"""Three fresh Jev consultations on can-implementation-task-list hardest decisions.

Every explanatory state field, instruction and option description is rewritten
in full across the three rounds. Technical identifiers, task IDs, numeric
facts and code spellings stay exact. No prior Jev answer appears in any
request. Usage: python3 consult.py (generate) ; python3 consult.py --send (3 calls).
"""
from pathlib import Path
import json
import os
import sys
import urllib.request
import datetime
import hashlib

P = Path(__file__).resolve().parent

state = {
'purpose': [
'Can is a programming language for AI coding agents. Correctness, stable contracts and observable product behavior outrank every other goal; total tokens per successful agent task is a secondary measured outcome, not a primary acceptance claim. The 24 September 2026 implementation task list T01-T27 is a plan, not a statement that any production change has shipped. There are zero external users and no compatibility requirements for old syntax, ABI, spellings, generated TypeScript layouts or goldens. Generated TypeScript must lower equivalent Can operations to native JavaScript/Bun operations, adding only adapters that preserve Can contracts and immutability. Gates 1-5 require linked reproducible evidence; no language mechanism is credited by a pilot. Select implementation judgments on this evidence without asking the user.',
'This consultation concerns an agent-oriented language where reliable behavior, dependable edits and externally visible results come first, while whole-task token cost across a successful assignment is tracked afterwards as a subordinate metric. The dated 24 September 2026 graph of tasks T01 through T27 proposes future work; it asserts no shipped compiler or runtime change. No outside adopters exist, so preserving prior source forms, binary interfaces, emitted file shapes or recorded goldens is explicitly not required. Emitted TypeScript should delegate each matching operation to the corresponding native JavaScript or Bun primitive, introducing extra helpers solely where Can invariants or frozen values demand them. Each gate from 1 to 5 needs repeatable linked proof, and a trial run alone never earns a mechanism its place. Reach a technical selection from the supplied facts alone, with no further user question.',
'Judge implementation choices for a language whose audience is coding agents rather than people. Sound execution, robust refactoring and checkable product effects dominate; the summed tokens of an entire victorious task, prompts through validation, are a lesser quantified objective. Tasks T01-T27 dated 24 September 2026 describe intended construction only and claim no delivered production edit. With no external community, backwards compatibility for grammar, interfaces, earlier spellings, generated TypeScript organization or prior goldens carries no weight. Lowering must prefer identical native JavaScript/Bun behavior in generated TypeScript, reserving bespoke adapters for upholding Can guarantees and unchangeable data. Proof for Gates 1 through 5 has to be reproducible and linked; pilot anecdotes cannot certify a feature. Make the call from the material provided here, posing no question to the user.',
],
'task_graph': [
'T01 freezes a dated baseline and repeatable harness: supported Bun/compiler versions, disposable build directories, core regression commands, exact current-vs-new diagnostic fixtures, and a fixture registry with creation/refactor/repair prompts, held-out variants, hidden checks and model/effort settings under the evaluation protocol. After T01, T02/T03/T06/T07/T18/T19 may proceed in parallel. T03 unlocks T04/T05/T08; T05 and T06 unlock T10; T03/T05/T06/T07 unlock T21. T10 unlocks T11/T12/T13; T21 unlocks T22. T09 integrates T02-T08 across compiler, runtime metadata, package graph, formatter, CLI diagnostics, docs and examples, runs full regression plus cross-feature negatives (owner record through generic/package boundary, variant leaf across imports, fixture link after alias rename, error report after lineage change), regenerates outputs once from integrated source, and completes Gate 1/2 core integration only when reproducible; T09 precedes T16 while invoice and browser lanes continue on their stated prerequisites. T10 adds source action declarations with checked catalogue symbols using the exact-path parser/type contract, with the selected captured paths as the public invoice declarations and no compatibility route. T14 builds invoice protected read/write operations with three thin action handlers against a real disposable database. T17 runs the complete server matrix for Gate 3; T19 pins official Bun 1.4.2 Linux x64 on Debian 13 amd64/glibc; T20 qualifies Gate 4 server SaaS on the installed Linux artifact. T21 implements canlc build --target browser as a distinct main-thread root/profile with transitive capability closure and a compiler-produced content-addressed same-origin asset. T26 updates docs and runs held-out agent comparisons; T27 performs the final release audit. Never merge two workers\' compiler or catalogue edits blindly; integrate against one locked revision and rerun affected checks.',
'The graph starts with T01, which locks the implementation baseline and test rig: approved Bun and compiler releases, throwaway build folders, central regression invocations, paired old-versus-new diagnostic fixtures, plus a registered set of construction, restructuring and repair prompts with reserved variants, concealed checks and fixed model/effort configurations per the evaluation protocol. Once T01 is done, workers may pursue T02, T03, T06, T07, T18 and T19 concurrently. Completion of T03 enables T04, T05 and T08; T05 together with T06 enables T10; T03, T05, T06 and T07 jointly enable T21. T10 enables T11, T12 and T13; T21 enables T22. T09 unifies T02 through T08 over the compiler, package graph, runtime metadata, formatter, public documentation, CLI diagnostics and samples, executes the whole compiler/runtime regression and cross-cutting negatives (an owner record crossing a generic and package edge, a variant leaf crossing an import, a fixture link surviving an alias rename, an error report surviving a lineage change), rebuilds generated outputs a single time from the unified source, and closes Gate 1/2 only on repeatable results; T09 gates T16, whereas the invoice and browser tracks advance under their own named prerequisites. T10 introduces source action declarations and verified catalogue symbols from the exact-path parsing and typing agreement, promoting the chosen captured routes to the public invoice surface with no legacy alias. T14 delivers the guarded invoice reads and writes plus three slim action handlers on a genuine throwaway database. T17 executes the full server product matrix for Gate 3; T19 fixes official Bun 1.4.2 Linux x64 onto Debian 13 amd64/glibc; T20 certifies Gate 4 server SaaS against that installed Linux build. T21 ships canlc build --target browser as its own main-thread root and profile with a transitive capability seal and a compiler-emitted content-hashed same-origin bundle. T26 refreshes documentation and runs reserved agent trials; T27 closes with release audit. Compiler or catalogue changes from separate workers must never be combined sight unseen; reconcile onto a single pinned revision and repeat impacted verification.',
'T01 establishes the repeatable foundation: recorded Bun/compiler versions, ephemeral build areas, canonical regression commands, precise before-and-after diagnostic fixtures, and advance registration of agent prompts for creation, refactor and repair with held-out forms, hidden assertions and model/effort levels governed by the evaluation protocol. Following T01, the branches T02, T03, T06, T07, T18 and T19 can run side by side. T03 is the prerequisite for T04, T05 and T08; T05 plus T06 gate T10; T03, T05, T06 and T07 gate T21. T10 gates T11, T12 and T13; T21 gates T22. T09 consolidates T02-T08 throughout compiler internals, runtime metadata, the package graph, formatting, command-line diagnostics, published docs and examples, performs exhaustive regression and intersectional failure tests (owner values at generic/package seams, variant leaves at import seams, fixture linkage after renames, error reporting after lineage edits), regenerates derived files exactly once from the consolidated tree, and satisfies Gate 1/2 solely with reproducible outcomes; T16 waits on T09, while invoice and browser work follows its listed dependencies. T10 specifies source-level action declarations and checked catalogue entries beginning from the exact-path contract, elevating the approved captured paths to the official invoice endpoints without a fallback path. T14 constructs the protected invoice readers and writers with their three narrow handlers on an actual disposable store. T17 grades the entire server matrix for Gate 3; T19 standardizes on official Bun 1.4.2 Linux x64 under Debian 13 amd64/glibc; T20 validates Gate 4 server SaaS on the deployed Linux artifact. T21 provides canlc build --target browser as a separate main-thread entry and profile carrying a transitive capability envelope and a compiler-generated content-addressed same-origin artifact. T26 revises manuals and executes held-out agent evaluations; T27 audits release readiness. Do not naively combine compiler or catalogue edits from two authors; converge on one frozen revision and re-execute touched checks.',
],
'evidence_limits': [
'Only bounded disposable probes exist. A two-package owner probe passed 11 assertion roots showing constructor, with, JSON decode, assertion-input and supplied-completion bypasses of rejecting factories. A nested-pattern probe ran 13 cases where final decliend and nested paidd silently bind and identical paid text tests a leaf under payment but binds under int. A 16-case variant matrix passed 12 builds with 24 assertions and 4 expected checker rejections, showing path-sensitive direct rejection with bridge/leaf admission. A generic-helper probe passed 28/28 assertions with disjoint singleton failure domains. A 12-check FormData probe showed equal-length parallel arrays misassociating cross-row values. Route-capture work carries 82 trial assertions on pinned Bun with strict 400/404/405 boundaries. An HTMX probe observed a real 503 fragment arriving over HTTP yet leaving stale 422 feedback visible. An 18-assertion invoice slice passed without any live database, HTTP response or DOM. No live production invoice flow, webhook ledger, browser grid, or Linux install qualification has passed. No held-out agent creation/refactor/repair comparison has run; whole-task token effects are unmeasured. Jev probabilities and confidence values are advisory only, not acceptance proof, and these calls run no Can code and establish no calibration.',
'Available measurements are narrow and throwaway. Eleven passing roots in a values/importer experiment demonstrated invalid inhabitants escaping through ordinary construction, copy replacement, structural decoding, fixture arguments and mocked completions despite factory refusal. Thirteen pattern trials revealed a last-arm decliend and an inner paidd quietly becoming binders, plus one spelling acting as a nominal check beneath payment and as a capture beneath int. Sixteen variant trials yielded twelve successful builds, twenty-four satisfied assertions and four anticipated static refusals, exposing a route-dependent direct block alongside bridge and shared-leaf acceptance. Twenty-eight of twenty-eight helper assertions held across two single-error caller domains. Twelve FormData checks proved bare parallel lists can attach one row\'s price to another row after omissions. Eighty-two route assertions on fixed Bun define guarded native dispatch with method-first and static-within-method order and exact malformed-escape/dot/encoded-separator handling. A browser trial watched an authentic 503 body arrive while outdated 422 guidance stayed on screen. Eighteen invoice assertions completed with no genuine store, wire reply or document model. No certified live invoice path, replay ledger, grid client, or Debian/Bun deployment exists. Reserved agent trials are unexecuted and token consequences unknown. Model scores advise but never certify; the present calls execute no generated program and measure no domain accuracy.',
'Evidence stops at small ephemeral spikes. An eleven-root validation study passed while foreign code minted empty email and zero quantity via constructors, with expressions, generic JSON projection, assertion parameters and supplied results. A thirteen-trial nesting study passed while a terminal decliend and a deep paidd silently captured, and the same paid token checked membership under one expected type and captured the whole value under another. A sixteen-trial variant survey produced twelve builds, twenty-four passes and four designed checker denials, documenting direct refusal that bridge indirection or leaf sharing already circumvents. A helper reuse study held 28 of 28 checks with callers holding disjoint single failures. A twelve-trial keyed-row study established that aligned same-length arrays silently cross-associate fields when rows drop controls. Eighty-two capture assertions pin native Bun behavior with strict single-segment decoding, canonical integer spelling and guarded callbacks reentering the service lifecycle. A live HTMX observation caught a genuine 503 payload failing to displace prior 422 output. An eighteen-check invoice sketch ran with neither durable rows, wire statuses nor rendered nodes. No production invoice mutation, idempotent webhook, living grid, or Linux artifact suite has cleared. No comparative agent workload with fresh held-out cases has started, so token claims would be speculation. The model distributions guide engineering thought but prove nothing here, and no call in this set runs Can artifacts or gauges calibration.',
],
'fixed_constraints': [
'Every compiler or catalogue change must add positive, negative and diagnostic-span tests plus regenerated TypeScript and goldens as applicable. Every edit to authored runtime/ or tools/runtime/ TypeScript must run bun run lint:fix:runtime, bun run format:runtime, bun run check:runtime and the relevant tests, using bun run lint:runtime --format=agent for compact diagnostics. Never hand-edit generated runtime/catalogue.ts or pinned vendor files. Observable product tests must inspect native HTTP, browser and database results, not merely a Can assertion or Jev advice. Each qualification report must record the actual model and version, compiler revision, environment and failures. Deferred mechanisms stay out of the build: DI-03 finite error-set parameters, DI-08 capture-binding syntax, DI-14a mutation RETURNING, DI-17 new native AI wrapper/batch/callable forms, DI-18 static escape/consumed-fault additions, DI-19 unrestricted SDK imports, DI-20 bulk immutable collections, DI-22 named-field constructors and DI-23 multiline grammar. Workers must not invent them to make a test pass.',
'Each compiler or catalogue edit ships with passing-case coverage, failing-case coverage and span-precision checks for diagnostics, together with refreshed generated TypeScript and golden files wherever relevant. Any modification under authored runtime/ or tools/runtime/ TypeScript requires bun run lint:fix:runtime followed by bun run format:runtime, then bun run check:runtime plus the scoped test selection, with bun run lint:runtime --format=agent available for terse findings. The generated runtime/catalogue.ts and locked vendor blobs are off limits for manual revision. Product-facing verification has to examine genuine wire replies, rendered documents and stored rows rather than stopping at an attached Can check or a model recommendation. Every qualification write-up logs the concrete model identity and release, compiler commit, host details and observed faults. Postponed features remain excluded from construction: DI-03 finite error-set generics, DI-08 capture binders, DI-14a RETURNING on mutation, DI-17 fresh AI wrapper/batch/callable natives, DI-18 static escape or consumed-fault extensions, DI-19 open SDK imports, DI-20 batched immutable collections, DI-22 named-field construction and DI-23 multiline syntax. Implementers may not conjure them to satisfy a test.',
'All compiler and catalogue revisions carry three test kinds, success paths, rejection paths and diagnostic-location precision, and rebuild emitted TypeScript with golden snapshots where they apply. All hand-written TypeScript beneath runtime/ or tools/runtime/ is followed by bun run lint:fix:runtime, bun run format:runtime, bun run check:runtime and pertinent suites, condensing linter output through bun run lint:runtime --format=agent when needed. Manual alteration of generated runtime/catalogue.ts or frozen vendor sources is forbidden. Externally visible behavior must be confirmed on true HTTP exchanges, live browser state and durable database content, never solely via an in-language assertion or advisory scores. Reports of qualification state the precise model and build, compiler revision, execution environment and each failure seen. The deferred set is not buildable work: DI-03 authored finite error sets, DI-08 capture-binding sugar, DI-14a mutation RETURNING, DI-17 novel AI wrapper/batch/callable intrinsics, DI-18 static escape or consumed-fault machinery, DI-19 arbitrary SDK inclusion, DI-20 bulk immutable tables, DI-22 named-field initializers and DI-23 multiline continuations. No worker invents those mechanisms to force a suite green.',
],
}

questions = {
'integration_strategy': {
'instructions': [
'Which core-integration strategy should T09 enforce for T02-T08, balancing reproducible contracts against parallel invoice, browser and webhook progress? Do not claim measured token savings.',
'Select the unification approach for the T02 through T08 compiler and catalogue changes that best protects stable cross-feature behavior while respecting the stated lane dependencies. Treat token impact as unknown.',
'Choose how to consolidate the core semantic edits before Gate 1/2, weighing single-source consistency against continued lane velocity. Decide from contract reliability, not prose length.',
],
'criteria': {
'single_locked_integration': [
'Integrate T02-T08 against one locked revision across compiler, runtime metadata, package graph, formatter, CLI diagnostics, docs and examples. Run full regression plus cross-feature negatives covering an owner record through a generic/package boundary, a variant leaf across imports, a fixture link after an alias rename, and an error report after a lineage change. Regenerate outputs once from the integrated source and record any intended source break. Gate 1/2 passes only on reproducible results; T16 waits on T09 while invoice and browser lanes advance on their own prerequisites.',
'Unify the T02 to T08 edits on a single pinned tree spanning checker, emitted metadata, package identity, formatting, command output, manuals and samples. Execute the complete regression and intersectional denials for protected values at generic and package seams, variant leaves at import seams, scenario linkage across renames, and report keys across lineage edits. Rebuild derived artifacts exactly once from that tree and note deliberate breaking changes. Credit Gate 1/2 solely when reruns match; hold T16 behind T09 and let invoice and browser tracks follow their named gates.',
'Converge all core edits from T02 through T08 onto one frozen baseline covering compilation, runtime records, package resolution, pretty-printing, diagnostic rendering, documentation and illustrations. Verify with exhaustive suites and seam-spanning counterexamples spanning owner/generic/package crossings, variant/import crossings, fixture/alias crossings and error/lineage crossings. Emit generated files a single time from the converged baseline and log intentional incompatibilities. Award Gate 1/2 only for repeatable green runs; sequence T16 after T09 and permit invoice and browser efforts under their listed dependencies.',
],
'per_lane_incremental': [
'Let each core lane land and regenerate its own goldens independently, merging opportunistically and postponing cross-feature negatives until invoice or browser qualification exposes a conflict.',
'Permit every core track to integrate and refresh its snapshots on its own cadence, combining branches when convenient and deferring seam-spanning failure tests until product lanes surface a mismatch.',
'Allow T02-T08 authors to ship separate integrations with per-task derived files, reconciling branches ad hoc and delaying intersectional checks until later server or client suites demand them.',
],
'block_all_on_core': [
'Freeze every invoice, browser, webhook and shutdown branch until T09 fully passes, permitting no parallel lane work even where the graph names an earlier prerequisite as sufficient.',
'Halt all product and platform tracks pending complete T09 sign-off, refusing concurrent effort on invoice, browser, webhook or shutdown tasks regardless of their stated independent prerequisites.',
'Suspend each downstream lane entirely while core unification completes, blocking invoice, browser, webhook and shutdown activity until Gate 1/2 is fully earned, with no overlap allowed.',
],
},
},
'replay_ledger': {
'instructions': [
'Which grid-write uncertainty contract should T14 implement for invoice mutations, given lost acknowledgements, foreign/nonexistent access, and HTML/JSON case mapping? Judge disclosure, idempotency and reconciliation clarity.',
'Pick the invoice replay and denial policy that best handles uncertain commits, cross-tenant reads and typed save outcomes across both adapters. Judge idempotent effects and honest failure signals.',
'Decide how the protected write should scope, persist and replay grid attempts while keeping denial behavior and adapter results explicit. Weigh duplicate suppression against retry simplicity.',
],
'criteria': {
'same_transaction_ledger': [
'Store a durable actor, invoice, operation_id and canonical-request-digest entry with the committed response in the same database transaction as the invoice mutation. A same-ID same-digest replay returns the prior result with no second effect; same ID with a different digest is a conflict. Foreign and nonexistent invoices share one nondisclosing 403 after authentication; malformed captures fail 400 before protected entry. Map validation to five HTML and five JSON save cases plus three typed GET load cases, enforcing the 8192-byte JSON POST cap and the 2048-byte/64-row HTML form caps. The HTML client rereads after uncertainty; the grid keeps its identified attempt and either retries the identical payload and ID or performs an authorized read. Bounded retention preserves the reconciliation path; renderer failure after commit may surface 500 with uncertain state.',
'Persist the replay record, binding authenticated principal, invoice key, client operation identifier, content hash and acknowledged reply, atomically alongside the guarded row change. Repeating the same identifier with matching bytes replays the stored outcome without duplicating the business effect, while the same identifier with altered bytes reports a clash. Unknown and foreign invoice keys receive an identical opaque 403 once identity is known; corrupt path encodings are rejected 400 ahead of guarded logic. Expose five HTML save results, five JSON save results and three JSON load results with typed shapes, honoring an 8192-byte JSON body ceiling and 2048-byte/64-row HTML form ceilings. After ambiguity the form rereads before writing again, and the grid preserves its tagged attempt for a byte-identical resend or a permitted snapshot fetch. A limited retention window sustains later reconciliation; a render fault following durable commit can present 500 with unknown effects.',
'Write the idempotency tuple of actor plus invoice plus operation token plus payload digest plus prior answer inside the identical transaction that applies the protected invoice edit. An exact identifier-and-bytes repeat fetches the earlier committed answer and performs no further mutation; an identifier repeat with divergent bytes becomes a conflict outcome. Nonexistent and other-tenant targets collapse to a single unrevealing 403 post-login; defective captures are refused 400 prior to authorization checks. Publish five HTML store endings, five JSON store endings and three JSON fetch endings in checked types, applying the 8192-byte JSON POST bound and the 2048-byte/64-row HTML form bounds. Following an unclear commit the HTML flow reloads state before another store, while the grid retains its labeled try for either a verbatim redelivery under the same token or an approved reread. Finite storage keeps the recovery route; post-commit presentation faults may emit 500 without guaranteeing rollback.',
],
'separate_ledger_transaction': [
'Commit the invoice mutation first, then persist the replay/outbox record in a later transaction with background reconciliation, accepting a window where the row changed but the ledger entry is absent.',
'Apply the guarded row update in one transaction and file the idempotency and dispatch rows afterwards in another commit, reconciling gaps asynchronously and tolerating a span with effects but no replay key.',
'Split mutation and bookkeeping into successive commits, landing the invoice change before its operation log, and repair the interim blind interval with a sweeper rather than atomicity.',
],
'client_new_id_retry': [
'After any 503, dropped connection, abort or disposal, have the browser mint a fresh operation_id for each retry, with the server treating every new ID as a distinct mutation that may duplicate the business effect.',
'On uncertain endings including timeouts, disconnects, cancellations and view teardowns, generate a new client token per attempt and let the backend apply each token as an independent write, risking repeated effects.',
'Resolve ambiguity by issuing a replacement operation token on every resend, so the service interprets each delivery as a new invoice change and can commit the same intent multiple times.',
],
},
},
}
questions['browser_closure'] = {
'instructions': [
'Which browser build boundary should T21/T22 enforce for the Can-authored grid, given shared wire contracts, server secrets, and DOM/Fetch safety? Judge least privilege and verifiability.',
'Choose the compilation and packaging rule for canlc build --target browser that best isolates the grid client from server capabilities while keeping wire parity checkable.',
'Decide how strictly the browser target must separate from server modules and unvetted scripts, weighing auditability and capability safety against authoring convenience.',
],
'criteria': {
'strict_transitive_closure': [
'Build canlc build --target browser as a distinct main-thread root and profile with a compiler-checked transitive browser capability closure over callable and generic paths. Exclude SQL, process, files, secrets and server crypto, audit emitted imports and sourcemaps, share locked pure packages and strict wire codecs, and test Bun/browser int64, finite floats, variants, option, duplicate/unknown fields and owner wire boundaries in named browsers. Use opaque app/view/node/state handles, safe native DOM/text/attributes/focus, event snapshots, view-scoped listener/timer disposal and versioned immutable replacement. The asset is compiler-produced, content-addressed and same-origin. No arbitrary authored JS/TS or worker profile is admitted; Fetch abort is local cancellation only, never proof of server rollback.',
'Compile the browser program through its own main-thread entry and target profile, verifying every reachable declaration, specialization and callback for browser fitness. Bar database handles, operating-system processes, filesystem paths, hidden credentials and server-side cryptography even via wrappers or generics, then inspect the output graph and maps for leaks. Reuse the pinned pure contract libraries and identical strict serialization on both runtimes, proving integer, float, variant, optional, extra-field and protected-record edges across declared browser versions. Expose only narrow opaque handles for application, view, node and state with guarded construction, text-centric rendering, snapshotted events, owner-tied cleanup and compare-and-publish state. Ship solely a compiler-built content-hashed same-origin module; forbid hand-written scripts and background-thread profiles. Treat network cancellation as client-side abandonment without rollback meaning.',
'Treat the browser artifact as an independent main-thread build whose whole callable, generic and reference closure passes a browser-capability gate. Deny transitively any path to SQL pools, process control, file access, environment secrets or privileged server ciphers, and scan generated modules and mappings for forbidden references or secret bytes. Keep pure shared dependencies and byte-exact wire logic common to Bun and each supported browser, covering big integers, bounded floats, closed variants, optional values, surplus or repeated members and owner-record translation. Model UI through opaque application, view, node and versioned-state tokens with main-thread DOM creation, text-only updates, checked attributes, focus control, immutable event copies, scoped handler/timer release and atomic snapshot replacement. Publish exclusively a compiler-derived content-addressed same-origin script under a tight content policy; exclude custom JavaScript bundles and worker execution. Interpret Fetch interruption as a local halt that says nothing about committed server work.',
],
'runtime_guarded_shared': [
'Use one shared build profile for Bun and browser, bundle server-capable imports, and rely on runtime checks at each call site to refuse SQL, process, file, secret or server-crypto use when running in the browser.',
'Keep a unified compilation pipeline for both runtimes, ship server-reaching code inside the client bundle, and block forbidden operations dynamically if the browser path happens to invoke them.',
'Merge server and browser outputs into a common bundle with permissive static admission, depending on execution-time guards to intercept disallowed capability calls rather than compile-time closure.',
],
'permissive_bundling': [
'Admit arbitrary authored JS/TS, inline scripts, third-party browser bundles and a worker profile alongside compiler output, without a content-addressed same-origin restriction or capability audit.',
'Open the browser target to hand-written modules, embedded script tags, external client libraries and threaded execution next to generated code, dropping the single-artifact hash and origin limits plus the import review.',
'Permit custom script authorship, third-party inclusions and worker-based execution within the browser build, removing the compiler-only content-hashed same-origin artifact rule and the emitted-graph security inspection.',
],
},
}

for entries in state.values():
    assert len(entries) == 3 and len(set(entries)) == 3, "state field must have 3 distinct phrasings"
for q in questions.values():
    assert len(set(q['instructions'])) == 3, "instructions must have 3 distinct phrasings"
    for entries in q['criteria'].values():
        assert len(entries) == 3 and len(set(entries)) == 3, "each option must have 3 distinct phrasings"

for i in range(3):
    payload = {
        'model': 'jev-latest',
        'state': {k: v[i] for k, v in state.items()},
        'questions': {
            k: {
                'type': 'choice',
                'instructions': q['instructions'][i],
                'criteria': {key: v[i] for key, v in q['criteria'].items()},
            } for k, q in questions.items()
        },
    }
    (P / f'request-{i+1}.json').write_text(json.dumps(payload, indent=2) + '\n')

hashes = {}
for i in range(1, 4):
    body = (P / f'request-{i}.json').read_bytes()
    hashes[f'request-{i}.json'] = hashlib.sha256(body).hexdigest()
(P / 'wording-audit.json').write_text(json.dumps({
    'review': 'Manually checked equal facts, constraints and alternatives across all three requests before sending. Each of the 4 state fields, 3 instructions and 9 option descriptions has a distinct complete phrasing (48 fields). Task IDs (T01-T27), gate names, Bun 1.4.2, Debian 13 amd64/glibc, canlc build --target browser, operation_id, status codes, byte/row caps, DI identifiers, probe counts and code spellings are intentionally stable. No response or favored recommendation appears in any later request state.',
    'same_facts': [
        'T01 baseline/harness/registry; parallel T02/T03/T06/T07/T18/T19; unlock chain T03->T04/T05/T08, T05+T06->T10, T03/T05/T06/T07->T21, T10->T11/T12/T13, T21->T22; T09 integrates T02-T08 before T16 with one regeneration and Gate 1/2 on reproduction',
        'T10 exact-path contract with captured public invoice paths and no compatibility route; T14 protected ops with 5 HTML + 5 JSON save cases and 3 GET load cases; T17 Gate 3; T19 Bun 1.4.2 on Debian 13; T20 Gate 4; T21 distinct browser root/profile with content-addressed same-origin asset; T26 agent trials; T27 audit',
        'Probes: 11 owner roots, 13 nested-pattern cases, 16-case variant matrix (12 builds/24 pass/4 rejections), 28/28 helper assertions, 12 FormData checks, 82 route assertions, HTMX 503 unswapped observation, 18-assertion invoice sketch with no live DB/HTTP/DOM',
        'Limits: no live invoice/webhook/grid/Linux qualification; no held-out agent comparison; token effects unmeasured; Jev output is advisory; calls run no Can code and establish no calibration',
        'Constraints: positive/negative/span tests plus regenerated goldens; bun run lint:fix:runtime, format:runtime, check:runtime; lint:runtime --format=agent; never hand-edit runtime/catalogue.ts or vendor files; native HTTP/browser/DB inspection; record model/version/revision/env/failures; deferred DI-03/DI-08/DI-14a/DI-17/DI-18/DI-19/DI-20/DI-22/DI-23 excluded',
    ],
    'limit': 'Text inequality plus manual semantic review cannot prove absence of framing effects; investigate disagreement and treat agreement as advice, not proof.',
    'request_sha256': hashes,
}, indent=2) + '\n')
print(json.dumps({'generated': hashes}, indent=2))

if '--send' in sys.argv:
    key = os.environ['TYPESAFE_API_KEY']
    for i in range(1, 4):
        req = urllib.request.Request(
            'https://api.typesafe.ai/v1/systemone',
            data=(P / f'request-{i}.json').read_bytes(),
            headers={'Content-Type': 'application/json', 'Authorization': 'Bearer ' + key},
        )
        start = datetime.datetime.now(datetime.timezone.utc).isoformat()
        with urllib.request.urlopen(req, timeout=60) as r:
            body, status = r.read(), r.status
        (P / f'response-{i}.json').write_bytes(body + b'\n')
        (P / f'response-{i}.metadata.json').write_text(json.dumps(
            {'startedAt': start, 'status': status, 'endpoint': 'v1/systemone'}, indent=2) + '\n')
        print(json.dumps({'request': i, **json.loads(body)}))

