"""Prepare three independently worded requests before inspecting any answers."""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
states = [
 {
  "objective": "Review Can as a possible default language for SaaS servers and browser clients. There are zero external users, so compatibility is not required. Preserve immutable data, explicit domain failures and resource ownership. Lower operations to native JavaScript/Bun with only contract-preserving adapters. This is a design review, not permission to implement changes.",
  "progress": "At revision 2cb1bc3, real shared handler-free actions bind request identity and startup services on the server. Browser builds now ship audited JavaScript with an explicit ownership runtime. Exported generics compose through symbolic checking. These are implemented strengths, not missing proposals.",
  "host_boundary": "Host operations form a closed compiler-owned catalogue; ordinary Can packages cannot add JavaScript/npm integrations. DOM events expose kind, target, value and key, but no checked state, files, modifiers or composition data. set_attribute uses native setAttribute: after a user edits an input, setting its value attribute need not change its current value. Browser storage/history and browser WebSocket are absent. Connection endpoints are literal and HTTP paths stay at that origin. This protects capabilities but limits rich widgets and tenant-selected webhook destinations.",
  "library_errors": "Public generic value composition now works. Authored emits lists still enumerate concrete error types, with no error-set parameter; native arrays can preserve callback-specific bounds. Fixed application bounds and nominal result data are available alternatives. The unresolved use case is a reusable retry/tracing helper serving two unrelated callback error sets without widening or losing their distinctions.",
  "assertions": "Every authored function requires assertion rows. An external owner record cannot be directly constructed by a consumer. Calling its fallible smart constructor inside an assertion input is rejected because input expressions cannot handle domain failures; rows have no setup region. Extra helpers or owner-provided total samples can work. The issue is composing legitimate setup without permitting fabricated owner values or skipping verification.",
  "iteration": "A freshly checked and emitted synchronous tail-recursive countdown passes at 100 steps and overflows the native stack at 20000 on local Bun 1.4.2. This is not a claimed tail-call guarantee violation. Existing arrays have native stack-safe folds. Dynamically continuing pagination and state machines need an intentional contract. Changes must retain evaluation order, completion identity, fixture invocation identity and useful diagnostic bounds.",
  "lifetime": "Race selects a winner while ownership retains losing work until scope drain. A current-runtime probe verifies root exit waits for a loser. HTTP request scope drains before returning the response. SQL awaits Bun.SQL without caller query or transaction deadlines; SQLite has a busy timeout and external database settings can help. Declared server HTTP clients already have deadlines, while shared browser action requests expose no authored deadline or cancellation operand. Closing resources early would be unsafe, and cancellation cannot undo writes or prove rollback. Commit uncertainty is explicit.",
  "ui": "The invoice grid really implements state snapshots, compare-and-swap, late-result protection, view disposal and DOM rendering in Can. It repeats field handlers and manual rebuilding/focus restoration. Named functions and generic callables can compose libraries. Missing native input information must be supplied whichever UI abstraction is chosen. There is no evidence yet that a declarative component syntax is necessary.",
 },
 {
  "objective": "Assess whether Can should be the usual choice for browser-and-server SaaS development. Since no external customers use it, historical compatibility carries no requirement. Keep values immutable, failures explicit and handles owned. Generate equivalent native JS/Bun behavior, adding adapters only for Can semantics. Recommendations here authorize no implementation work.",
  "progress": "The examined commit, 2cb1bc3, already provides handler-independent shared action declarations, server bindings with request authentication and initialized services, audited browser JS delivery with explicit owner context, and symbolic composition of exported generics. Treat this foundation as present.",
  "host_boundary": "Compiler-maintained entries are the only host API surface; user libraries cannot introduce npm or JavaScript calls. Browser snapshots contain only kind/target/value/key, excluding checkbox status, file selections, modifier keys and IME composition. The attribute setter delegates to setAttribute, which does not necessarily overwrite a dirty input's live value. No browser persistence, history or browser WebSocket API is admitted. HTTP connection origins are fixed literals and requests cannot depart from them. These limits enforce capability control while excluding some widgets and customer-configured webhook targets.",
  "library_errors": "Generic functions can now invoke other public generic contracts. User-authored emits declarations nevertheless require finite concrete error entries and cannot quantify over an error set, unlike callback-bound propagation in built-in array operations. Applications can choose fixed bounds or encode success/failure in nominal data. We need to evaluate a general retry or tracing combinator used with two disjoint callback failure families while retaining each family's precision.",
  "assertions": "All functions must carry executable assertion examples. A client package is forbidden to manufacture another package's owner record. Its validating constructor may fail, and placing that call in a row's argument fails checking: arguments are expressions without failure handling, and rows offer no preparation block. A separate helper or exported total sample provides a possible workaround. Any improved setup must still use authorized construction and retain the verification obligation.",
  "iteration": "On Bun 1.4.2, a new compiled synchronous self-tail countdown completes 100 iterations but reaches stack overflow at 20000. The language never promised elimination of that recursion. Native collection folds already avoid stack growth for arrays. A policy remains needed for pagination and state machines with dynamically determined continuation. Preserve once-only ordered evaluation, completion and fixture identities, and tractable source diagnostics when comparing remedies.",
  "lifetime": "Choosing a race result leaves losers owned; the enclosing scope waits for them. A probe against today's runtime establishes this root-wait behavior, and the HTTP server publishes a response only after request drainage. Query and transaction calls await native SQL without an authored deadline. SQLite busy timing and database-side configuration offer partial controls; Declared backend HTTP clients already enforce time budgets, but browser action calls provide no author-supplied timeout or abort input. Disposing still-used resources is invalid; stopping a call neither reverses a write nor establishes rollback. The implementation models uncertain commits.",
  "ui": "Can code in invoice-grid already manages immutable state snapshots with version checks, stale replies, disposal and native DOM updates. Similar handlers and rebuilding/focus logic recur across fields. Functions and generic callbacks can supply reusable library components. Every proposed UI approach still requires additional native input observations. Current evidence has not established a need for language-level declarative components.",
 },
 {
  "objective": "Judge Can's suitability as the preferred implementation language across SaaS frontend and backend. No existing external user constrains a redesign. Retain explicit error contracts, immutable values and safe resource lifetimes; implement them through JavaScript/Bun primitives plus necessary semantic adaptation. This exercise chooses review advice only.",
  "progress": "Current source at 2cb1bc3 already joins client and server through common actions without embedded handlers, supplies server-side actor/service context, produces structurally audited browser bundles with explicit ownership, and checks compositions of exported generics symbolically. Do not classify those accomplishments as outstanding features.",
  "host_boundary": "A fixed catalogue owned by the compiler controls native access, so an authored package has no facility to wrap a new npm/JavaScript library. Event records report kind, target, value, key; checked/file/modifier/IME data is unavailable. Native setAttribute underlies set_attribute and updating a value attribute leaves an already edited input's current value potentially unchanged. Storage, history and browser WebSockets have no exposed operations. Literal connection origins also prevent runtime HTTP destinations outside that origin. The controlled surface both preserves restrictions and blocks certain interactive widgets and per-tenant outbound webhook URLs.",
  "library_errors": "Checked public generics support composition over values, yet authored failure lists are concrete and offer no variable for a set of errors. Array built-ins have callback-dependent propagation that authored wrappers cannot express in the same form. Nominal outcome records and application-specific fixed bounds remain usable. The comparison task is one reusable trace/retry wrapper with two unrelated callback failure sets, keeping the caller's precise alternatives.",
  "assertions": "The testing rule attaches assertion rows to every function. When a parameter is a foreign owner record, its consumer cannot invoke the record constructor directly. Using an approved but fallible constructor as a row input also fails: expression-only inputs lack domain-completion handling and assertion syntax has no setup body. Authors may add unwrapping helpers or consume total sample factories. Improve lawful test preparation without opening an owner-construction bypass or weakening mandatory checking.",
  "iteration": "The current emitter's synchronous tail-recursive countdown was checked anew: 100 steps succeed, whereas 20000 exhaust the local Bun 1.4.2 stack. Tail-call optimization was never guaranteed. Array folds already use native bounded-stack traversal. Unbounded-by-input continuation in pagers or state machines still deserves a selected model. Preserve argument evaluation semantics, error-completion identities, fixture call paths and manageable diagnostics in any proposed lowering.",
  "lifetime": "An observed runtime race delivers its selected value before the owning root can exit; remaining participants delay scope closure. HTTP responses wait at that request-scope closure. SQL query/transaction awaits have no caller-supplied deadline, although SQLite busy limits and administrator database settings are available, and server-side declared HTTP operations enforce deadlines; the browser action API lacks an authored time budget or cancellation argument. A lease cannot be revoked safely while in use. Cancellation gives no reversal of side effects or certainty of rollback; unknown commit outcomes already have their own representation.",
  "ui": "Invoice-grid is implemented in Can, including snapshot/CAS state, stale-response protection, scoped views and DOM painting. Repeated field callbacks and explicit redraw/focus repair make composition costly. Ordinary functions plus generic callables are available for abstraction. Native input coverage must improve for either library or syntax solutions. No experiment yet proves a new declarative component construct is required.",
 }
]

decisions = {
 "host_extension": (
  ["Which next host-access strategy most improves broad SaaS suitability while retaining capability guarantees?", "Choose the next native-access direction that best expands SaaS applicability under the existing safety constraints.", "Select the most useful immediate host-integration policy for recommending Can across SaaS use cases without losing its contracts."],
  {
   "catalogue": ["Expand the central catalogue for demonstrated use cases and retain compiler-only host admission.", "Keep native additions compiler-owned and add the APIs that concrete applications require.", "Maintain closed host access while extending built-ins for proven application needs."],
   "reviewed_adapters": ["Design an explicitly trusted adapter package boundary with declared types, failures, target capabilities, ownership and conformance checks.", "Introduce vetted native wrapper packages specifying data/error contracts, target permissions, resource rules and tests.", "Permit reviewed host bindings through packages whose schemas, completions, platform admission, lifetimes and validation are explicit."],
   "companion": ["Keep the language surface fixed and support a documented companion JavaScript/service boundary for unsupported features.", "Leave native admission unchanged and integrate missing capabilities through an external JS component or service with a specified interface.", "Scope Can to its present APIs and formalize interoperation through separately implemented components or services."],
  }),
 "failure_abstraction": (
  ["What should be evaluated first for reusable helpers that preserve unrelated callback failures?", "Select the first design experiment for generic tracing/retry across distinct error families.", "Which authoring model deserves the first comparison for reusable wrappers retaining precise callback errors?"],
  {
   "error_rows": ["Prototype a small explicit finite error-set parameter in callable and function contracts.", "Test bounded error-row variables that are named explicitly in helper signatures.", "Explore a narrow quantified error-set facility with authored public bounds."],
   "result_data": ["Build the helpers with nominal result data and explicit adaptation at completion boundaries before changing syntax.", "First demonstrate outcome-data combinators and adapters to concrete emits contracts.", "Try ordinary typed success/failure values, translating to domain completions at application edges, before adding language machinery."],
   "fixed_bounds": ["Retain concrete application-specific bounds and accept separate helpers for different error families.", "Keep enumerated bounds, documenting duplicated or specialized wrappers as the supported pattern.", "Recommend distinct wrappers with fixed declared failures for each application family."],
  }),
 "assertion_setup": (
  ["How should lawful owner-value preparation in mandatory assertions improve first?", "Choose the next approach for preparing opaque domain values in attached tests without bypassing their constructors.", "What is the best first response to assertion inputs that require handling a validating constructor's failure?"],
  {
   "setup_region": ["Prototype an assertion setup region that runs ordinary checked construction and completion handling.", "Add a trial checked preparation block to assertion rows, retaining normal constructor and failure rules.", "Evaluate test-local setup bodies that build values through the same checked APIs and handle their outcomes."],
   "factory_pattern": ["Keep row syntax and standardize reusable test factories or helper functions with explicit failure policy.", "Document an economical factory/unwrap-helper pattern using existing function and row rules.", "Use present language forms to establish test-value helper conventions with deliberate failure behavior."],
   "scenario_coverage": ["Allow selected private helpers to satisfy testing obligations through explicit linked consumer scenarios instead of local rows.", "Explore inherited verification from named integration scenarios for designated internal helpers.", "Permit explicit scenario-based coverage of some private functions in place of separate attached examples."],
  }),
 "iteration": (
  ["Which stack-safety approach should be investigated first for dynamically continuing work?", "Select the first remedy to evaluate for stack growth in dynamic Can iteration.", "For pagination and state-machine continuation, which execution design should receive the next experiment?"],
  {
   "self_tail": ["Lower provably self-tail relay calls to native loops, preserving observable call/test behavior.", "Implement an experimental native loop transformation for checked self-tail calls with preserved semantics.", "Study elimination of direct tail recursion into native iteration while retaining observable identities."],
   "iteration_primitive": ["Prototype an explicit immutable-state iteration primitive that lowers to a native loop.", "Try a dedicated state-transition loop contract with immutable carried values and native execution.", "Evaluate a small typed iteration operation for immutable state, emitted as ordinary host looping."],
   "bounded_policy": ["Retain recursion limits and folds, recommending only bounded workloads until demand justifies new machinery.", "Document bounded recursion plus array traversal as the supported scope for now.", "Keep current recursion/fold behavior and make finite workload limits part of the recommendation."],
  }),
 "request_lifetime": (
  ["Which next execution contract best addresses request and shutdown latency without abandoning resource safety?", "Choose the first lifetime improvement for bounded service responses while retaining safe ownership.", "Select the next operational design experiment balancing latency guarantees with live resources and uncertain side effects."],
  {
   "operation_deadlines": ["Add effective native SQL/connection deadlines and compose operation budgets within the existing drain policy first.", "First expose enforceable per-operation time limits, especially SQL, while keeping all losers drained.", "Prioritize native cancellation/deadline support on individual operations under unchanged ownership completion."],
   "scope_policy": ["Design explicit cooperative cancellation and supervised loser ownership at request/scope boundaries.", "Introduce selectable scope policies for cancellation and transferring remaining work to supervised service ownership.", "Explore a request-level model with cooperative abort and explicitly supervised remaining participants."],
   "deployment_limits": ["Keep semantics and rely on database/proxy/process limits, with a documented external latency boundary.", "Use administrator timeouts and service supervisors as the supported budget mechanism without language changes.", "Specify deployment-enforced bounds and retain current operation and scope contracts."],
  }),
 "ui_composition": (
  ["After supplying missing native input capabilities, what should be the first UI composition investment?", "Assuming native event/property gaps are addressed, choose the next frontend abstraction experiment.", "Once the required DOM observations exist, which approach should first reduce repeated UI wiring?"],
  {
   "library": ["Build reusable Can field, keyed-row and lifecycle libraries, testing focus, IME, disposal and late responses.", "Exercise ordinary functions/generics through shared controls and list components with focus/composition/lifetime tests.", "Develop library-level controls and keyed collections that preserve input composition, focus and asynchronous disposal behavior."],
   "syntax": ["Prototype a declarative component syntax with an explicit state and lifetime model.", "Try language-level declarative views defining how state and resource scopes interact.", "Design a new component form with specified state updates and lifecycle semantics."],
   "interop_ui": ["Prefer a mature external UI implementation connected to Can through a typed boundary.", "Use an established frontend library outside Can and retain typed integration to Can logic.", "Delegate interactive presentation to an existing UI ecosystem via a checked interface."],
  }),
}

requests=[]
for index in range(3):
 req={"model":"jev-latest", "state":states[index], "questions":{}}
 for key,(questions,options) in decisions.items():
  req["questions"][key]={"type":"choice", "instructions":questions[index], "criteria":{k:v[index] for k,v in options.items()}}
 requests.append(req)
 (HERE/f"jev-request-{index+1}.json").write_text(json.dumps(req,indent=2,ensure_ascii=False)+"\n")

def prose(req):
 out={"state."+k:v for k,v in req["state"].items()}
 for key,q in req["questions"].items():
  out[key+".instructions"]=q["instructions"]
  out.update({key+".criteria."+k:v for k,v in q["criteria"].items()})
 return out

variants=[prose(r) for r in requests]
assert all(set(v)==set(variants[0]) for v in variants)
assert all(len({v[key] for v in variants})==3 for key in variants[0])
audit={"all_requests_prepared_before_consultation":True, "prose_fields_per_request":len(variants[0]), "all_corresponding_prose_rewritten":True, "manual_semantic_review":"Same observed facts, constraints, conditional premises, questions and alternatives in all three forms. Technical identifiers retained where useful. No earlier review or classifier verdict included.", "sources":["https://docs.typesafe.ai/llms.txt","https://docs.typesafe.ai/api.md","https://docs.typesafe.ai/primitives/choice.md"]}
(HERE/"jev-wording-audit.json").write_text(json.dumps(audit,indent=2)+"\n")
print(json.dumps(audit,indent=2))
