// Standalone native observations, not Can acceptance tests. Run with the pinned Bun.
import {mkdtemp, rm, mkdir, rename, readdir} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {Database} from "bun:sqlite";
const results: Record<string, unknown> = {version:Bun.version,revision:Bun.revision};
async function check(name:string,fn:()=>unknown){
  try { results[name]={status:"observed",value:await fn()}; }
  catch(e) { results[name]={status:"error",name:e.name,message:e.message}; }
}
const directory=await mkdtemp(join(tmpdir(),"can-bun-asap-"));
try {
await check("availability",()=>Object.fromEntries(["SQL","password","CSRF","Cookie","CookieMap","S3Client","TOML","YAML","JSON5","JSONL","markdown"].map(k=>[k,typeof Bun[k]])));
await check("files",async()=>{await mkdir(join(directory,"nested"));await Bun.write(join(directory,"nested/a.txt"),"hello");await rename(join(directory,"nested/a.txt"),join(directory,"nested/b.txt"));return {text:await Bun.file(join(directory,"nested/b.txt")).text(),glob:await Array.fromAsync(new Bun.Glob("**/*.txt").scan({cwd:directory})),entries:await readdir(join(directory,"nested"))};});
await check("sqlite_sql",async()=>{const sql=new Bun.SQL({adapter:"sqlite",filename:":memory:",bigint:true});try{await sql`CREATE TABLE t (id INTEGER, value TEXT)`;await sql`INSERT INTO t VALUES (${9007199254740993n}, ${"x' OR 1=1 --"})`;return await sql`SELECT id,value FROM t`;}finally{await sql.close();}});
await check("sqlite_direct",()=>{const db=new Database(":memory:",{safeIntegers:true});try{return db.query("SELECT ? AS n").get(9007199254740993n);}finally{db.close();}});
await check("process",async()=>{const p=Bun.spawn([process.execPath,"-e","process.stdout.write(process.argv[1]);process.stderr.write('err');process.exitCode=7","$(echo unintended)"],{stdout:"pipe",stderr:"pipe",env:{}});const [out,err,exit]=await Promise.all([new Response(p.stdout).text(),new Response(p.stderr).text(),p.exited]);return {out,err,exit};});
await check("stream",async()=>{let cancelled=false;const stream=new ReadableStream({start(c){c.enqueue(new Uint8Array([1,2]));},cancel(){cancelled=true;}});const reader=stream.getReader();const first=await reader.read();await reader.cancel();reader.releaseLock();return {first:Array.from(first.value),cancelled,locked:stream.locked};});
await check("stream_pull",async()=>{let pulls=0;const stream=new ReadableStream({pull(c){pulls++;if(pulls<=3)c.enqueue(new Uint8Array([pulls]));else c.close();}});const before=pulls;const reader=stream.getReader();const a=await reader.read();const b=await reader.read();reader.releaseLock();return {pullsBeforeReader:before,pullsAfterTwoReads:pulls,first:Array.from(a.value),second:Array.from(b.value),firstDone:a.done,lockedAfterRelease:stream.locked};});
await check("stream_filesink",async()=>{const path=join(directory,"sink.bin");const sink=Bun.file(path).writer({highWaterMark:16});const accepted=sink.write(new Uint8Array([1,2,3,4]));await sink.flush();await sink.end();let afterEnd="none";try{sink.write(new Uint8Array([9]));}catch(e){afterEnd=e.name+":"+e.message;}return {accepted,bytes:Array.from(new Uint8Array(await Bun.file(path).arrayBuffer())),afterEnd};});
await check("stream_alias",async()=>{const stream=new ReadableStream({start(c){c.enqueue(new Uint8Array([65,66]));c.enqueue(new Uint8Array([67]));c.close();}});const reader=stream.getReader();const a=await reader.read(),b=await reader.read(),c=await reader.read();reader.releaseLock();const copy=a.value.slice();a.value[0]=90;const decoder=new TextDecoder();const euro=decoder.decode(new Uint8Array([0xE2,0x82]),{stream:true})+decoder.decode(new Uint8Array([0xAC]),{stream:false});return {distinct:a.value!==b.value,second:Array.from(b.value),endDone:c.done,copyStable:Array.from(copy),mutated:Array.from(a.value),splitUtf8:euro};});
await check("stream_abort",async()=>{let pulls=0;const stream=new ReadableStream({pull(c){pulls++;if(pulls>2)c.close();}});const reader=stream.getReader();const pending=reader.read();await reader.cancel();const settled=await pending;reader.releaseLock();const again=stream.getReader();const late=await again.read();again.releaseLock();return {settledDone:settled.done,settledValue:settled.value===undefined?"undefined":"present",lateDone:late.done,locked:stream.locked};});
await check("stream_process_reader",async()=>{const p=Bun.spawn([process.execPath,"-e","process.stdout.write('ab');process.stdout.write('cd')"],{stdout:"pipe",stderr:"pipe",env:{}});const reader=p.stdout.getReader();const chunks=[];for(;;){const next=await reader.read();if(next.done)break;chunks.push(Array.from(next.value));}reader.releaseLock();const exit=await p.exited;return {chunks,exit};});
await check("password",async()=>{const hash=await Bun.password.hash("probe-password",{algorithm:"argon2id",memoryCost:4096,timeCost:2});return {valid:await Bun.password.verify("probe-password",hash),wrong:await Bun.password.verify("wrong",hash)};});
await check("webcrypto",async()=>{const key=await crypto.subtle.generateKey({name:"AES-GCM",length:256},false,["encrypt","decrypt"]);const iv=crypto.getRandomValues(new Uint8Array(12));const plain=new TextEncoder().encode("probe");const cipher=await crypto.subtle.encrypt({name:"AES-GCM",iv},key,plain);return {roundtrip:new TextDecoder().decode(await crypto.subtle.decrypt({name:"AES-GCM",iv},key,cipher)),extractable:key.extractable};});
await check("cookie_csrf",()=>{const token=Bun.CSRF.generate("probe-only",{sessionId:"A"});return {cookie:new Bun.Cookie("session","abc",{httpOnly:true,secure:true,sameSite:"strict"}).toString(),valid:Bun.CSRF.verify(token,{secret:"probe-only",sessionId:"A"}),crossSession:Bun.CSRF.verify(token,{secret:"probe-only",sessionId:"B"})};});
for (const [name,parse,text] of [
  ["toml",Bun.TOML.parse,"n = 9007199254740993"],
  ["yaml",Bun.YAML.parse,"n: 9007199254740993"],
  ["json5",Bun.JSON5.parse,"{n:9007199254740993}"],
  ["jsonl",Bun.JSONL.parse,'{"n":9007199254740993}\n'],
] as const) await check("format_"+name,()=>parse(text));
await check("jsonl_partial",()=>{const chunk=Bun.JSONL.parseChunk('{"ok":1}\n{bad}\n');return {partial:Bun.JSONL.parse('{"ok":1}\n{bad}\n'),chunk:{...chunk,error:chunk.error?{name:chunk.error.name,message:chunk.error.message}:null}};});
await check("sqlite_safe_option",async()=>{const sql=new Bun.SQL({adapter:"sqlite",filename:":memory:",safeIntegers:true,bigint:true});try{return await sql`SELECT ${9007199254740993n} AS n`;}finally{await sql.close();}});
await check("markdown",()=>({html:Bun.markdown.html("# Hello\n\n<script>alert(1)</script>\n\n[x](javascript:alert(1))"),disabled:Bun.markdown.html("<b>hello</b>",{noHtmlBlocks:true,noHtmlSpans:true}),render:typeof Bun.markdown.render}));
await check("url_text_time",()=>({url:new URL("../b?x=1&x=2","https://example.test/a/").href,query:new URLSearchParams("x=1&x=2").getAll("x"),utf8:Array.from(new TextEncoder().encode("€")),iso:new Date(0).toISOString()}));
await check("http_websocket",async()=>{const server=Bun.serve({hostname:"127.0.0.1",port:0,fetch(req,s){if(new URL(req.url).pathname==="/ws"){if(s.upgrade(req))return;return new Response("failed",{status:400});}return new Response(new ReadableStream({start(c){c.enqueue(new TextEncoder().encode("one"));c.enqueue(new TextEncoder().encode("two"));c.close();}}));},websocket:{message(ws,message){ws.send(message);}}});try{const body=await(await fetch(server.url)).text();const echo=await new Promise((resolve,reject)=>{const ws=new WebSocket(`ws://127.0.0.1:${server.port}/ws`);const timer=setTimeout(()=>{ws.close();reject(new Error("probe deadline"));},3000);ws.onopen=()=>ws.send("echo");ws.onmessage=e=>{clearTimeout(timer);ws.close();resolve(e.data);};ws.onerror=()=>{clearTimeout(timer);reject(new Error("websocket failure"));};});return {body,echo};}finally{await server.stop(true);}});
await check("ws_client",async()=>{const seen:Record<string,unknown>={};for(const [label,url,proto] of [["garbage","not a url"],["http-scheme","http://127.0.0.1:9/"],["bad-proto","ws://127.0.0.1:9/",["a,b"]],["empty-proto","ws://127.0.0.1:9/",[""]]] as const){try{const ws=proto===undefined?new WebSocket(url):new WebSocket(url,proto as unknown as string[]);seen[label]="constructed";ws.onerror=()=>{};ws.close();}catch(e){seen[label]=(e as Error).name;}}const server=Bun.serve({hostname:"127.0.0.1",port:0,fetch(req,s){if(s.upgrade(req,{data:{tag:"c"}}))return;return new Response("x",{status:400});},websocket:{open(ws){seen.openData=(ws.data as {tag:string}).tag;},message(ws,msg){if(typeof msg==="string")ws.send("t:"+msg);else ws.send(new Uint8Array([9,8]));},close(ws,code,reason){seen.serverHook={code,reason};}}});try{await new Promise<void>((res,rej)=>{const ws=new WebSocket(`ws://127.0.0.1:${server.port}/`);const timer=setTimeout(()=>rej(new Error("probe deadline")),3000);ws.onopen=()=>ws.send("hi");ws.onerror=()=>{clearTimeout(timer);rej(new Error("client error"));};ws.onmessage=(e:MessageEvent)=>{if(typeof e.data==="string"){seen.textEcho={type:typeof e.data,value:e.data};ws.send(new Uint8Array([1,2,3]));}else{seen.binaryEcho={ctor:e.data?.constructor?.name,bytes:Array.from(new Uint8Array(e.data))};ws.close(1000,"bye");}};ws.onclose=(e:CloseEvent)=>{seen.clientHook={code:e.code,reason:e.reason,wasClean:e.wasClean};clearTimeout(timer);setTimeout(res,200);};});}finally{await server.stop(true);}return seen;});
await check("ws_upgrade",async()=>{const seen:Record<string,unknown>={};const server=Bun.serve({hostname:"127.0.0.1",port:0,fetch:async(req,s)=>{const path=new URL(req.url).pathname;if(path==="/defer"){await new Promise(r=>setTimeout(r,20));if(s.upgrade(req))return undefined as unknown as Response;return new Response("deferred-failed",{status:500});}if(path==="/plain")return new Response("upgraded="+s.upgrade(req));if(path==="/sel"){seen.offered=req.headers.get("sec-websocket-protocol");if(s.upgrade(req,{headers:{"Sec-WebSocket-Protocol":"proto-b"}}))return undefined as unknown as Response;return new Response("x",{status:400});}if(s.upgrade(req))return undefined as unknown as Response;return new Response("x",{status:400});},websocket:{message(ws,msg){ws.send(msg);}}});try{seen.plain=await(await fetch(`http://127.0.0.1:${server.port}/plain`)).text();const run=(path:string,protocols?:string[])=>new Promise<{data:unknown,protocol:string}>((res,rej)=>{const ws=protocols===undefined?new WebSocket(`ws://127.0.0.1:${server.port}${path}`):new WebSocket(`ws://127.0.0.1:${server.port}${path}`,protocols);const timer=setTimeout(()=>rej(new Error("probe deadline")),3000);ws.onopen=()=>ws.send("D");ws.onmessage=(e:MessageEvent)=>{clearTimeout(timer);const out={data:e.data,protocol:ws.protocol};ws.close();res(out);};ws.onerror=()=>{clearTimeout(timer);rej(new Error("client error"));};});seen.deferred=await run("/defer");seen.selected=await run("/sel",["proto-a","proto-b"]);seen.unselected=await run("/auto",["proto-a","proto-b"]);}finally{await server.stop(true);}return seen;});
await check("ws_send_close",async()=>{const seen:Record<string,unknown>={};const attempt=(label:string,fn:()=>unknown)=>{try{seen[label]={ok:fn()};}catch(e){seen[label]={throws:(e as Error).name};}};const server=Bun.serve({hostname:"127.0.0.1",port:0,fetch(req,s){if(s.upgrade(req))return;return new Response("x",{status:400});},websocket:{open(ws){attempt("sendText",()=>ws.send("hello"));attempt("sendBytes",()=>ws.send(new Uint8Array([1])));attempt("close1000",()=>ws.close(1000,"bye-ok"));attempt("sendAfterClose",()=>ws.send("late"));attempt("closeBadCode",()=>ws.close(999,"bad"));attempt("closeLongReason",()=>ws.close(1000,"r".repeat(200)));}}});try{const early=new WebSocket(`ws://127.0.0.1:${server.port}/`);attempt("clientSendBeforeOpen",()=>early.send("x"));attempt("clientCloseBeforeOpen",()=>early.close(1000,"early"));await new Promise<void>(res=>{early.onclose=()=>res();setTimeout(res,3000);});const ws=new WebSocket(`ws://127.0.0.1:${server.port}/`);await new Promise<void>((res,rej)=>{const timer=setTimeout(()=>rej(new Error("probe deadline")),3000);ws.onopen=()=>{clearTimeout(timer);res();};ws.onerror=()=>rej(new Error("client error"));});attempt("clientCloseBadCode",()=>ws.close(999,"bad"));attempt("clientCloseLongReason",()=>ws.close(1000,"r".repeat(200)));ws.close(1000,"done");await new Promise<void>(res=>{ws.onclose=()=>res();setTimeout(res,3000);});}finally{await server.stop(true);}return seen;});
await check("ws_backpressure",async()=>{const seen:Record<string,unknown>={saturated:0,drains:0};const server=Bun.serve({hostname:"127.0.0.1",port:0,fetch(req,s){if(s.upgrade(req))return;return new Response("x",{status:400});},websocket:{open(ws){const chunk=new Uint8Array(65536);for(let i=0;i<50;i++)if(ws.send(chunk)===-1)seen.saturated=(seen.saturated as number)+1;},drain(){seen.drains=(seen.drains as number)+1;},message(){},close(){}}});try{await new Promise<void>((res,rej)=>{const ws=new WebSocket(`ws://127.0.0.1:${server.port}/`);let bytes=0;const timer=setTimeout(()=>rej(new Error("probe deadline")),8000);ws.onmessage=(e:MessageEvent)=>{bytes+=e.data.byteLength;if(bytes>=50*65536){clearTimeout(timer);seen.bytes=bytes;ws.close();res();}};ws.onerror=()=>rej(new Error("client error"));});await new Promise(r=>setTimeout(r,100));}finally{await server.stop(true);}return seen;});
await check("ws_close_provenance",async()=>{const seen:Record<string,unknown>={};const server=Bun.serve({hostname:"127.0.0.1",port:0,fetch(req,s){const t=new URL(req.url).pathname.slice(1);if(s.upgrade(req,{data:{t}}))return;return new Response("x",{status:400});},websocket:{message(ws,msg){if((ws.data as {t:string}).t==="sclose")ws.close(1001,"server-bye");else ws.send(msg);},close(ws,code,reason){seen[(ws.data as {t:string}).t+"-serverHook"]={code,reason};}}});try{const run=(t:string,act:(ws:WebSocket)=>void)=>new Promise<void>((res,rej)=>{const ws=new WebSocket(`ws://127.0.0.1:${server.port}/${t}`);const timer=setTimeout(()=>rej(new Error("probe deadline")),3000);ws.onopen=()=>act(ws);ws.onerror=()=>{clearTimeout(timer);rej(new Error("client error"));};ws.onclose=(e:CloseEvent)=>{seen[t+"-clientHook"]={code:e.code,reason:e.reason,wasClean:e.wasClean};clearTimeout(timer);setTimeout(res,250);};});await run("cclose",ws=>ws.close(1000,"client-bye"));await run("sclose",ws=>ws.send("trigger"));const net=await import("node:net");await new Promise<void>((res,rej)=>{const timer=setTimeout(()=>rej(new Error("probe deadline")),3000);const sock=net.connect(server.port,"127.0.0.1",()=>{sock.write("GET /abrupt HTTP/1.1\r\nHost: x\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==\r\nSec-WebSocket-Version: 13\r\n\r\n");});let got=false;sock.on("data",()=>{if(!got){got=true;seen["abrupt-upgraded"]=true;sock.destroy();clearTimeout(timer);setTimeout(res,250);}});sock.on("error",rej);});}finally{await server.stop(true);}return seen;});
await check("ws_tls_client",async()=>{const seen:Record<string,unknown>={};const cert=join(directory,"ws-cert.pem"),key=join(directory,"ws-key.pem");const made=Bun.spawnSync(["openssl","req","-x509","-newkey","rsa:2048","-keyout",key,"-out",cert,"-days","1","-nodes","-subj","/CN=127.0.0.1"]);if(made.exitCode!==0)return {openssl:"unavailable"};const server=Bun.serve({hostname:"127.0.0.1",port:0,tls:{cert:Bun.file(cert),key:Bun.file(key)},fetch(req,s){seen.offered=req.headers.get("sec-websocket-protocol");if(s.upgrade(req))return;return new Response("x",{status:400});},websocket:{message(ws,msg){ws.send(msg);}}});try{const attempt=(label:string,fn:()=>WebSocket)=>new Promise<void>(resolve=>{let ws:WebSocket;try{ws=fn();}catch(e){seen[label]={throws:(e as Error).name};resolve();return;}const timer=setTimeout(()=>{seen[label]={hang:true};try{ws.close();}catch{}resolve();},3000);ws.onopen=()=>{clearTimeout(timer);seen[label]={open:true};ws.close();resolve();};ws.onerror=()=>{clearTimeout(timer);seen[label]={error:true};resolve();};});await attempt("verify-default",()=>new WebSocket(`wss://127.0.0.1:${server.port}/`));await attempt("insecure-bypass",()=>new WebSocket(`wss://127.0.0.1:${server.port}/`,{tls:{rejectUnauthorized:false}} as unknown as string[]));seen.offeredAfterBypass=seen.offered;await attempt("bypass-with-protocols",()=>new WebSocket(`wss://127.0.0.1:${server.port}/`,{protocols:["proto-a"],tls:{rejectUnauthorized:false}} as unknown as string[]));}finally{await server.stop(true);}return seen;});
await check("cookie_parse",()=>{const seen:Record<string,unknown>={};const snap=(label:string,header:string)=>{const map=new Bun.CookieMap(header);seen[label]={size:map.size,json:map.toJSON(),entries:Array.from(map as unknown as Iterable<[string,unknown]>).map(([k,v])=>[k,v&&typeof v==="object"?(v as {value?:unknown}).value??"[object]":v])};};snap("simple","a=1; b=2");snap("duplicates","a=1; a=2");snap("case","A=1; a=2");snap("no-equals","a=1; bare; b=2");snap("empty-value","a=; b=2");snap("empty-name","=x; b=2");snap("empty","");snap("spaces","  a  =  1 ;b=2 ");snap("quoted",'a="quoted;still"; b=2');snap("percent","a=%20%3B");snap("unicode","a=€");snap("semis","a=1;;b=2;");snap("eq-value","a=b=c");const miss=new Bun.CookieMap("a=1");seen.missing={get:miss.get("zzz"),has:miss.has("zzz")};seen.dupGet=new Bun.CookieMap("a=1; a=2").get("a");return seen;});
await check("cookie_serialize",()=>{const seen:Record<string,unknown>={};const attempt=(label:string,fn:()=>unknown)=>{try{seen[label]={ok:fn()};}catch(e){seen[label]={throws:(e as Error).name+":"+(e as Error).message};}};attempt("basic",()=>new Bun.Cookie("a","1").toString());attempt("full",()=>new Bun.Cookie("s","v",{domain:"example.com",path:"/admin",httpOnly:true,secure:true,sameSite:"strict",maxAge:3600}).toString());attempt("expires",()=>new Bun.Cookie("e","v",{expires:new Date("2030-01-01T00:00:00.000Z")}).toString());attempt("samesite-lax",()=>new Bun.Cookie("a","1",{sameSite:"lax"}).toString());attempt("samesite-none",()=>new Bun.Cookie("a","1",{sameSite:"none",secure:true}).toString());attempt("samesite-none-insecure",()=>new Bun.Cookie("a","1",{sameSite:"none"}).toString());attempt("samesite-bogus",()=>new Bun.Cookie("a","1",{sameSite:"bogus" as "lax"}).toString());attempt("samesite-omitted",()=>new Bun.Cookie("a","1",{}).toString());attempt("partitioned",()=>new Bun.Cookie("a","1",{partitioned:true}).toString());attempt("maxage-zero",()=>new Bun.Cookie("a","1",{maxAge:0}).toString());attempt("maxage-negative",()=>new Bun.Cookie("a","1",{maxAge:-5}).toString());attempt("both-expiry",()=>new Bun.Cookie("e","v",{expires:new Date("2030-01-01T00:00:00.000Z"),maxAge:60}).toString());attempt("crlf-name",()=>new Bun.Cookie("a\r\nX","1").toString());attempt("crlf-value",()=>new Bun.Cookie("a","1\r\nX: y").toString());attempt("empty-name",()=>new Bun.Cookie("","1").toString());attempt("semi-name",()=>new Bun.Cookie("a;b","1").toString());attempt("space-name",()=>new Bun.Cookie("a b","1").toString());attempt("eq-name",()=>new Bun.Cookie("a=b","1").toString());attempt("comma-name",()=>new Bun.Cookie("a,b","1").toString());attempt("semi-value",()=>new Bun.Cookie("a","1;2").toString());attempt("unicode-value",()=>new Bun.Cookie("a","€").toString());attempt("host-prefix-open",()=>new Bun.Cookie("__Host-s","v",{}).toString());attempt("host-prefix-locked",()=>new Bun.Cookie("__Host-s","v",{secure:true,path:"/"}).toString());attempt("secure-prefix-open",()=>new Bun.Cookie("__Secure-s","v",{}).toString());attempt("secure-prefix-locked",()=>new Bun.Cookie("__Secure-s","v",{secure:true}).toString());attempt("host-prefix-domain",()=>new Bun.Cookie("__Host-s","v",{secure:true,path:"/",domain:"example.com"}).toString());seen.isExpired={zero:new Bun.Cookie("x","y",{maxAge:0}).isExpired(),session:new Bun.Cookie("x","y").isExpired(),past:new Bun.Cookie("x","y",{expires:new Date("2000-01-01T00:00:00.000Z")}).isExpired()};return seen;});
await check("cookie_headers",()=>{const seen:Record<string,unknown>={};const map=new Bun.CookieMap("a=1");map.set("b","2",{path:"/"});map.set("c","3",{path:"/",httpOnly:true});seen.setHeaders=map.toSetCookieHeaders();map.delete("a");seen.afterDelete=map.toSetCookieHeaders();map.delete({name:"b",domain:"example.com",path:"/admin"});seen.afterDeleteScoped=map.toSetCookieHeaders();const headers=new Headers();for(const field of map.toSetCookieHeaders())headers.append("set-cookie",field);seen.getSetCookie=typeof (headers as unknown as {getSetCookie?:unknown}).getSetCookie==="function"?(headers as unknown as {getSetCookie:()=>string[]}).getSetCookie():"missing";seen.combined=headers.get("set-cookie");return seen;});
await check("csrf_token",()=>{const seen:Record<string,unknown>={};const attempt=(label:string,fn:()=>unknown)=>{try{seen[label]={ok:fn()};}catch(e){seen[label]={throws:(e as Error).name+":"+(e as Error).message};}};const shape=(t:unknown)=>({type:typeof t,length:typeof t==="string"?t.length:-1,charset:typeof t==="string"?/^[A-Za-z0-9_.-]+$/.test(t):false});const a=Bun.CSRF.generate("s3cret",{sessionId:"A"});const b=Bun.CSRF.generate("s3cret",{sessionId:"A"});seen.shape=shape(a);seen.distinct=a!==b;seen.valid=Bun.CSRF.verify(a,{secret:"s3cret",sessionId:"A"});seen.crossSession=Bun.CSRF.verify(a,{secret:"s3cret",sessionId:"B"});seen.wrongSecret=Bun.CSRF.verify(a,{secret:"other",sessionId:"A"});seen.garbage=Bun.CSRF.verify("not-a-token",{secret:"s3cret",sessionId:"A"});seen.truncated=Bun.CSRF.verify(String(a).slice(0,8),{secret:"s3cret",sessionId:"A"});seen.flipped=Bun.CSRF.verify(String(a).slice(0,-2)+(String(a).endsWith("AA")?"BB":"AA"),{secret:"s3cret",sessionId:"A"});const nosession=Bun.CSRF.generate("s3cret",{});seen.noSessionVerify=Bun.CSRF.verify(nosession,{secret:"s3cret"});seen.noSessionWithSession=Bun.CSRF.verify(nosession,{secret:"s3cret",sessionId:"A"});seen.sessionWithoutSession=Bun.CSRF.verify(a,{secret:"s3cret"});attempt("empty-session-generate",()=>shape(Bun.CSRF.generate("s3cret",{sessionId:""})));attempt("empty-secret",()=>{const t=Bun.CSRF.generate("",{sessionId:"A"});return {length:typeof t==="string"?t.length:-1,verified:Bun.CSRF.verify(t,{secret:"",sessionId:"A"})};});attempt("nonstring-token",()=>Bun.CSRF.verify(123 as unknown as string,{secret:"s3cret",sessionId:"A"}));attempt("missing-options",()=>Bun.CSRF.verify(a));attempt("default-secret",()=>{const t=Bun.CSRF.generate();return {length:typeof t==="string"?t.length:-1,verified:Bun.CSRF.verify(t)};});attempt("encode-mismatch",()=>{const t=Bun.CSRF.generate("s3cret",{sessionId:"A",encoding:"base64"});return {verifyDefault:Bun.CSRF.verify(t,{secret:"s3cret",sessionId:"A"}),verifyB64:Bun.CSRF.verify(t,{secret:"s3cret",sessionId:"A",encoding:"base64"})};});return seen;});
await check("csrf_expiry",async()=>{const seen:Record<string,unknown>={};const attempt=(label:string,fn:()=>unknown)=>{try{seen[label]={ok:fn()};}catch(e){seen[label]={throws:(e as Error).name+":"+(e as Error).message};}};const fresh=Bun.CSRF.generate("s3cret",{sessionId:"A",expiresIn:60000});seen.fresh=Bun.CSRF.verify(fresh,{secret:"s3cret",sessionId:"A"});attempt("maxAgeZero",()=>Bun.CSRF.verify(fresh,{secret:"s3cret",sessionId:"A",maxAge:0}));attempt("maxAgeNegative",()=>Bun.CSRF.verify(fresh,{secret:"s3cret",sessionId:"A",maxAge:-1}));attempt("maxAgeHuge",()=>Bun.CSRF.verify(fresh,{secret:"s3cret",sessionId:"A",maxAge:9007199254740992}));const tiny=Bun.CSRF.generate("s3cret",{sessionId:"A",expiresIn:50});seen.tinyFresh=Bun.CSRF.verify(tiny,{secret:"s3cret",sessionId:"A"});await new Promise(r=>setTimeout(r,250));seen.tinyStale=Bun.CSRF.verify(tiny,{secret:"s3cret",sessionId:"A"});seen.tinyMaxAge=Bun.CSRF.verify(tiny,{secret:"s3cret",sessionId:"A",maxAge:60000});attempt("expiresInZero",()=>{const zero=Bun.CSRF.generate("s3cret",{sessionId:"A",expiresIn:0});return Bun.CSRF.verify(zero,{secret:"s3cret",sessionId:"A"});});attempt("expiresInNegative",()=>{const neg=Bun.CSRF.generate("s3cret",{sessionId:"A",expiresIn:-5});return Bun.CSRF.verify(neg,{secret:"s3cret",sessionId:"A"});});return seen;});
} finally {await rm(directory,{recursive:true,force:true});}
console.log(JSON.stringify(results,(_,v)=>typeof v==="bigint"?{bigint:v.toString()}:v,2));
