"""Save fully reworded Jev selection requests; --send submits saved JSON bytes."""
import itertools
import json
import os
from pathlib import Path
import sys
import urllib.request

OUT = Path(__file__).resolve().parent
state = {
    "objective": [
        "Can must remove copied upstream SQLite grammar/runtime from its tracked source tree and use pinned normal external Go modules in the shared cache. Replacing copied C with copied Go, archives, submodules or another vendor tree is forbidden. Native Bun.SQL execution and the intended checked-raw-SQL contract stay. No external consumers need compatibility. Codex decides and reviews; Muse executes the complete saved checklist. No benchmarks or broad builds are authorized on the 256GB laptop.",
        "The requested implementation externalizes SQLite parser source ownership through ordinary versioned Go dependencies cached globally. Can may not hide the payload in generated Go, a ZIP, submodule or new vendoring location. Preserve native Bun.SQL plus the intended offline descriptor guarantees, without preserving accidental old behavior for nonexistent users. Muse performs the ordered implementation under Codex review. Storage is constrained to a 256GB machine; broad builds and performance experiments remain deferred.",
        "Choose a production dependency for a compiler migration whose endpoint is no third-party SQLite parser source checked into Can. Only standard pinned Go modules using the common module cache meet the requested boundary; copied code in any language and repository-stored archives/checkouts do not. Keep raw-SQL checking and execution through Bun.SQL. There are zero external users and no compatibility obligation. The established workflow uses Muse implementation and independent Codex verification, with neither large builds nor measurements allowed on the 256GB laptop.",
    ],
    "contract": [
        "The compiler owns Analysis: statement count/kind and source byte spans, every bind occurrence/index in source order, top-level SELECT LIMIT shape, RETURNING and positioned syntax failures. Descriptor checks enforce one admitted statement, parameter coverage/name matching, exclusive trailing LIMIT binding, non-returning DML execute and INSERT RETURNING under one. Exact segments drive native tags; runtime validates returned records. Schema proof and limits on all database work are not promised. Parser identity must distinguish a pinned release/content from Tree-sitter ABI alone. PostgreSQL still requires cgo; distribution preserves CGO_ENABLED=1 and GOPROXY=off after prefetch.",
        "The required interface reports byte-accurate statement ranges and kinds, counts, all parameter sites and assigned numbers in lexical order, outer SELECT limit structure, mutation RETURNING and located parse failures. Can independently restricts statement admission, declared coverage and named suffixes, one exclusive final LIMIT parameter, execute DML without RETURNING, and the INSERT RETURNING/one case. Those sites become Bun tag segments and row data is checked at runtime. This provides neither database-schema verification nor a bound on every engine operation. Record the actual parser pin, not merely its ABI. PostgreSQL retains CGo, and offline assembly still uses GOPROXY=off with CGO_ENABLED=1 after dependency provisioning.",
        "Both candidates must feed the existing compiler Analysis boundary with exact UTF-8 byte extents, complete source-ordered bind locations/numbers, statement type/count, outermost LIMIT shape, RETURNING flags and diagnostic positions. Higher layers retain single-statement rules, declared-name/coverage checks, the unique trailing limit slot, ordinary mutation execute, and one-row INSERT RETURNING admission. Native templates and runtime row decoding consume that analysis. No schema correctness or universal query-work bound is established. Metadata should identify parser content/release rather than confuse Tree-sitter language ABI with identity. Keep PostgreSQL CGo and pre-provisioned offline distribution settings CGO_ENABLED=1/GOPROXY=off.",
    ],
    "official": [
        "The exact existing grammar resolves as github.com/defin/tree-sitter-sqlite3 v0.1.1-0.20260503135658-7f69bb66845b; parser/scanner/header hashes match local copies. Paired with official github.com/tree-sitter/go-tree-sitter v0.25.0, actual SetLanguage and parsing succeed at ABI15. The runtime proxy pin resolves with verified sums at adc13ffd8b2c0b01b878fda9f7c422ce0df5fad3 although its live GitHub tag is absent. Archive sources are complete. An adapter matched the current backend across 74 cases. It needs exact-once parser/tree/cursor Close, missing-node handling, explicit rejection of ordinary malformed-literal nodes, and bounded iterative traversal. Plain Parse avoids a suspected options-pointer lifetime gap. C and cgo remain only in external modules.",
        "A working external baseline imports github.com/defin/tree-sitter-sqlite3 v0.1.1-0.20260503135658-7f69bb66845b and github.com/tree-sitter/go-tree-sitter v0.25.0. The grammar's three key source hashes are identical to Can's vendored bytes; ABI15 installation and real parse checks passed, as did 74-case comparison to the existing implementation. Required C sources ship in the module archives. The runtime is checksum-verified from the proxy at adc13ffd8b2c0b01b878fda9f7c422ce0df5fad3 despite a missing current GitHub tag. Can would keep a small bridge with once-only Close ownership, missing/error and malformed-literal recognition and capped iterative walking. Avoid the options callback path with a suspected retained pointer; ordinary Parse does not allocate it. Native compilation moves outside the repository.",
        "The official-binding option has been built and exercised: github.com/defin/tree-sitter-sqlite3 v0.1.1-0.20260503135658-7f69bb66845b plus github.com/tree-sitter/go-tree-sitter v0.25.0 admits ABI15 and reproduces the old analysis for 74 inputs. Its parser, scanner and header are byte-identical to the current pinned grammar, and module archives contain the compile inputs. Runtime commit adc13ffd8b2c0b01b878fda9f7c422ce0df5fad3 resolves through proxy and sums even though GitHub no longer exposes that release tag. Integration must close each parser/tree/cursor once, detect missing nodes and special malformed-literal nodes, and cap an iterative walk. The simple Parse entry avoids a suspected options callback pointer-retention issue. External packages continue to compile C via CGo.",
    ],
    "meyer": [
        "github.com/sqlc-dev/meyer v0.1.2 resolves normally with verified sums at commit 59b2dbf9b1872316bc6c6d3379b500df84db3e01. It is independently authored Go, MIT, Go1.24 and has zero module dependencies. sqlc main imports it, but the inspected sqlc release does not; maintenance history is short. The 74-case probe returns the needed AST/spans, including UTF-8, CTEs, nested limits, DML and binds inside RETURNING. Differences include full-sigil name identities, digit/Tcl names, optional mutation LIMIT, diagnostic wording/positions and semicolon-inclusive statement spans. LIMIT-comma AST children reorder operands, so sites must be sorted by byte position. Its existing BindParam.Number already implements SQLite numbering and should be reused.",
        "Meyer v0.1.2 from github.com/sqlc-dev/meyer is a normal checksum-pinned module at 59b2dbf9b1872316bc6c6d3379b500df84db3e01, licensed MIT and written in Go with Go1.24 minimum and no dependencies. Adoption is visible in sqlc's main branch rather than the checked released version, leaving a young-project risk. Running the same 74 SQL inputs exposed suitable byte locations and typed structures for UTF-8, common-table expressions, nested LIMIT, mutations and RETURNING parameters. Changed outputs concern sigil-distinct numbering, numeric/Tcl names, option-controlled DML limits, errors and statement terminators. Sort parameter nodes by source offsets because comma-LIMIT traversal swaps their order; consume the already-assigned upstream numbers instead of implementing another numbering algorithm.",
        "The second candidate, github.com/sqlc-dev/meyer v0.1.2, was resolved and sum-verified at 59b2dbf9b1872316bc6c6d3379b500df84db3e01. This independent MIT parser uses only Go, requires Go1.24 and lists no module dependencies. sqlc has integrated it on main but not in the release inspected here; it remains a recent dependency. A 74-input qualification supplies all needed syntax structures and byte ranges through Unicode text, CTE/subquery limits, mutations and RETURNING expressions. Divergences cover named-sigil identity, digit/Tcl parameters, optional UPDATE/DELETE LIMIT, failure presentation and inclusion of trailing semicolons in spans. Its comma LIMIT visits count before offset, requiring sorting by source position. BindParam.Number gives native numbering directly, avoiding Can-owned reimplementation.",
    ],
    "guards_and_limits": [
        "Meyer has a fixed parser recursion guard of 10000: bounded probes parsed a 40035-byte expression chain and 5000 nested parentheses, while 15000 nesting failed cleanly. A 100000-term chain also parsed; these were correctness checks, not timing/footprint measurements. Parse(ctx,Reader) ignores context and reads without limit; choose ParseString behind a 1MiB input ceiling. Lexer NUL stops parsing, so reject NUL before the call. ast.Walk is separately recursive and unsafe for arbitrarily deep flat-expression trees; use iterative Node.Children traversal capped at one million nodes and sort/validate bind spans. No hard heap/time bound is claimed. Tree-sitter also passed bounded chains/nesting but native allocation failure can abort. Full upstream corpora, all target platforms and staged bundles were not reproduced.",
        "Resource evidence favors explicit adapter limits under either implementation. Meyer caps parser recursion at 10000; 40035 bytes of chained expression and depth5000 passed, depth15000 produced a clean recursion error, and a 100000-term chain parsed. None of these probes measured speed or memory. Its reader entry disregards context and reads everything, so use ParseString only after a 1MiB length check and refuse NUL, which otherwise acts as EOF. Replace recursive ast.Walk with an iterative Children walk limited to one million visits, then sort and validate sites. These limits do not certify bounded heap or elapsed time. Official Tree-sitter handled the bounded examples too, with abort possible on native OOM. Upstream full suites, platform matrices and distribution execution remain unrun.",
        "Guard the adapter rather than claim either library is resource-isolated. Meyer's built-in depth ceiling is 10000; correctness probes accepted 40035-byte expression chains, parentheses nested5000 and a chain of100000 terms, rejecting nesting15000 normally. There are no performance or allocation measurements. ParseString permits a pre-parse 1MiB byte cap, unlike the context-ignoring unbounded reader API. Refuse embedded NUL because its lexer stops there. An iterative Children traversal with a million-node budget avoids recursive ast.Walk depth growth; ordered, checked byte spans follow. This is not a hard memory/time guarantee. Comparable small Tree-sitter probes passed, though C allocation exhaustion aborts. No full upstream corpus, multi-platform qualification or staged bundle test has been executed.",
    ],
    "verified_policy": [
        "Independent Bun1.4.2 in-memory SQLite checks bind :a/@a/$a to separate values and accept $1 as a named parameter. Malformed X'01001' and 123abc are rejected. #name prepares in SQLite but lies outside Can's documented placeholder family. The old code/documentation described sigil collapsing and digit-name rejection as engine behavior incorrectly; there is no independently motivated Can compatibility requirement for these mistakes. Keep declared suffix-to-field checking, which can reject digit/Tcl application names even when parsing accepts them; limit names remain unrestricted. Do not rewrite native statement spans merely to mimic old punctuation boundaries. Grammar differences must be reconciled against engine observations and intended admission, not only old goldens.",
        "A separate correctness check on Bun1.4.2's in-memory SQLite returned distinct values for :a, @a and $a, and recognized the named spelling $1. It refused X'01001' and 123abc; #name prepared, although Can's listed parameter forms omit it. Historical comments incorrectly claimed SQLite collapses sigils and rejects numeric names. No product rationale found requires those behaviors. Retain Can's exact suffix-versus-declared-field rule, including its possible rejection of parsed numeric/Tcl application names and free limit-name choice. Preserve accurate native spans instead of stripping terminators just for historical output. Judge acceptance changes from engine evidence and Can policy, not automatic golden-file preservation.",
        "Bun1.4.2 SQLite was exercised independently in memory: :a/@a/$a carried three different supplied values; $1 worked as a name; X'01001' and 123abc failed. Preparation of #name succeeded, yet that sigil is outside Can's stated source family. The prior engine-equivalence explanation for name-sigil collapse and digit-name failure is false, and no separate compatibility reason justifies retaining it. Named sites must still match declared Can field suffixes (numeric or Tcl application names may fail that check), while limit names have no declaration. Avoid copying old semicolon exclusion into an otherwise precise upstream span API. Intended rules and executed SQLite results resolve disagreements, not the existence of older expected outputs.",
    ],
    "engine_arbitration": [
        "Muse's schema-backed in-memory Bun1.4.2/SQLite3.54.0 checks now confirm acceptance of numeric and Tcl names and separate sigils. UPDATE..LIMIT and DELETE..ORDER BY..LIMIT also execute, so Meyer must use Options{UpdateDeleteLimit:true}. Both parsers accept ?0 and overflowing numbered binds, but existing Can CheckSites rejects their zero/invalid indexes; keep that guard. Both accept LIMIT before a later UNION, rejected by the engine: add a narrow structural check for misplaced LIMIT/ORDER BY on nonfinal compound cores rather than recreate preparation. Engine accepts depth2000 and rejects5000 while both parsers accept5000; do not imitate a build-dependent preparation resource ceiling with a new handwritten scanner. Retain the stated compiler input/traversal guards and disclose that parser acceptance does not guarantee engine preparation. No new owned repository is needed on current evidence.",
        "The completed Bun1.4.2 SQLite3.54.0 oracle created the referenced tables and established numeric/Tcl-name acceptance plus sigil-distinct values. Mutation LIMIT forms work in that build, requiring Options{UpdateDeleteLimit:true} on Meyer. Invalid ?0/overflow nodes emerge from either parser and are already rejected by Can's index-range validation, which stays. Each backend also permits a LIMIT preceding UNION although SQLite refuses it; inspect nonfinal compound cores to reject misplaced LIMIT/ORDER BY without implementing an engine. Depth2000 succeeds natively and5000 fails despite both parsers accepting it; use compiler byte/node bounds and honest preparation limits instead of a handwritten nesting scanner tied to host-engine resource settings. Existing modules suffice, so publishing another parser project has no established justification.",
        "Final oracle evidence from Bun1.4.2 with SQLite3.54.0 and real in-memory tables verifies named numeric/Tcl parameters and distinct sigils, as well as executable UPDATE/DELETE LIMIT. Set Meyer's Options{UpdateDeleteLimit:true} accordingly. Can's existing CheckSites closes the shared parser acceptance of zero/overflow parameter numbers; preserving that validation avoids duplicate binding logic. A LIMIT on an earlier compound core is accepted by both parsers but rejected by SQLite, so apply a small structural nonfinal-core LIMIT/ORDER BY rejection rather than reproduce native preparation. The engine's nesting2000 pass/5000 failure differs from both parsers; compiler byte/node budgets should stand independently without a bespoke depth lexer or a promise that every parsed statement prepares. There is no evidenced reason to create a Can-owned external parser repository.",
    ],
}
instructions = [
    "Which production SQLite parser should Can integrate now, given the qualified options and the stated small adapter guards? Choose for this no-vendoring migration without weakening intended checks or claiming unmeasured speed benefits. Your answer is advisory; independently reviewed implementation and tests remain required.",
    "Select the dependency approach best supported for completing this source-externalization change with the specified contract and bounded adapters. Do not assume timing improvements or let historical implementation accidents dictate semantics. This judgment informs Codex and cannot replace review or execution tests.",
    "Recommend the parser choice to ship for the authorized migration based only on these supplied qualifications, guard requirements and maintenance uncertainties. Retain intended SQL validation, exclude presumed performance gains, and treat the selection as advice subject to independent code verification.",
]
options = {
    "meyer": [
        "Integrate pinned Meyer v0.1.2 with pre-parse byte/NUL guards, iterative bounded traversal, sorted byte spans and its native bind numbering; update release metadata and deliberate policy differences. Remove all local SQLite parser C and the obsolete bridge.",
        "Use the qualified Meyer release as the external Go dependency, keeping a compact adapter for input limits/NUL rejection, capped iterative visiting, source-order sites and coherent identity/policy updates. Delete the vendored grammar/runtime and C glue.",
        "Choose v0.1.2 of Meyer, consuming its numbered AST with length/NUL validation and a limited nonrecursive sorted occurrence walk. Revise metadata and justified admission expectations while eliminating copied SQLite C and custom serialization.",
    ],
    "official": [
        "Integrate the verified defin grammar and official v0.25.0 runtime modules, with exact-once native ownership, bounded traversal, failure-node corrections and deliberate parameter/policy updates. Remove repository-owned upstream C but retain external native compilation.",
        "Adopt the reproducible official module pair for the existing grammar, implement one-time Close discipline and capped walks, and correct special failures/numbering as required. Externalize all third-party source while keeping CGo in dependencies.",
        "Prefer the tested Tree-sitter Go binding/runtime pins, using a small lifecycle-aware bounded adapter and explicit syntax/parameter corrections. Delete the local upstream payload; its C implementation continues through the shared module cache.",
    ],
    "further_evidence": [
        "Neither candidate is sufficiently supported for integration yet; identify this as a need for additional bounded correctness evidence before selecting, without publishing a new parser repository or redesigning SQL.",
        "Defer production choice because the supplied qualifications leave a consequential unresolved gap; obtain a focused correctness result within the current module-migration scope first.",
        "Withhold selection pending another small verification that materially affects suitability; stay within existing external modules and the present SQL contract rather than expanding architecture.",
    ],
}

for key, values in state.items():
    assert len(values) == 3 and len(set(values)) == 3, key
for key, values in options.items():
    assert len(values) == 3 and len(set(values)) == 3, key
assert len(set(instructions)) == 3
requests = [
    {"model": "jev-latest", "state": {k: v[i] for k, v in state.items()},
     "questions": {"production_parser": {"type": "choice", "instructions": instructions[i],
        "criteria": {k: v[i] for k, v in options.items()}}}}
    for i in range(3)
]
for i, request in enumerate(requests, 1):
    (OUT / f"selection-request-{i}.json").write_text(json.dumps(request, indent=2) + "\n")
(OUT / "selection-wording-audit.json").write_text(json.dumps({
    "passed": True,
    "method": "Codex authored three full rewrites and manually checked semantic equivalence: same objective, contract, pins, qualification counts, strengths, faults, limits and alternatives in each. Every explanatory state field, instruction and option differs across each pair; identifiers, code, numbers and schema keys remain exact. Automated distinct-field assertions pass. This is wording review, not proof of unbiased classification.",
    "request_pairs": list(itertools.combinations([1, 2, 3], 2)),
}, indent=2) + "\n")
if "--send" in sys.argv:
    for i in range(1, 4):
        raw = (OUT / f"selection-request-{i}.json").read_bytes()
        req = urllib.request.Request("https://api.typesafe.ai/v1/systemone", data=raw,
            headers={"Authorization": "Bearer " + os.environ["TYPESAFE_API_KEY"],
                     "Content-Type": "application/json"})
        with urllib.request.urlopen(req, timeout=45) as response:
            answer = json.load(response)
        (OUT / f"selection-response-{i}.json").write_text(json.dumps(answer, indent=2) + "\n")
        print(json.dumps({"round": i, "answers": answer.get("answers"), "model": answer.get("model")}))
