package app
    provides []
    uses [sql]
fn sql::decision<sql::transaction[]> capture
    emits []
    given
        near bool take
        sql::transaction tx
    asserts
        harmless: false => ok sql::commit<sql::transaction[]>([])
    match take
        false => ok sql::commit<sql::transaction[]>([])
        true => ok sql::commit<sql::transaction[]>([tx])
fn void main
    emits []
    given
        str[] args
    asserts
        empty: [] => ok
    ok
