"""Fresh, separately worded Jev consultations; docs-only preparation."""
from pathlib import Path
import datetime, json, os, sys, urllib.request, urllib.error, time
OUT = Path(__file__).resolve().parent
facts = {
'objective': [
'Can is a language for AI coding agents; human familiarity is not an optimization target. Correctness and reliable edits outrank total tokens per successful task, a secondary measured goal. There are zero external users or old-source compatibility obligations. Generated TypeScript uses equivalent native JavaScript/Bun operations and only needed contract adapters. Select a design direction for an implementation plan, not a claim that it is implemented.',
'The intended authors are AI agents, even if humans find the language harsh. Prioritize correct programs and safe modifications; count complete successful-task tokens second. No external adopter requires migration compatibility. Lower equivalent behavior to native JS/Bun with minimal contract-preserving adaptation. This evaluation guides future work and confers no implemented capability.',
'Judge two planned language decisions for agent-written software. Human comfort carries no independent weight. Successful behavior and dependable refactors come first, with whole-task token cost measured afterward. The project has no outside users and may replace old syntax freely. Emitted TS must delegate equivalent operations to JavaScript/Bun, adding adapters only for language guarantees. Advice concerns design preparation rather than delivery.'
],
'error_evidence': [
'Current source requires error 1000000 payment_declined(str reason), duplicated in an active/retired registry. Graph, checker and runtime reject overlapping application numbers across owners, including a foreign retired number. Yet matching, bounds and assertion equality use qualified declaration plus concrete generic arguments. Terminal JSON contains both numeric id and full typeIdentity with redacted payload. A repository consumer audit found no requirement to resolve a naked application integer across locked builds or preserve it across renames. Both alternatives require coordinated loader/lock/checker/emitter/runtime/report/test changes; built-in catalogue numbers may remain internal metadata.',
'The existing declaration error 1000000 payment_declined(str reason) allocates its integer again in project registry data. Loading, checking and runtime admission enforce global numeric exclusivity, even against another project’s retirement list. Nominal dispatch and assertion comparison already distinguish resolved declaration identity and generic specialization. Unhandled failure reports expose id alongside typeIdentity and redact payloads. Audited consumers establish neither bare-number lookup across builds nor numeric continuity after renaming. Either redesign touches graph and lock, checks, emission, runtime, diagnostics and tests; catalogue-owned numeric tags can stay internal.',
'Today an author writes error 1000000 payment_declined(str reason) and maintains the corresponding registry allocation. Independently developed owners collide because active and retired integers are globally reserved at load, check and runtime boundaries. Actual type matching, error bounds and assertions distinguish qualified symbols and instantiated arguments. The terminal emits a number plus full typeIdentity without revealing protected payloads. Source inspection found no consumer demanding standalone integer interpretation between locked builds or stability through declaration renaming. Both candidates require the full compiler-to-report migration, while internal built-in numeric metadata need not disappear.'
],
'error_contract': [
'After authoring in the chosen grammar, unrelated dependencies must compose without coordinated allocations or further source changes. Preserve distinct owners and generic specializations, redaction, reproducible reports, checkout-relocation independence and interpretation of archived reports from two locked builds. Define rename/retirement and canonical owner scope explicitly. Adding unrelated dependencies must not conflate identities. A compact optional number is build-local only with build ID and archived reverse map; no unqualified integer is a nominal type.',
'The selected scheme must let independently authored libraries link unchanged without negotiating identifiers. Owner separation, generic error distinctions, redacted reporting and reproducibility are mandatory. Explain canonical ownership and rename/retirement policy; relocation cannot affect identity, and unrelated graph growth cannot merge errors. Reports from both old and new locked builds must remain interpretable using promised artifacts. Any optional short integer belongs to its identified build and retained reverse mapping, never replacing nominal type identity.',
'Require composition of two separately written dependencies once each uses the new design, with no joint numbering agreement or link-time source rewrite. Maintain owner-qualified and generic-specialization distinctions as well as redaction and deterministic reports. Specify owner scope and the treatment of renamed or retired declarations. Moving a checkout must not alter identity; adding a foreign dependency cannot collapse identities. Retain enough artifacts to interpret reports from two locked builds. If compact numbers appear, label their build and archive their inverse map rather than treating the number as a type.'
],
'action_evidence': [
'The current strongest idiom has centralized URL/status/render helpers, shallow raw-form records and explicit result variants. An isolated invoice Can probe passed 18 assertions, but did not exercise HTTP, a live database or DOM; it cannot prove protected effects. Safe URL and target types do not tie a request to an exact endpoint. Wire field/error strings and separately repeated route/method literals can drift without compile errors. Proposed source and manifest alternatives have equal semantics and neither is implemented or agent-benchmarked. Either needs checker/emitter/catalogue and native adapters. Existing static descriptor checks provide precedent, not an existing action implementation.',
'Current Can can centralize URLs, rendering and status selection, decode a shallow raw record and return finite outcome cases. Its 18-assertion invoice experiment is source-only evidence, without HTTP/database/browser observation or protected-effect verification. Generic URL safety and target typing lack exact route ownership, while field names and duplicated mount/request literals admit unchecked drift. The two linked-contract candidates promise the same checks; neither has an implementation or held-out agent result. Both incur compiler/catalogue/emitter plus native-adapter work. Present static descriptor validation is only an analogy.',
'A factored baseline uses ordinary helpers for route construction, status and HTML, with raw-form types and finite results; the invoice probe passed 18 assertions. That run established no live HTTP, persisted writes or browser swaps. Existing URL/target safety cannot identify a particular action. Independent route/method occurrences and form-error/control strings may become inconsistent without static rejection. A source declaration and a checked manifest could each close these gaps with identical semantics, but neither has been built or measured on agent tasks. Both demand checking, emission, catalogue and runtime adapters; other static descriptors do not already supply this feature.'
],
'action_contract': [
'Use exact-path POST /invoice/edit with invoice_key query, invoice_form shallow raw strings, 2048-byte limit, and edit_outcome cases saved/invalid/conflict/forbidden/unavailable mapped to actual 200/422/409/403/503 and inner-swap policy. One canonical package-instance/declaration identity links URL builder, method, form, mount and exhaustive response mapping. Checked direct field references preserve wire owner/type; strict decoding handles duplicates/unknown fields. Endpoint identity does not prove authorization, DOM presence, persistence or retry safety. Handler owns authentication/CSRF and protected tenant/revision checks; browser and database tests remain necessary. Server mount must not enter browser builds. Typed path captures, nested rows, components and typed DOM scopes are separate work, not prerequisites for this choice.',
'The bounded feature is a POST at /invoice/edit using invoice_key query data and raw invoice_form members, capped at 2048 bytes. Map saved, invalid, conflict, forbidden and unavailable to genuine 200, 422, 409, 403 and 503 responses with declared inner replacement. Canonical package instance plus action declaration joins construction, method, mount, input and complete case mapping. Direct wire-field references carry ownership and exact types, and strict form parsing rejects duplicate or unknown fields. Such checking cannot guarantee permissions, an existing target, durable writes or safe retries. Server handlers still enforce actor/CSRF and tenant/revision protections; real DOM and database observations are required. Browser compilation excludes mount. Captured paths, nested forms, component syntax and render-scope targets are independently scoped.',
'Test only the exact POST /invoice/edit first: query invoice_key, shallow string invoice_form, maximum 2048 bytes, result edit_outcome. Its five leaves saved/invalid/conflict/forbidden/unavailable retain HTTP 200/422/409/403/503 respectively and request inner swaps. Resolve one action identity from its package instance and declaration for the route builder, method, form, handler binding and exhaustive status table. Typed direct field handles retain wire ownership; strict decoding addresses unknown names and duplicate scalar fields. This gives no authorization, target-existence, commit or retry proof: server-owned authentication/CSRF plus tenant/revision enforcement and observed browser/database tests remain obligations. Reject server mounts on browser targets. Do not bundle typed captures, row forms, components or typed DOM regions into this decision.'
],
'action_tradeoffs': [
'A source declaration keeps the contract beside ordinary types, adds top-level action grammar/contextual sections and exported static action symbols consumed by catalogue operations; action symbols cannot become arbitrary mutable runtime data. A manifest descriptor adds no Can declaration grammar but introduces a second checked authoring surface, type/case strings resolved as symbols, synthetic package members, collision/privacy/ownership rules and key-aware diagnostics. It must resolve in the owning dependency environment. It generates ordinary URL/post/mount functions with identical static guarantees. Ordinary helpers add no new language mechanism but leave exact endpoint and string drift checks to disciplined centralization and companion tests. Measure creation, rename and diagnostic repair against this factored baseline before making agent-efficiency claims.',
'Putting action beside Can types requires parser support for a declaration and its sections, export/resolution of static symbols and catalogue consumers; it must restrict those symbols from mutable general data. JSON placement avoids that grammar while requiring symbol-aware manifest checking, generated package APIs and rules for collisions, private types, ownership and precise key diagnostics. Its symbol lookup uses the declaring project’s dependencies and generated URL/post/mount calls retain the same checked semantics. Keeping only helper functions costs no new mechanism, yet endpoint identity and loose string consistency remain discipline/test obligations. Comparative creation, edit and error-repair tasks must include the strongest centralized helpers; no token benefit has been established.',
'One candidate introduces an action declaration next to source types, contextual parser sections, resolvable exported static symbols and checked catalogue consumption. Such symbols must not be unconstrained mutable values. Another records the same contract in JSON and synthesizes ordinary URL/post/mount members. Although it avoids new Can grammar, it needs typed manifest references, owner-environment resolution, namespace-collision/privacy rules and file/key diagnostics across two authoring surfaces. A helpers-only approach introduces neither surface and relies on centralized code plus protocol tests for the untyped endpoint/string relationships. Any efficiency judgment must compare creation, renaming and repair with that factored baseline; these candidates have no task-token measurements.'
]
}
questions = {
'application_error_identity': {
'instructions': [
'Which of the two complete application-error authoring and reporting contracts should be selected for the implementation plan, given the audited consumers and required independent composition?',
'Select the better future error declaration/reporting design for agent-authored libraries using the consumer evidence and identity obligations supplied here.',
'Which application error contract should engineering specify now to remove cross-owner allocation conflicts while retaining the required reporting and nominal guarantees?'
],
'criteria': {
'qualified_text': [
'Adopt error payment_declined(str reason), without an authored application integer or active numeric registry. Canonical owner/declaration plus concrete arguments identify errors; use explicit qualified textual report keys. Renames create a new identity and archived old reports remain tied to their locked build; optional compact IDs require per-build reverse maps. Define textual retirement/reuse policy without duplicating active source allocations.',
'Choose an unnumbered declaration, error payment_declined(str reason), and remove application active-number bookkeeping. Report resolved qualified owner/declaration identities with generic arguments. A rename denotes a different error and historical reports retain their build interpretation; optional integer compaction needs an archived build mapping. State textual-name retirement and reuse rules separately from active source declarations.',
'Use error payment_declined(str reason) with no source-assigned application code or parallel active numeric list. Base reporting on explicit canonical qualified declaration keys and instantiated types. Renamed declarations get different identities; old locked-build reports remain decodable. Permit only mapped build-specific compact integers and specify textual retirement/reuse without duplicating active allocations.'
],
'owner_number': [
'Adopt error 1000000 payment_declined(str reason) with an owner-local active/retired registry. Independent owners may allocate or retire the same number. Reports identify canonical owner plus local number and concrete generic type, never a naked integer; retain within-owner numerical stability and its retirement policy despite duplicated source/registry allocation.',
'Keep error 1000000 payment_declined(str reason), but scope the number ledger to its owner. Foreign active or retired values do not collide. Emit owner identity, local code and concrete type arguments together, preserving each owner’s numeric continuity and tombstones while maintaining both authored declaration and registry allocation.',
'Retain the numbered declaration error 1000000 payment_declined(str reason) and active/retired bookkeeping per owning project. Allow identical integers in unrelated projects, qualify report codes by owner and retain full instantiated type identity. This supports owner-local stable numbers and retirement, at the cost of writing the allocation in source and registry.'
]
}},
'action_contract_placement': {
'instructions': [
'Which authoring direction should the implementation plan use for the bounded checked action contract, weighing reliable agent edits and mechanism cost without assuming unmeasured token gains?',
'Choose the planned surface for exact endpoint, form and finite-response linking, using the common contract and present evidence rather than human familiarity or untested brevity claims.',
'What design should engineering specify for action authoring in this bounded workload, considering static repair guarantees and full implementation cost under the stated evidence limits?'
],
'criteria': {
'source_action': [
'Add a source action declaration adjacent to its Can types, with method/path/query/form/result/body/case sections and exported canonical static symbol. Checked action::url, action::post and action::mount consume that symbol. Implement the shared exact-path/field/response semantics and compare against current helpers; leave captures separately gated.',
'Author the linked contract in Can beside the wire and outcome types via new action syntax. Export its static identity for action::url, action::post and action::mount. Supply the same method, route, form and exhaustive status checks as the manifest candidate, test against centralized helpers and defer optional capture design.',
'Specify a Can action declaration containing the bounded route/input/result/policy table, producing an exportable static action identity. Catalogue action::url, action::post and action::mount operate on it. Build the common exact-route guarantees with the existing helper pattern as control; path captures remain a separate increment.'
],
'checked_manifest': [
'Add a checked actions manifest descriptor referencing owner-relative Can types/cases and synthesizing ordinary save_invoice_url/save_invoice_post/save_invoice_mount calls. Implement the same exact-path/field/response guarantees without a new Can declaration; compare with the factored helper baseline and leave captures independent.',
'Place the action table in a symbol-checked manifest section, resolved in its owner’s environment, and generate save_invoice_url/save_invoice_post/save_invoice_mount members. Preserve all shared route, form and response checks while avoiding action grammar; benchmark the centralized baseline and gate captures separately.',
'Choose typed manifest action metadata, binding Can type/case names and generating ordinary save_invoice_url/save_invoice_post/save_invoice_mount APIs. This supplies the identical bounded semantic checks via a second authoring surface, with no action declaration syntax. Compare helper controls and keep captures out of the initial scope.'
],
'ordinary_helpers': [
'Retain only ordinary centralized helpers and companion HTTP/browser/database tests for now. Do not implement a checked action declaration or manifest descriptor; accept that exact endpoint identity and loose string drift are not static guarantees and revisit a mechanism only after further measured baseline failures.',
'Keep the factored helper approach as the planned mechanism, backed by protocol/DOM/storage tests. Add neither source actions nor checked manifest synthesis yet, explicitly leaving endpoint identity and string consistency outside compile-time checks until additional comparative evidence warrants them.',
'Continue with existing URL/status/form/render helpers plus external observations, deferring both new action surfaces. Declare the absence of exact endpoint typing and static string-link checks, and require more baseline/agent evidence before introducing either dedicated mechanism.'
]
}}
}
for section in facts.values():
 assert len(section)==3 and len(set(section))==3
for q in questions.values():
 assert len(set(q['instructions']))==3
 for c in q['criteria'].values(): assert len(c)==3 and len(set(c))==3
for i in range(3):
 payload={'model':'jev-latest','state':{k:v[i] for k,v in facts.items()},'questions':{k:{'type':'choice','instructions':q['instructions'][i],'criteria':{c:v[i] for c,v in q['criteria'].items()}} for k,q in questions.items()}}
 (OUT/f'request-{i+1}.json').write_text(json.dumps(payload,indent=2,ensure_ascii=False)+'\n')
(OUT/'wording-audit.json').write_text(json.dumps({'review':'Before sending, manually compared all three requests: same objectives, current source/registry and audit findings, report/type obligations, 18-assertion limitations, exact invoice contract, boundaries, candidate mechanisms and costs. Every explanatory state field, question instruction and option description has independently rewritten prose. Exact language/API identifiers and literal code remain stable. Prior consultation answers and preferred recommendations are excluded.','automated_check':'All explanatory string triples have length three and pairwise distinct full wording.','limit':'Semantic equivalence is a reviewed judgment, not a machine proof. Rephrasing cannot establish absence of bias; report all distributions and investigate splits.'},indent=2)+'\n')
if '--send' in sys.argv:
 key=os.environ['TYPESAFE_API_KEY']
 for i in range(1,4):
  for attempt in range(1,4):
   req=urllib.request.Request('https://api.typesafe.ai/v1/systemone',data=(OUT/f'request-{i}.json').read_bytes(),headers={'Content-Type':'application/json','Authorization':'Bearer '+key})
   started=datetime.datetime.now(datetime.timezone.utc).isoformat()
   try:
    with urllib.request.urlopen(req,timeout=60) as r: body,status=r.read(),r.status
    (OUT/f'response-{i}.json').write_bytes(body+b'\n')
    (OUT/f'response-{i}.metadata.json').write_text(json.dumps({'startedAt':started,'status':status,'attempt':attempt,'endpoint':'v1/systemone'},indent=2)+'\n')
    data=json.loads(body); print(json.dumps({'request':i,'model':data.get('model'),'answers':data.get('answers'),'usage':data.get('usage')}),flush=True)
    break
   except urllib.error.HTTPError as e:
    (OUT/f'response-{i}.attempt-{attempt}.error.json').write_bytes(e.read()+b'\n')
    if e.code not in (429,529) or attempt==3: raise
    time.sleep(2**attempt)
