"""Prepare/audit three fresh independent Jev batches; --send transmits exact saved bytes."""
import datetime
import hashlib
import itertools
import json
import os
from pathlib import Path
import sys
import time
import urllib.error
import urllib.request

OUT = Path(__file__).resolve().parent

def triple(a, b, c):
    assert len({a, b, c}) == 3
    return [a, b, c]

state = {
"constraints": triple(
"Can targets AI coding agents. Correctness, explicit contracts and edit reliability rank before total tokens per successful task; human familiarity and source brevity do not settle design. There are no external users or compatibility duties. Prefer equivalent native JavaScript/Bun/browser operations plus only contract/immutability adapters. These are technical prototype judgments, not syntax choices or product preferences; no new contract is adopted. Jev cannot research, and these supplied facts are the complete evidence.",
"The language's audience is AI agents, so assess reliable changes, contract precision and correct behavior first, and whole successful-task token cost second. Neither familiar notation nor shorter source is decisive. Compatibility has no value here because Can has zero outside users. Lower to matching native JavaScript, Bun or browser APIs with bounded safety/immutability glue. Advise on engineering experiments only: do not select spellings, user priorities or final guarantees. All available evidence is included; no independent research is available to this classifier.",
"Judge experimental engineering for an agent-authored language with no external users and no need to retain old interfaces. Semantic correctness, declared boundaries and robust agent edits are primary; count all tokens through successful repair as a secondary metric, without optimizing for human comfort or line count. Native JavaScript/Bun/web operations should implement equivalent behavior, supplemented only to preserve Can contracts and immutable data. Your choice is advisory preparation, never a syntax decision or a customer-facing commitment. Use solely the evidence provided rather than assuming researched facts."),
"evidence_status": triple(
"The audited source baseline is 02a549d28fd5fc5c3996160e65a97de332390d30. Current deployment qualification is bun-1.4.2-darwin-arm64-v1, not Linux. Upstream facts describe possibilities and need pinned-binary probes. No invoice/webhook product slice, dedicated account-search 503 browser reproduction, browser compiler, offline prototype, schema-snapshot check or comparative agent trial has been executed in these packets. Component tests and source audits support narrower claims. The broader target includes Can-authored frontend and backend; SSR or a foreign client qualifies a narrower result.",
"Evidence comes from source revision 02a549d28fd5fc5c3996160e65a97de332390d30 and component checks. The only qualified runtime target is bun-1.4.2-darwin-arm64-v1; Linux lacks qualification. Current native-platform documentation is not a test of that pinned runtime. These notes have no executed end-to-end invoice or webhook, account-search 503 browser case, browser compilation, offline model, versioned-schema check or agent comparison. Keep all such claims provisional. The program seeks both frontend and backend authored in Can, whereas server rendering and foreign-browser code demonstrate less.",
"Treat 02a549d28fd5fc5c3996160e65a97de332390d30 as the inspected implementation revision. Qualification covers bun-1.4.2-darwin-arm64-v1 alone, with Linux still unverified; documented native features must be exercised on pinned binaries. Audits and isolated tests exist, but this evidence does not contain running invoice/webhook flows, an account-search 503 browser reproduction, a Can browser compiler, offline experiments, a schema snapshot validator or measured agent comparisons. Those missing demonstrations limit the strength of advice. Can-written client and server remain the wider goal; SSR and a client in another language are narrower baselines."),
"routes": triple(
"DI-09a currently admits literal exact paths and named handlers, rejects dynamic path segments, and can pass tenant/invoice IDs through query strings with explicit conversion. Named URL builders and centralized endpoint records are the strongest existing baseline. html::url validates URL safety, not mount identity, method, payload or DOM presence. A checked exact endpoint could join mount/method/request/response/URL references; named path captures additionally need wire parsing, encoding round trips, slash/invalid-encoding rules and ambiguity/precedence checks. Native Bun parameter routing is documented but unprobed on the pinned binary. Package identity must compose across imports; source rename and wire path change differ.",
"For DI-09a, today's router matches exact literals via named callbacks and refuses captures. Explicitly parsed query parameters already carry tenant and invoice keys; central builders or endpoint records reduce duplicate strings. The guarantee of html::url stops at safe URLs and excludes router membership, HTTP verb, body contract and target existence. Compiler-linked exact endpoints would connect mount, method, request, response and URL use. Adding captures also requires typed wire conversion, correct encoding, slash and malformed-escape semantics plus duplicate/precedence rules. Bun advertises native captures, pending pinned-version verification. Imported endpoint identity must remain coherent, and changing a symbol need not change its wire path.",
"The DI-09a baseline uses named handlers mounted at literal paths; dynamic segments are disallowed. Tenant/invoice identifiers can instead travel as query text with application parsing, with shared URL helpers or an endpoint record centralizing construction. html::url proves only URL admission, never an endpoint's existence, verb, input shape or live target. Exact-path checked identity can tie declaration and request/response/method/URL consumers together. Capture support expands that work to conversion failures, encode/decode parity, slash handling, invalid escapes and route conflict ordering. Although Bun documents parameter routes, the pinned build has not been tested. Cross-package identity is required, and source identifier refactors are separate from wire-path edits."),
"forms": triple(
"DI-09b form decoding produces shallow str, optional str and str[] records; strict UTF-8/percent parsing rejects unknown fields and scalar duplicates while retaining repeated array entries. Explicit validation maps text to domain values and can retain raw values plus independent field errors. Separate repeated columns do not intrinsically preserve row identity. Candidate line items use validated parallel arrays, checked keyed rows, or a separately declared exact JSON action. Missing/empty/partial values, duplicate keys, deletion/reorder and stable error paths all need definition. Form text is not JSON, and server validation and package-owned validated-value construction remain required.",
"The current DI-09b wire contract is a flat record containing str, optional str or str[]: malformed UTF-8/escapes, unknown names and repeated scalars fail; repeated array fields survive. Applications parse domain values explicitly and can return the original text with accumulated independent errors. Row association does not follow from several repeated columns. Options are parallel arrays with validated alignment, an identified-row decoder, and an independent action using the exact JSON codec. Each must address absent versus empty data, incomplete rows, repeated row identifiers, removal/reordering and error-to-control correspondence. Do not reinterpret HTML fields as JSON or bypass server/domain-owner validation.",
"In DI-09b, shallow string/optional-string/string-array records are the admitted form schema. The decoder enforces UTF-8 and escape validity, rejects unknown fields or duplicate scalar controls, and keeps repeated array values. A separate validation step builds domain records while preserving rejected text and collecting unrelated field failures. Repeated names across columns supply no checked row pairing. Compare an alignment-checked array representation, keyed row paths with validation, and a distinct JSON endpoint under the existing exact codec. Semantics must cover missing/empty/partial rows, repeated keys, reorder/delete and persistent field-error identity. Ordinary form encoding stays distinct from JSON; protected values and server checks cannot be bypassed."),
"actions_html": triple(
"DI-09d maps finite application outcomes in named response handlers. The vendored HTMX policy swaps 422 but excludes other 4xx/5xx, so the account-search 503 fragment is inferred not visible; a dedicated browser reproduction is missing. Options include explicit status/swap policy, checked action-case mapping and scoped target references. Conditional removal means a typed ID alone cannot prove DOM presence. Preserve actual 200/422/409/403/503 status, retained values, focus, announcements and response ordering. DI-10 safe builders escape text with Bun.escapeHTML, validate URLs/attributes/structure at runtime and produce immutable nodes; named render helpers are the baseline. Literal-call checking or declarative components could diagnose known-invalid structure earlier. All alternatives retain dynamic checks, safe URLs, controlled assets and no raw markup/script escape; accessibility tag expansion is separate catalogue work.",
"Named handlers already turn finite DI-09d outcomes into safe responses. Only 422 among HTTP failures is swapped by the pinned HTMX policy; source inspection therefore predicts hidden account-search 503 feedback, without a reproduced browser case yet. Compare application mapping with narrow swap configuration, exhaustively checked result mapping and target references tied to render scopes. A target that disappears conditionally still needs runtime treatment. Keep the true 200/422/409/403/503 codes and test input retention, focus, announcements and out-of-order replies. For DI-10, reusable helper functions over safe constructors are the current benchmark: Bun.escapeHTML escapes text and runtime code checks URLs, attributes and structure while preserving node immutability. Earlier literal checking and a declarative component model are proposed. Dynamic safety checks, admitted assets and the raw-script/markup exclusion remain mandatory; adding accessible elements does not imply new syntax.",
"The existing DI-09d idiom explicitly maps application cases in named response functions. Can's HTMX asset swaps status 422 and suppresses all remaining 4xx/5xx swaps; this implies the 503 account-search body will not appear, but that exact browser experiment has not run. Possible additions are a configured application status policy, checked per-result mappings or scoped target identities. Conditional DOM disappearance is not ruled out by a typed target name. Real HTTP codes 200/422/409/403/503, retained fields, focus/error announcements and ordering of replies all matter. DI-10 already offers immutable safe HTML constructors and factored render helpers using Bun.escapeHTML plus runtime URL, attribute and structural validation. Static literal-call analysis or checked component declarations could move known faults earlier. Retain runtime validation for unknown values, URL constraints and controlled browser assets; admit neither raw HTML nor authored script, and treat accessibility element coverage separately."),
"browser": triple(
"DI-11 currently runs Can on Bun and serves HTML/HTMX, with no admitted authored browser JS/TS workaround. A Can-authored rich grid needs separately compiled browser execution; a typed foreign-language bridge or SSR baseline does not prove that outcome. The smallest proposed main-thread profile has shared data/validation, DOM/events, Fetch, explicit state/rendering and disposal; workers are separate because they lack document access. Server-only env, SQL, filesystem/process and HTTP capabilities must be excluded transitively through imports, generics and callbacks and absent from bundles. Cross-target codecs must agree on exact integers, finite floats, records, tagged options/variants, unknown/duplicate fields, immutable aliases and completion boxing; Number alone cannot assume full int fidelity. No browser compiler or conformance result exists.",
"Today's DI-11 admission permits Bun-side Can with HTML and HTMX, not project-authored browser JavaScript or TypeScript. SSR and a checked bridge to another client language can be comparators but cannot demonstrate a rich frontend written in Can. A limited browser compilation proposal covers main-thread shared validation/data, DOM events, Fetch, state transitions, rendering and disposal; worker execution needs its own non-DOM profile. Enforce exclusion of server env, SQL, files/processes and HTTP operations through callback, import and generic dependency closure as well as emitted bundle contents. Match server codecs for full exact int, finite float, records, variant/tagged option shapes and rejection of extra/duplicate fields, plus immutable alias and completion-boxing behavior. Native Number is insufficient as an assumed integer representation. These target guarantees have not yet been implemented or demonstrated.",
"Can currently authors Bun applications with safe HTML/HTMX only; browser JS/TS supplied by an app is outside admission. Showing SSR or a foreign-language typed client establishes less than the requested Can-written rich frontend. The bounded candidate is a distinct main-thread browser build admitting shared validation/data, DOM/event work, Fetch, explicit local transitions/rendering and lifecycle cleanup. Workers cannot touch the document and require separate treatment. Server environment, SQL, process/file and HTTP operations must neither remain callable through imports/generics/callbacks nor leak into the bundle. Both targets need identical exact integer and finite-float wire behavior, record and tagged variant/option encodings, unknown/duplicate rejection, immutable aliases and boxed completions. Full int behavior cannot be presumed from Number. No such browser build or parity experiment is in the evidence."),
"offline_lifecycle": triple(
"DI-11 has three unselected offline experiments: memory draft plus explicit retry (view lifetime only); locally durable versioned draft plus explicit submit (storage permitting, not queued effects); durable identified mutation queue with ordering/reconciliation and server deduplication where supported. Online indicators do not prove endpoint reachability. Durable drafts need user/tenant isolation, sign-out policy, quota/eviction handling and schema migration; queues add crash windows, authorization expiry and multi-tab coordination. Offline shell reload and background sync are separate promises. Start-point advice must not select the user's durability preference. All save designs track acknowledged revision, current draft, pending mutation identity and status; late replies cannot erase newer edits. Disposal releases listeners/timers and prevents view updates, but Fetch abort does not undo remote commit. View-owned work and application-owned continuing mutations need distinct owners and uncertain outcomes require reconciliation.",
"Offline scope remains open in DI-11: retaining an in-memory draft until the view dies with deliberate retry; persisting a schema-versioned draft for explicit later submission when storage is available; or persisting mutation IDs in a reconciled queue whose business deduplication relies on the server. A browser online hint says nothing definite about this endpoint. Disk drafts require account/tenant partitioning, logout rules, migration and visible storage quota/eviction failures; queues additionally require multi-tab coordination, expired-auth handling and recovery across crashes. Neither app-shell availability without a network nor background sync follows automatically. Recommend experimental sequencing, never a durability preference. Represent revision acknowledged by the server, newer local edits, mutation identity and save state in every design. Removing a view must clean its listeners/timers and stop its updates, while cancelling Fetch cannot establish rollback. Continuing mutations need an application owner separate from the view and ambiguous acknowledgements must be reconciled.",
"Three technical offline models await evaluation: live-view memory edits with manual retry; a versioned local draft restored subject to storage availability and explicitly submitted; and a durable mutation queue with stable IDs, ordered recovery/reconciliation and server-supported deduplication. The online flag is merely advisory about connectivity. Local persistence introduces identity isolation across tenants/users, sign-out behavior, schema upgrades and quota/eviction outcomes. Queued effects also introduce multi-tab races, expired authorization and crash recovery. Do not conflate either with offline app-shell reload or background synchronization, and do not make a product promise from the selected trial baseline. Independently, saves require the acknowledged server revision, present draft, identified pending change and outcome state, preserving edits newer than a reply. Listener/timer cleanup and suppression of disposed-view updates are local duties; Fetch abort cannot reverse a server write. View and application owners must distinguish work that ends on disposal from tracked mutations that continue, with uncertain effects reconciled."),
"observation": triple(
"DI-13 attached assertions check computation and fixture behavior; bare => ok for an opaque response does not compare status, headers, body, DOM or database effects. Companion protocol/browser/live-database tests already provide separate observation layers. Compare improved companion tooling, read-only protocol projections and a source scenario runner; projections still cannot prove DOM swaps. Fixture identity, argument checking, isolation and FIFO must survive caller-label renames, with cross-package selection coordinated through DI-06. Wrong-body 200, executable injection, unswapped 503, UI/row disagreement and duplicate successful webhook effect need detection at their relevant layers. Disclose skipped integration prerequisites; no runner proves universal correctness.",
"A DI-13 source assertion accepting opaque => ok establishes execution only, excluding HTTP status/header/body, browser changes and persisted writes. The current stronger idiom combines attached computation/fixture tests with external protocol, browser and real-database tests. Additional options are better companion-test support, safe read-only response projections, and an authored scenario runner; even a projected HTTP body does not establish a swap. Keep checked fixture arguments, invocation identity, per-scenario isolation and FIFO, and ensure DI-06 cross-package reuse is stable when caller labels change. Challenges include a wrong 200 body, active injection, an invisible 503, correct-looking UI with incorrect rows and repeated webhook business effects. Report missing prerequisites/skips, and never describe the runner as a general proof.",
"Existing DI-13 attached tests inspect Can computations and fixture queues, but bare => ok on an opaque server result cannot inspect its protocol contents, resulting DOM or lasting effects. Today's layered alternative uses companion HTTP, browser and live-database observations. Consider improving that tooling, admitting read-only HTTP projections, or introducing a source-authored multi-layer scenario runner. An HTTP-level projection is insufficient to certify target updates. Reusable fixtures must preserve argument checks, isolated FIFO invocation identity and caller-rename stability via DI-06. Observation adequacy is tested by incorrect success bodies, executable hostile output, suppressed 503 rendering, wrong database rows despite a correct UI and duplicate webhook effects behind success statuses. Missing integration runs remain explicitly missing; no scenario machinery supplies universal proof."),
"sql": triple(
"DI-14 currently validates static descriptor parameters/cardinality, binds parameters and checks returned column/type/value shape at runtime. Row-returning descriptors require bounded SELECT; execute permits mutations but rejects RETURNING and supplies affected-row counts. A scoped-transaction read after mutation or known-value response is the baseline. PostgreSQL RETURNING could return canonical mutation rows but needs supported forms, dialect, finite cardinality/zero-row semantics and codecs. Tenant/revision checks remain in the protected write or explicit locking/isolation; Read Committed pre-read alone is unstable. Returning rows does not settle commit_unknown: failure after the commit decision requires durable identity lookup/reconciliation. Compile-time schema agreement is absent. Alternatives are migration-linked real-DB tests, a provenance/versioned deterministic schema snapshot with drift checks, or a database-connected build naming its checked schema. All retain runtime codecs; none proves deployed-schema agreement without deployment verification.",
"The DI-14 implementation admits bounded SELECT row results and mutation execute counts while refusing mutation RETURNING. It already checks descriptor/parameter/cardinality shape, performs parameter binding and validates row columns/scalars at runtime. To obtain canonical data, use a known response or a second read within the transaction. Native PostgreSQL RETURNING is a candidate with explicit dialect/forms, row bounds, zero-result handling and projection codecs, not a solution to authorization or revision checks. Protect writes with tenant/revision predicates or declared locks/isolation: a Read Committed pre-read can change. commit_unknown after deciding to commit still requires durable-ID reconciliation. No current build validates projection against a database schema. Compare tests coupled to migrations, versioned/provenanced schema input with freshness/deploy-drift checks, and live-database build checks identifying their schema. Keep runtime codecs under each; checking a build schema does not establish production agreement absent deployment verification.",
"For DI-14, Can statically checks descriptors and parameter/cardinality admission and dynamically binds parameters and validates row names, scalar types and values. Only bounded SELECT can return rows; mutation execute returns counts and disallows RETURNING. Canonical post-write values currently need a known-value response or a transaction-local follow-up read. PostgreSQL's native RETURNING can be assessed if mutation forms, dialect, finite result bounds, zero rows and row codecs are explicit. It cannot replace tenant/revision protection at the write or stated isolation/locking, since Read Committed does not freeze an earlier read. Nor can it resolve commit_unknown after a commit decision; durable operation identity and reconciliation remain necessary. Schema agreement is not checked at compile time today. The alternatives add migration-backed database tests, a reproducible schema snapshot with version/provenance and staleness/deployment checks, or builds consulting a named live schema. Each still needs runtime row checks and verification that the deployed database matches what was checked."),
"cancellation": triple(
"DI-15 owners/leases preserve live work until settlement; race losers are not automatically cancelled. Close/shutdown deadlines bound waiting but neither cancel arbitrary native work nor release its lease, so a permanently pending owner can prevent clean drain. Fetch/streams have specific abort paths; Bun documents SQL reservation-wait abort only before acquisition, not running-query cancellation. Native Promise.race stays pending when empty; Promise.any fails when empty; application nonempty guards preserve these current semantics. Options for shutdown are explicit operation APIs plus qualified host grace/kill, a cancellation context propagated only through supported adapters, or worker/process isolation for bounded computation with serialization/effect-recovery cost. Distinguish requested cancellation, settlement, resource release and host kill; kill proves no cleanup or rollback. Disconnect during commit/outbox send, hung loser and forced termination need owner/lease, rows and external-effect observations on a named installed target.",
"Live DI-15 work retains owner leases until it settles, including losing race participants; there is no implicit loser abort. A close or shutdown timeout stops a wait rather than arbitrary native effects or lease retention, and hung work may block root drain indefinitely. Abort adapters exist for Fetch and streams; the only supplied SQL signal behavior cancels reservation waiting before acquisition, not an active query. Keep native empty Promise.race pending and empty Promise.any failing, using application guards when participants are required. Candidate termination strategies are specific operation controls with tested supervisor grace/kill, supported-adapter cancellation-context propagation, and isolated workers/processes with message/effect-recovery overhead. Cancellation request, actual completion, resource cleanup and forced process exit are separate observations, and kill ensures neither rollback nor clean release. Test disconnect at commit/outbox, permanent losers and forced exit by observing leases/owners, stored rows and external effects on an identified installed platform.",
"DI-15 currently keeps ownership and resource leases for all unsettled participants, including race losers, without automatic cancellation. Deadlines on close/shutdown limit the caller's patience but cannot discard the underlying lease or terminate arbitrary native work; a never-settling owner can hold drain forever. Fetch and stream adapters support particular cancellation actions. Documented SQL reservation abort covers only waiting before acquisition and establishes nothing about cancelling an executing query. Existing native semantics leave an empty Promise.race unresolved and make empty Promise.any fail; explicit nonempty guards are the current idiom. Compare per-operation controls plus qualified supervisor timeout/kill, a context conveyed only to cancellable adapters, and worker/process separation to stop bounded computations at serialization/recovery cost. Keep cancel intent distinct from settlement, actual release and host termination; forced exit is not rollback or cleanup evidence. Probe disconnect around commit/outbox delivery, a hung loser and forced shutdown using owner/lease counts, database state and external effects on a named installed target."),
}

# Each item contains three fully authored wordings for instructions and every option.
questions = {}
def add(key, instructions, **criteria):
    questions[key] = {"instructions": instructions, "criteria": criteria}

add("endpoint_probe", triple(
"For DI-09a, which first added prototype best isolates the technical value of compiler-linked endpoint identity against the centralized exact-route baseline, before evidence supports a larger routing contract?",
"What DI-09a increment should be tested first to measure static endpoint-link benefits relative to the best existing centralized literal-path idiom without presuming capture semantics?",
"Choose the initial DI-09a experiment that most cleanly evaluates checked endpoint references versus factored exact routing, while limiting unsupported additional routing commitments."),
A=triple("Measure only stronger centralized records/builders and protocol tests first; postpone any checked identity prototype.", "Begin by improving application endpoint records/helpers plus HTTP tests; defer compiler-linked identity experiments.", "First trial a strengthened library/tooling baseline with shared endpoint construction and protocol checks, leaving identity checking for later."),
B=triple("Compare a checked exact-path endpoint connecting mount, method, request/response and URL use, without path captures yet.", "Prototype static linkage across exact route declaration, verb, wire cases and URL callers, excluding captured segments initially.", "Test compiler-known identity for literal routes and their method/input/output/URL references before adding parameterized paths."),
C=triple("Prototype checked identity and named captures together, including conversion, encoding and route-ambiguity rules.", "Evaluate identity linkage alongside typed path parameters, with decoding/encoding failures and precedence defined together.", "Build the linked endpoint trial with captured segments from the start and specify their wire conversion, round trips and overlap rules."))

add("form_rows", triple(
"For DI-09b HTML line-item reorder/delete with stable retained input and error identity, which wire representation should the first comparative prototype prioritize against the validated parallel-array baseline?",
"Which candidate merits the first DI-09b comparison when native form line rows can move or disappear and rejected values/errors must remain associated with the correct row?",
"Select a DI-09b row-encoding trial for HTML edits that preserves row/error correspondence through reordering and removal, using checked parallel arrays as the current baseline."),
A=triple("Keep explicit parallel arrays and validate their length/order invariant with stable row keys before domain conversion.", "Use repeated column arrays with explicit row identifiers and checked alignment before constructing domain rows.", "Retain column-wise arrays, carrying row identity and verifying matching lengths and ordering before validation produces values."),
B=triple("Prototype declared keyed form rows with checked row-key/field-path decoding and explicit duplicate/partial-row rules.", "Try an identified-row HTML form codec that validates key/path references and specifies repeated keys and incomplete records.", "Evaluate a row-key-based form representation with checked field paths and defined handling for key collisions and missing row parts."),
C=triple("Use a separate exact JSON action for row records, requiring a browser serialization path rather than treating it as native form decoding.", "Move row submission to an independently declared JSON endpoint with exact codecs and explicit client encoding, not an HTML form decoder.", "Trial complete row objects through a distinct JSON contract whose browser serialization is separately provided from ordinary form submission."))

add("action_mapping", triple(
"For DI-09d, what first increment best targets omitted status/render/swap cases while respecting that conditional DOM target presence remains a runtime concern?",
"Which DI-09d prototype most directly tests prevention of missing response-case behavior without claiming a typed identifier guarantees a mounted DOM target?",
"Choose the next DI-09d comparison aimed at incomplete action outcome handling, with live target existence explicitly outside an ordinary static ID proof."),
A=triple("Improve named application handlers and a narrow status/swap policy, relying on protocol/browser tests for completeness.", "Keep explicit handler mappings with carefully configured swaps and assess missing cases through HTTP and DOM tests.", "Strengthen the existing manual result mapping and limited swap configuration; let external tests detect incomplete coverage."),
B=triple("Add checked mapping of declared action results to real status, rendering and swap policy; retain runtime missing-target outcomes.", "Prototype exhaustive declared result-to-status/render/swap linkage while handling removed targets at runtime.", "Check every action outcome's HTTP code, renderer and swap choice statically, with an explicit dynamic target-absence path."),
C=triple("Prioritize scoped typed target references with runtime absence handling; keep result/status/swap mapping explicit in handlers.", "First type-check target identity within render scopes and report missing live targets, leaving response-case maps as application code.", "Evaluate render-scope target linkage before checked action mappings, retaining runtime absence behavior and explicit status/render/swap handlers."))

add("html_probe", triple(
"For DI-10, which next prototype most cleanly tests earlier invalid-literal diagnostics while preserving existing safe-builder semantics and comparing against factored render helpers?",
"What DI-10 experiment best isolates the benefit of catching static markup mistakes earlier without changing the safety contract of the current helper-based rendering baseline?",
"Choose a DI-10 trial focused on diagnosing known-invalid HTML before execution while retaining the established immutable safe-node and dynamic-check behavior."),
A=triple("Improve helper/library composition and diagnostics only; retain runtime validation of literal builder calls.", "Refine reusable render functions and runtime error reporting, without moving literal structure checks into compilation.", "Extend the factored safe-builder library and its failure messages, keeping static-looking calls validated at runtime."),
B=triple("Check literal invocations of existing builders in the compiler, keeping dynamic validation and existing safe value types.", "Prototype compile-time validation for known builder arguments while preserving runtime checks and safe-node contracts.", "Add static analysis of literal safe-constructor calls without replacing their dynamic checks or immutable representations."),
C=triple("Introduce a checked declarative component representation with explicit inputs/outputs and defined conditional-child analysis.", "Trial compiler-checked component declarations whose input/output contracts and conditional structure rules are specified.", "Prototype a declarative component model with validated boundaries and an explicit account of what conditional children can prove."))

add("browser_profile", triple(
"For DI-11's first Can-authored rich-grid compiler experiment, which capability scope is the smallest technically useful qualification target, without claiming other profiles are covered?",
"Which DI-11 capability profile should the initial Can browser grid prototype qualify to provide useful frontend evidence with a bounded validation surface?",
"Select the first browser-execution scope for a Can-written invoice grid trial that is sufficient to test the requested local interaction while containing qualification work."),
A=triple("Qualify a main-thread profile with shared codecs/validation, DOM/events, Fetch, explicit state/render/disposal and transitive server-capability exclusion.", "Start with browser main-thread data/codec parity, local state, DOM events, rendering, Fetch and cleanup, rejecting all transitive server-only dependencies.", "Limit the initial target to main-thread shared validation/codecs, DOM/event and state/render operations, Fetch and lifecycle, with closed server-capability rejection."),
B=triple("Qualify main-thread and worker profiles together, adding message codecs, worker ownership and termination to the same initial trial.", "Include both DOM-thread execution and workers from the beginning, testing cross-thread encoding, lifetime and stop behavior alongside grid support.", "Make the first qualification encompass main-thread UI plus worker computation, with validated messages, owners and termination semantics."),
C=triple("First qualify a typed foreign-language client bridge to validate shared endpoint/wire contracts, explicitly deferring evidence of Can-authored browser execution.", "Begin with an admitted typed bridge to another browser language as a contract experiment, postponing proof of the Can frontend compiler.", "Use a checked external-language client first to exercise route/data sharing, recording that Can-authored client execution remains unqualified."))

add("offline_minimum", triple(
"For DI-11, which provisional minimum should anchor offline grid evaluation before any durability preference or product promise is selected, while higher contracts remain separate fault-tested comparisons?",
"Choose the initial offline evaluation contract that best bounds the first DI-11 experiment without deciding whether the product should promise reload survival or queued remote writes.",
"What temporary offline baseline should be tested first for DI-11, leaving product durability requirements undecided and retaining independent experiments for stronger persistence?"),
A=triple("Memory draft for the live view with visible unsaved/failed state, identified saves and deliberate retry; no navigation/reload survival claim.", "Retain edits in the current view's memory, expose unsaved/failure status and retry identified operations explicitly, with no persistence across leaving or reload.", "Start with view-lifetime drafts, clear pending/error feedback and intentional retry using mutation identity, making no claim after navigation or reload."),
B=triple("A versioned durable local draft with explicit submit, visible storage failures and identity isolation; no queued remote-effect promise.", "Begin with storage-backed draft restoration plus explicit submission, account/tenant partitioning and surfaced persistence errors, excluding automatic effect queues.", "Use a persistent schema-versioned draft as the baseline, with isolated identities and reported storage faults, while remote submission stays explicit rather than queued."),
C=triple("A durable identified mutation queue with reconciliation, server-supported deduplication and multi-tab/crash/authorization recovery.", "Start from persisted pending operations with stable identities, reconciliation, server deduplication where available and crash, login-expiry and tab coordination.", "Make recoverable queued mutations the minimum, including operation IDs, uncertain-commit reconciliation, supported server deduplication and multi-tab/auth/crash policy."))

add("lifecycle_ownership", triple(
"For DI-11 disposal while an invoice save may already have committed, which ownership strategy best prevents disposed-view updates while keeping uncertain mutation outcomes accountable?",
"Which DI-11 ownership model should be prototyped for removing a view during an in-flight save, balancing local cleanup with explicit tracking of possible remote commitment?",
"Select a lifecycle design for DI-11 save completion after view removal that blocks stale UI updates and preserves responsibility for ambiguous server effects."),
A=triple("Keep saves view-owned; disposal aborts supported local work and writes an explicit reconciliation handoff before releasing mutation tracking.", "Own operations in the view and cancel locally on removal, but transfer unresolved mutation identity to a reconciliation record before dropping the owner.", "Use view-scoped save ownership with supported abort on cleanup and a mandatory explicit handoff of uncertain effects to reconciliation."),
B=triple("Separate view-owned listeners/rendering from application-owned identified saves; dispose UI locally while the application tracks settlement/reconciliation.", "Give DOM/event cleanup to the view and pending mutation ownership to the application so tracking continues after UI disposal until resolution or reconciliation.", "Split local view resources from app-lifetime mutation records; stop view activity on removal while retaining ownership of save completion and ambiguous effects."),
C=triple("Require save settlement or a recorded reconciliation handoff before permitting view disposal; make delayed navigation an explicit prototype behavior.", "Gate removal of the view on resolved saves or an explicit reconciliation transfer, exposing any resulting navigation wait.", "Hold view teardown until pending writes settle or responsibility is handed to reconciliation, and test the declared delay to navigation."))

add("observation_layer", triple(
"For DI-13, which first observation investment most directly validates visible and durable invoice/webhook behavior across the known opaque-response and HTMX gaps?",
"Which DI-13 next step best tests whether the product outcome actually appears in the browser and database, given the current source-assertion boundary?",
"Choose the initial DI-13 evidence improvement most likely to detect the described protocol, DOM and persistence mismatches without overstating source assertions."),
A=triple("Strengthen reusable companion HTTP/browser/live-database scenarios while preserving source fixture contracts and explicitly recording skipped layers.", "Improve shared external protocol, browser and real-database tests, retaining attached fixture semantics and reporting every unexecuted layer.", "First build better companion scenario reuse across HTTP, DOM and live persistence observations, keeping source fixture behavior and prerequisite/skipped-run reporting intact."),
B=triple("Add admitted read-only response projections first, then retain companion browser/database tests for observations projections cannot supply.", "Prioritize safe source-level inspection of HTTP responses while continuing separate browser and database tests for their own outcomes.", "Begin with read-only protocol assertion operations, relying on existing companion DOM/persistence checks beyond the projection boundary."),
C=triple("Prototype a source-authored scenario runner joining protocol/browser/database observations, with explicit fixture identity/isolation and integration prerequisites.", "Create an authored multi-layer runner linking HTTP, browser and live rows, defining queue identity, isolation and required external setup.", "Trial source-defined end-to-end scenarios spanning responses, DOM and database state with specified fixture ownership/FIFO isolation and execution prerequisites."))

add("returning", triple(
"For DI-14a, what is the best next technical comparison before admitting mutation-returning descriptors, given that canonical row and concurrency evidence is currently missing?",
"Which DI-14a experiment should precede a decision on native RETURNING admission when the existing transaction-read baseline has not been measured on the representative flow?",
"Choose the next DI-14a evaluation that would meaningfully separate mutation-returning descriptors from current approaches without mistaking row results for commit certainty."),
A=triple("Implement and measure only the known-value/transaction-read baseline first, deferring any RETURNING prototype until a concrete inadequacy is observed.", "First execute the existing response-or-follow-up-read flow; postpone mutation-returning implementation until it exposes a specific limitation.", "Establish the current known-data or same-transaction read solution experimentally before investing in a RETURNING alternative."),
B=triple("Compare the transaction-read baseline with a bounded PostgreSQL RETURNING prototype on canonical invoice/outbox rows, including zero/multiple rows, constraints and commit_unknown.", "Run equivalent canonical invoice and ledger/outbox mutations using both follow-up reads and constrained PostgreSQL returning descriptors, testing row bounds, constraint faults and uncertain commit.", "Build a paired baseline/native RETURNING experiment for canonical invoice/outbox data under concurrency, checking empty/excess rows, constraints and commit ambiguity in both."),
C=triple("Prototype broad multi-dialect mutation-returning admission first, including dialect-specific cardinality and projection handling before flow measurement.", "Start by specifying and implementing returning mutations across several dialects with explicit result bounds/codecs, then benchmark the product cases.", "Evaluate a general multi-dialect returning-descriptor implementation ahead of invoice/outbox trials, defining each dialect's projection and cardinality behavior."))

add("schema_assurance", triple(
"For DI-14b, which assurance increment should be evaluated first to improve projection/migration drift diagnostics while keeping build reproducibility and deployed-schema claims explicit?",
"Which DI-14b candidate merits the first comparison for earlier schema-drift detection, considering reproducible builds and the separate need to verify deployment state?",
"Select a DI-14b experiment for detecting projection and migration disagreement that accurately bounds both build inputs and production-schema assurance."),
A=triple("Retain descriptor/runtime validation and strengthen migration-linked live-database tests and honest diagnostic documentation before adding build schema checks.", "First improve real-database tests tied to migrations and explain existing descriptor/row errors accurately, leaving compile-time schema agreement absent.", "Use the current static admission/runtime codecs with better migration integration testing and precise failure reporting as the first assurance upgrade."),
B=triple("Prototype a versioned, provenance-checked schema snapshot as deterministic build input with supported-query analysis, freshness and deployment-drift checks.", "Trial reproducible build-time validation against a sourced/versioned schema artifact, explicitly checking supported queries, staleness and deployed agreement.", "Evaluate a deterministic schema snapshot carrying dialect/version/provenance and bounded query analysis, with migration freshness and deployment verification."),
C=triple("Prototype database-connected build checking against a named schema, exposing availability/reproducibility limits and verifying deployment separately.", "Consult an identified live database during builds for projection checks, recording dependence on availability/state and retaining a separate deployed-schema check.", "Test build-time queries against a specifically named live schema, making mutable-input and reachability costs explicit and independently verifying deployment."))

add("shutdown", triple(
"For DI-15a, which next experiment best clarifies bounded service shutdown without promising arbitrary cancellation, lease release or rollback from a timeout?",
"What DI-15a prototype should come first to establish truthful service termination behavior given operation-specific abort support and potentially permanent owners?",
"Choose the next DI-15a comparison that can improve shutdown guarantees while preserving the distinction between timeout, native settlement, cleanup and forced exit."),
A=triple("Inventory and test operation-specific abort/deadline APIs with existing owners plus named supervisor grace/kill; qualify actual effects before a shared cancellation context.", "First verify each operation's cancel/timeout and owner-drain behavior under an identified host shutdown policy, deferring common cancellation propagation.", "Begin with adapter-level cancellation/timeout probes and installed-host grace/kill tests over current ownership, then assess whether a unified context is warranted."),
B=triple("Prototype a cancellation context propagated only through verified supporting adapters, retaining owner drain, host kill limits and reconciliation for uncertain effects.", "Add explicit shared cancel state to operations that have demonstrated support, preserving leases until settlement and separately testing forced exit and ambiguous writes.", "Evaluate cooperative context propagation across proven abortable adapters, keeping actual owner release, supervisor termination and effect reconciliation distinct."),
C=triple("Prioritize worker/process isolation for bounded computation termination with explicit serialization, resource ownership and side-effect recovery protocols.", "Start with isolated workers or processes whose computation can be stopped, defining message codecs, owners and reconciliation of external effects.", "Trial process/worker boundaries first to bound computation lifetime, accepting specified serialization and resource/effect recovery costs."))

# An escape option is present in every question; its prose is also fresh.
none = triple("The supplied evidence does not distinguish these experiments sufficiently; collect a focused missing observation before prioritizing one.", "No listed experiment can yet be prioritized from these facts; obtain the specific absent measurement first.", "Leave the experimental ordering unresolved because the evidence lacks a needed discriminator among these alternatives.")
for q in questions.values():
    q["criteria"]["D"] = none

payloads = []
for i in range(3):
    payload = {"model": "jev-latest", "state": {k: v[i] for k, v in state.items()}, "questions": {}}
    for key, q in questions.items():
        items = list(q["criteria"].items())
        # Rotate display order only; stable keys retain the same substantive meanings.
        items = items[i:] + items[:i]
        payload["questions"][key] = {"type": "choice", "instructions": q["instructions"][i], "criteria": {k:v[i] for k,v in items}}
    payloads.append(payload)
    (OUT / f"request-{i+1}.json").write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n")

# Compare every explanatory leaf at the same semantic path, not only question text.
def leaves(x, path=""):
    if isinstance(x, dict):
        for k,v in x.items():
            yield from leaves(v, path + "/" + k)
    elif isinstance(x, str) and path not in ("/model",) and not path.endswith("/type"):
        yield path, x
maps = [dict(leaves(p)) for p in payloads]
assert maps[0].keys() == maps[1].keys() == maps[2].keys()
assert all(len({m[k] for m in maps}) == 3 for k in maps[0]), "Unrewritten explanatory field"
audit = {
"before_send": True,
"explanatory_paths_checked": len(maps[0]),
"identical_explanatory_paths": [],
"request_sha256": {str(i+1):hashlib.sha256((OUT/f"request-{i+1}.json").read_bytes()).hexdigest() for i in range(3)},
"semantic_review": "Manually compared every triple for the same facts, constraints, question scope and A/B/C/D alternatives. All state paragraphs, instructions and option descriptions were rewritten; only schema/model/option keys and exact technical identifiers remain fixed. Option display order rotates. No prior Jev answer is included. Each question is an independent engineering-experiment choice, not a final product preference or syntax approval.",
"fact_coverage": list(state),
"question_coverage": list(questions),
"limitations": "Paraphrase uniqueness is mechanically checked; semantic equivalence is a reviewer judgment, not proven. Shared authored framing, option sets and classifier correlations remain. Rotation and three fresh calls cannot guarantee bias removal. No probe outcomes beyond the supplied evidence are implied."
}
(OUT/"wording-audit.json").write_text(json.dumps(audit,indent=2)+"\n")
print(json.dumps({"prepared":3,"questions_per_request":len(questions),"explanatory_paths":len(maps[0]),"wording_audit":"passed"}))

if "--send" in sys.argv:
    secret = os.environ["TYPESAFE_API_KEY"]
    for i in range(1,4):
        request_bytes = (OUT/f"request-{i}.json").read_bytes()
        started = datetime.datetime.now(datetime.timezone.utc).isoformat()
        clock_start = time.monotonic()
        request = urllib.request.Request("https://api.typesafe.ai/v1/systemone", data=request_bytes, headers={"Authorization":"Bearer "+secret,"Content-Type":"application/json"})
        try:
            with urllib.request.urlopen(request,timeout=90) as response:
                body,status = response.read(),response.status
                safe_headers = {k:v for k,v in response.headers.items() if k.lower() in {"date","content-type","x-request-id","request-id"}}
        except urllib.error.HTTPError as error:
            body,status,safe_headers = error.read(),error.code,{}
        (OUT/f"response-{i}.json").write_bytes(body)
        parsed = json.loads(body)
        meta = {"started_at":started,"elapsed_seconds":round(time.monotonic()-clock_start,3),"status":status,"endpoint":"https://api.typesafe.ai/v1/systemone","request_sha256":hashlib.sha256(request_bytes).hexdigest(),"response_sha256":hashlib.sha256(body).hexdigest(),"safe_response_headers":safe_headers,"requested_model":"jev-latest","returned_model":parsed.get("model"),"usage":parsed.get("usage"),"fresh_call":True}
        (OUT/f"response-{i}.metadata.json").write_text(json.dumps(meta,indent=2)+"\n")
        print(json.dumps({"request":i,"status":status,"model":parsed.get("model"),"answers":parsed.get("answers"),"usage":parsed.get("usage")}),flush=True)
        if status != 200:
            raise SystemExit("Unsuccessful call saved; no silent retry")
