package distribution

import (
	"bytes"
	"crypto/sha512"
	"encoding/base64"
	"os"
	"testing"
)

func TestGuardAssetPinsGeneratedBytes(t *testing.T) {
	script, err := GuardAsset()
	if err != nil {
		t.Fatal(err)
	}
	onDisk, err := os.ReadFile("assets/htmx-guard.js")
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(script, onDisk) {
		t.Fatal("guard asset differs from the checked-in generated bytes")
	}
	if Hash(script) != "4d7098c2660af8affaf4693c38f7b91ede6632193f7a1b2bc45731ed7d603da0" {
		t.Fatal("unexpected guard SHA-256")
	}
	sum := sha512.Sum384(script)
	if "sha384-"+base64.StdEncoding.EncodeToString(sum[:]) != "sha384-mr/IRfJgLjok38ftBi21o/T8c9cnFZrvEKtiwVjIOFAlo3Z7h1rGMYsWvebDJ8kG" {
		t.Fatal("unexpected guard integrity")
	}
	if len(script) != 9507 {
		t.Fatalf("unexpected guard size %d", len(script))
	}
}

func TestGuardAssetInventoryIsClosed(t *testing.T) {
	if err := VerifyHTMX(".."); err != nil {
		t.Fatal(err)
	}
	entries, err := os.ReadDir("assets")
	if err != nil {
		t.Fatal(err)
	}
	if len(entries) != 3 {
		t.Fatalf("guard inventory holds %d files, want 3", len(entries))
	}
}
