package distribution

import (
	"bytes"
	"crypto/sha512"
	"encoding/base64"
	"os"
	"testing"
)

func TestGuardAssetPinsGeneratedBytes(t *testing.T) {
	script, err := GuardAsset()
	if err != nil {
		t.Fatal(err)
	}
	onDisk, err := os.ReadFile("assets/htmx-guard.js")
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(script, onDisk) {
		t.Fatal("guard asset differs from the checked-in generated bytes")
	}
	if Hash(script) != "a48acdeb5385611cd6e318a0557e745e1c2a2541a5f97ae0793f345b912331ac" {
		t.Fatal("unexpected guard SHA-256")
	}
	sum := sha512.Sum384(script)
	if "sha384-"+base64.StdEncoding.EncodeToString(sum[:]) != "sha384-C5A6uJ5FDnfm4n0j9TRlnVP+OIz//4VRs7OcvEYgUzCRevIwXmktURVNyPxYvOpQ" {
		t.Fatal("unexpected guard integrity")
	}
	if len(script) != 10735 {
		t.Fatalf("unexpected guard size %d", len(script))
	}
}

func TestGuardAssetInventoryIsClosed(t *testing.T) {
	if err := VerifyHTMX(".."); err != nil {
		t.Fatal(err)
	}
	entries, err := os.ReadDir("assets")
	if err != nil {
		t.Fatal(err)
	}
	if len(entries) != 3 {
		t.Fatalf("guard inventory holds %d files, want 3", len(entries))
	}
}
