// K05: independent C adapter witness hooked to the actual generated path.
//
// A C adapter was ACTUALLY invoked when the witness itself drove the call
// through the real supervisor the generated entries use, with the verified
// generated bytes bound by digest. There is no public begin/complete claim:
// invocations open only inside the hook, and complete only from the observed
// supervisor settlement.
//
// The three boundaries (all read-only; owned by K04 and R):
//   - artifact bytes: exact generated module sources, verified seam-clean by
//     the real K04 checker (checkModule from ./c-ingress.ts) against the real
//     K04 manifest, and bound by artifact_digest = sha256(path\0kind\0source);
//   - executable hook: the real runEntry supervisor (runtime/entry.ts:61) with
//     a counting stub reporter; exit 0/1 observes completed/failed;
//   - assertion-case hook: the real runAssertion case supervisor
//     (runtime/assert/runner.ts:146, no progress sink so no timer), which is
//     the exact downstream call the generated assertion path makes
//     (runner.ts:264); passed observes completed, "expected evaluation
//     failed" observes rejected, any other reason observes failed.
//
// Detectable negatives:
//   - bypass: a directly called (unwitnessed) adapter produces no facts; an
//     uninstrumented digest, a fabricated token, or a token/id/digest triple
//     that was never minted together rejects with not-found;
//   - wrong export/signature: an export outside the closed adapter vocabulary
//     ($canMain/$canCase), an export/kind mismatch, a seam-dirty or stale
//     artifact, or a signature that differs from the manifest entry rejects;
//   - eager read: observing a pending (not yet settled) invocation rejects;
//   - forged completion: there is no public complete to forge; unknown
//     invocation ids reject at observe time.
//
// Returned facts are inert counter/identity data only (counts, ids, digests,
// tags; never raw values, reporter content, or adapter callables) and pass
// checkFactsInert.
//
// Residual (QN2, live host): the adapter callable is supplied by the caller —
// K01 forbids eval and loading generated modules is host-dependent — so the
// witness proves the supplied adapter was actually invoked through the real
// supervisor with the verified artifact digest bound, not that the callable
// is the generated bytes. Assertion-root entries (runAssertionRoot) deliver
// over host stdio unconditionally (runner.ts:220-224,251-261,270-279) and are
// not hookable in bounded local controls.
//
// Bounded local mechanics only: no I/O, timers, transports, services, or
// live runtimes. The stub reporter counts lines without storing them.

import { createHash, randomBytes } from "node:crypto";
import { checkFactsInert, NativeSchemaError } from "./schema.ts";
import { checkModule, parseModule, type IngressManifest } from "./c-ingress.ts";
import { runEntry } from "../../../../runtime/entry.ts";
import { runAssertion, type AssertionCase } from "../../../../runtime/assert/runner.ts";
import type { Completion } from "../../../../runtime/completion.ts";

export const NATIVE_C_WITNESS_SCHEMA_VERSION = "2" as const;

// ---------------------------------------------------------------------------
// Closed vocabularies
// ---------------------------------------------------------------------------

// Adapter exports the emitter produces (compiler/internal/emit/program_entry.go):
// $canMain is the executable entry's program edge (there :136), $canCase is the
// assertion-case module export (there :124). runEntry/runAssertionRoot are the
// hook mechanism (the real supervisors invoked below), not witness subjects.
export const C_WITNESS_EXPORTS = ["$canMain", "$canCase"] as const;
export type CWitnessExport = (typeof C_WITNESS_EXPORTS)[number];

export const C_WITNESS_ARTIFACT_KINDS = ["executable", "assertion_case"] as const;
export type CWitnessArtifactKind = (typeof C_WITNESS_ARTIFACT_KINDS)[number];

// Observed terminal outcomes. Executable runs observe completed/failed only:
// the supervisor reports binary status, so rejected is unobservable there
// (pinned as missing evidence). Case runs observe all three.
export const C_WITNESS_COMPLETIONS = ["completed", "rejected", "failed"] as const;
export type CWitnessCompletion = (typeof C_WITNESS_COMPLETIONS)[number];

const CASE_REASONS = [
  "expected evaluation failed",
  "outcome mismatch",
  "harness violation",
] as const;

// The Main signature mirrors runtime/entry.ts:11 exactly.
export type WitnessMain = (args: readonly string[]) => Completion<void> | Promise<Completion<void>>;

function isWitnessExport(value: unknown): value is CWitnessExport {
  return typeof value === "string" && (C_WITNESS_EXPORTS as readonly string[]).includes(value);
}

function isArtifactKind(value: unknown): value is CWitnessArtifactKind {
  return (
    typeof value === "string" && (C_WITNESS_ARTIFACT_KINDS as readonly string[]).includes(value)
  );
}

function kindOfExport(exportName: CWitnessExport): CWitnessArtifactKind {
  return exportName === "$canMain" ? "executable" : "assertion_case";
}

// ---------------------------------------------------------------------------
// Manifest view: full K04 ingress manifest plus the signatures table
// ---------------------------------------------------------------------------

export type CWitnessManifestView = IngressManifest &
  Readonly<{
    signatures: Readonly<Record<string, string>>;
  }>;

function checkBoundedString(value: unknown, what: string, max: number): string {
  if (typeof value !== "string" || value.length === 0 || value.length > max) {
    throw new NativeSchemaError("rejected", "invalid-request", `${what} must be a bounded string`);
  }
  return value;
}

function checkStringArray(
  value: unknown,
  what: string,
  maxItems: number,
  maxItem: number,
  minItems = 1,
): readonly string[] {
  if (!Array.isArray(value) || value.length < minItems || value.length > maxItems) {
    throw new NativeSchemaError("rejected", "invalid-request", `${what} must be a bounded array`);
  }
  for (const item of value) {
    checkBoundedString(item, `${what} entry`, maxItem);
  }
  return value as readonly string[];
}

function checkRecord(value: unknown, what: string): Record<string, unknown> {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    throw new NativeSchemaError("rejected", "invalid-request", `${what} must be an object`);
  }
  return value as Record<string, unknown>;
}

function checkFixedEdge(value: unknown, what: string): void {
  const record = checkRecord(value, what);
  const names = checkRecord(record["names"], `${what} names`);
  const keys = Object.keys(names);
  if (keys.length === 0 || keys.length > 32) {
    throw new NativeSchemaError("rejected", "invalid-request", `${what} needs bounded names`);
  }
  for (const [key, local] of Object.entries(names)) {
    checkBoundedString(key, `${what} name`, 256);
    checkBoundedString(local, `${what} alias`, 256);
  }
  for (const key of ["runtime_module", "resolved"] as const) {
    if (record[key] !== undefined) {
      checkBoundedString(record[key], `${what} ${key}`, 256);
    }
  }
  if (record["type_only"] !== undefined && typeof record["type_only"] !== "boolean") {
    throw new NativeSchemaError("rejected", "invalid-request", `${what} type_only must be boolean`);
  }
}

function checkIngressManifest(value: unknown): CWitnessManifestView {
  const record = checkRecord(value, "witness manifest");
  checkBoundedString(record["local_prefix"], "manifest local_prefix", 64);
  checkStringArray(record["allowed_program_roots"], "manifest allowed_program_roots", 16, 128);
  checkStringArray(record["runtime_modules"], "manifest runtime_modules", 64, 256);
  const entries = checkRecord(record["entries"], "manifest entries");
  const executable = checkRecord(entries["executable"], "manifest executable entry");
  checkBoundedString(executable["path"], "manifest executable path", 256);
  const bodyPattern = checkBoundedString(executable["body_pattern"], "manifest body_pattern", 2048);
  try {
    new RegExp(bodyPattern);
  } catch {
    throw new NativeSchemaError(
      "rejected",
      "invalid-request",
      "manifest body_pattern does not compile",
    );
  }
  const fixedEdges = executable["fixed_edges"];
  if (!Array.isArray(fixedEdges) || fixedEdges.length > 16) {
    throw new NativeSchemaError(
      "rejected",
      "invalid-request",
      "manifest fixed_edges must be bound",
    );
  }
  for (const edge of fixedEdges) {
    checkFixedEdge(edge, "manifest fixed edge");
  }
  const assertionRoot = checkRecord(entries["assertion_root"], "manifest assertion_root entry");
  checkBoundedString(assertionRoot["path"], "manifest assertion_root path", 256);
  const rootPattern = checkBoundedString(
    assertionRoot["body_pattern"],
    "manifest assertion body_pattern",
    2048,
  );
  try {
    new RegExp(rootPattern);
  } catch {
    throw new NativeSchemaError(
      "rejected",
      "invalid-request",
      "manifest assertion body_pattern does not compile",
    );
  }
  const rootEdges = assertionRoot["fixed_edges"];
  if (!Array.isArray(rootEdges) || rootEdges.length > 16) {
    throw new NativeSchemaError(
      "rejected",
      "invalid-request",
      "manifest assertion fixed_edges must be bound",
    );
  }
  for (const edge of rootEdges) {
    checkFixedEdge(edge, "manifest assertion fixed edge");
  }
  const assertionCase = checkRecord(entries["assertion_case"], "manifest assertion_case entry");
  const runtimeEdges = assertionCase["required_runtime_edges"];
  if (!Array.isArray(runtimeEdges) || runtimeEdges.length > 32) {
    throw new NativeSchemaError(
      "rejected",
      "invalid-request",
      "manifest required_runtime_edges must be bound",
    );
  }
  for (const edge of runtimeEdges) {
    const edgeRecord = checkRecord(edge, "manifest runtime edge");
    checkBoundedString(edgeRecord["runtime_module"], "manifest runtime edge module", 256);
    if (typeof edgeRecord["type_only"] !== "boolean") {
      throw new NativeSchemaError(
        "rejected",
        "invalid-request",
        "manifest runtime edge type_only must be boolean",
      );
    }
  }
  const resolvedEdges = assertionCase["required_resolved_edges"];
  if (!Array.isArray(resolvedEdges) || resolvedEdges.length > 16) {
    throw new NativeSchemaError(
      "rejected",
      "invalid-request",
      "manifest required_resolved_edges must be bound",
    );
  }
  for (const edge of resolvedEdges) {
    const edgeRecord = checkRecord(edge, "manifest resolved edge");
    checkBoundedString(edgeRecord["resolved"], "manifest resolved edge target", 256);
    if (typeof edgeRecord["type_only"] !== "boolean") {
      throw new NativeSchemaError(
        "rejected",
        "invalid-request",
        "manifest resolved edge type_only must be boolean",
      );
    }
  }
  checkStringArray(assertionCase["exports"], "manifest assertion_case exports", 16, 128);
  const signatures = checkRecord(record["signatures"], "manifest signatures");
  for (const [key, entry] of Object.entries(signatures)) {
    checkBoundedString(key, "manifest signature name", 128);
    if (typeof entry !== "string" || entry.length === 0 || entry.length > 512) {
      throw new NativeSchemaError(
        "rejected",
        "invalid-request",
        `invalid manifest signature for ${key}`,
      );
    }
  }
  return value as CWitnessManifestView;
}

// ---------------------------------------------------------------------------
// Bounded caps and id shapes
// ---------------------------------------------------------------------------

export const MAX_WITNESS_ARTIFACTS = 8;
export const MAX_WITNESS_INVOCATIONS = 32;
// A committed real assertion-case module is 115,057 bytes; 1 MiB bounds real
// artifacts with headroom without admitting unbounded sources.
export const MAX_ARTIFACT_BYTES = 1048576;
export const MAX_WITNESS_ARGV = 8;
export const MAX_WITNESS_ARGV_BYTES = 256;
export const MAX_WITNESS_PATH = 256;

const ARTIFACT_PATTERN = /^cartifact[1-9][0-9]*$/;
const INVOCATION_PATTERN = /^cinv[1-9][0-9]*$/;
const TOKEN_PATTERN = /^cwt:[1-9][0-9]*:[0-9a-f]{16}$/;
const DIGEST_PATTERN = /^sha256:[0-9a-f]{64}$/;

// ---------------------------------------------------------------------------
// Digests (local, deterministic; independent of the K03 seal)
// ---------------------------------------------------------------------------

function canonicalize(value: unknown): string {
  if (value === null) return "null";
  if (typeof value === "number" || typeof value === "string" || typeof value === "boolean") {
    return JSON.stringify(value) as string;
  }
  if (Array.isArray(value)) {
    return `[${value.map((item) => canonicalize(item)).join(",")}]`;
  }
  if (typeof value === "object") {
    const record = value as Record<string, unknown>;
    const keys = Object.keys(record).sort();
    const body = keys.map((key) => `${JSON.stringify(key)}:${canonicalize(record[key])}`).join(",");
    return `{${body}}`;
  }
  throw new NativeSchemaError("failed", "native-io", "witness input carries a non-inert value");
}

export function digestBinding(value: unknown): string {
  return `sha256:${createHash("sha256").update(canonicalize(value), "utf8").digest("hex")}`;
}

// Flat-preimage artifact digest so controls can recompute it independently
// with three lines of node:crypto instead of duplicating the canonicalizer.
export function digestArtifact(path: string, kind: CWitnessArtifactKind, source: string): string {
  return `sha256:${createHash("sha256").update(`${path}\0${kind}\0${source}`, "utf8").digest("hex")}`;
}

// ---------------------------------------------------------------------------
// Artifact shape and fact shapes (all inert data)
// ---------------------------------------------------------------------------

export type GeneratedArtifact = Readonly<{
  path: string;
  kind: CWitnessArtifactKind;
  source: string;
}>;

function checkArtifactShape(value: unknown): GeneratedArtifact {
  const record = checkRecord(value, "witness artifact");
  if (!isArtifactKind(record["kind"])) {
    throw new NativeSchemaError(
      "rejected",
      "unsupported-capability",
      `unknown artifact kind: ${String(record["kind"])}`,
    );
  }
  if (typeof record["path"] !== "string" || record["path"].length === 0) {
    throw new NativeSchemaError("rejected", "invalid-request", "artifact path must be a string");
  }
  if (record["path"].length > MAX_WITNESS_PATH) {
    throw new NativeSchemaError("rejected", "invalid-request", "artifact path exceeds the bound");
  }
  if (typeof record["source"] !== "string" || record["source"].length === 0) {
    throw new NativeSchemaError("rejected", "invalid-request", "artifact source must be a string");
  }
  if (record["source"].length > MAX_ARTIFACT_BYTES) {
    throw new NativeSchemaError("rejected", "resource-limit", "artifact source exceeds the bound");
  }
  return value as GeneratedArtifact;
}

export type WitnessArtifactFacts = Readonly<{
  artifact: string;
  adapter_export: CWitnessExport;
  adapter_binding: string;
  artifact_digest: string;
  token: string;
  seq: number;
}>;

export type WitnessExecutableDetail = Readonly<{
  kind: "executable";
  exit_code: 0 | 1;
  report_lines: number;
}>;

export type WitnessCaseDetail = Readonly<{
  kind: "assertion_case";
  passed: boolean;
  reason: string | null;
}>;

export type WitnessCompletionFacts = Readonly<{
  artifact: string;
  invocation: string;
  completion: CWitnessCompletion;
  binding: string;
}> &
  (WitnessExecutableDetail | WitnessCaseDetail);

export type WitnessObservationFacts = Readonly<{
  artifact: string;
  adapter_export: CWitnessExport;
  adapter_binding: string;
  artifact_digest: string;
  invocation: string;
  completion: CWitnessCompletion;
  binding: string;
}> &
  (WitnessExecutableDetail | WitnessCaseDetail);

export type WitnessCounters = Readonly<{
  artifacts: number;
  invocations: number;
  completions: number;
  observations: number;
  rejected: number;
}>;

// ---------------------------------------------------------------------------
// Witness: verified artifact bytes plus hook-driven invocation
// ---------------------------------------------------------------------------

type ArtifactRecord = {
  artifactId: string;
  token: string;
  exportName: CWitnessExport;
  signature: string;
  kind: CWitnessArtifactKind;
  path: string;
  digest: string;
  binding: string;
  seq: number;
};

type InvocationRecord = {
  invocationId: string;
  artifactId: string;
  completion: CWitnessCompletion | null;
  detail: WitnessExecutableDetail | WitnessCaseDetail | null;
  binding: string | null;
};

export class CAdapterWitness {
  private readonly nonce: string;
  private readonly artifacts = new Map<string, ArtifactRecord>();
  private readonly byToken = new Map<string, ArtifactRecord>();
  private readonly invocations = new Map<string, InvocationRecord>();
  private artifactCounter = 0;
  private invocationCounter = 0;
  private completionCount = 0;
  private observationCount = 0;
  private rejectedCount = 0;

  constructor() {
    this.nonce = randomBytes(8).toString("hex");
  }

  counters(): WitnessCounters {
    return Object.freeze({
      artifacts: this.artifacts.size,
      invocations: this.invocations.size,
      completions: this.completionCount,
      observations: this.observationCount,
      rejected: this.rejectedCount,
    });
  }

  // Instrument one generated adapter artifact: the claimed export must be in
  // the closed adapter vocabulary for the artifact kind, the claimed
  // signature must exactly match the manifest entry, and the artifact bytes
  // must be seam-clean under the real K04 checker. Returns the artifact id,
  // its adapter binding, its digest, and its witness token; only minted
  // token/id/digest triples ever verify.
  instrument(
    artifact: unknown,
    exportName: unknown,
    signature: unknown,
    manifest: unknown,
  ): WitnessArtifactFacts {
    let checked: CWitnessManifestView;
    let shape: GeneratedArtifact;
    try {
      checked = checkIngressManifest(manifest);
    } catch (error) {
      throw this.counted(error);
    }
    try {
      shape = checkArtifactShape(artifact);
    } catch (error) {
      throw this.counted(error);
    }
    if (!isWitnessExport(exportName)) {
      throw this.reject("unsupported-capability", `unknown witness export: ${String(exportName)}`);
    }
    if (kindOfExport(exportName) !== shape.kind) {
      throw this.reject(
        "unsupported-capability",
        `export ${exportName} needs ${kindOfExport(exportName)} artifacts`,
      );
    }
    if (typeof signature !== "string" || signature.length === 0 || signature.length > 512) {
      throw this.reject("invalid-request", "witness signature must be a bounded string");
    }
    const authoritative = checked.signatures[exportName];
    if (authoritative === undefined) {
      throw this.reject(
        "unsupported-capability",
        `export ${exportName} is not in the ingress manifest`,
      );
    }
    if (signature !== authoritative) {
      throw this.reject("changed-input", `signature for ${exportName} differs from the manifest`);
    }
    const problems = checkModule(checked, shape.kind, shape.path, shape.source);
    if (problems.length > 0) {
      const first = (problems[0] as string).slice(0, 256);
      throw this.reject("changed-input", `artifact fails the ingress seam: ${first}`);
    }
    const adapterBinding = this.adapterBinding(shape, exportName);
    if (this.artifacts.size >= MAX_WITNESS_ARTIFACTS) {
      throw this.reject("resource-limit", "witness artifact cap reached");
    }
    this.artifactCounter += 1;
    const artifactId = `cartifact${this.artifactCounter}`;
    const token = this.mintToken(this.artifactCounter);
    const digest = digestArtifact(shape.path, shape.kind, shape.source);
    const record: ArtifactRecord = {
      artifactId,
      token,
      exportName,
      signature,
      kind: shape.kind,
      path: shape.path,
      digest,
      binding: adapterBinding,
      seq: this.artifactCounter,
    };
    this.artifacts.set(artifactId, record);
    this.byToken.set(token, record);
    const facts = Object.freeze({
      artifact: artifactId,
      adapter_export: exportName,
      adapter_binding: adapterBinding,
      artifact_digest: digest,
      token,
      seq: this.artifactCounter,
    });
    checkFactsInert(facts, "witness artifact facts");
    return facts;
  }

  // Invoke an executable adapter through the real runEntry supervisor: the
  // witness opens the invocation, calls runEntry with the supplied adapter
  // and a counting stub reporter, and completes from the observed exit code.
  // The invocation record is created before the first await so the pending
  // invocation is observable (and eagerly unreadable) while the supervisor
  // runs. Validation failures mint no invocation.
  async invokeExecutable(
    token: unknown,
    artifactId: unknown,
    artifactDigest: unknown,
    adapter: unknown,
    argv: unknown = [],
  ): Promise<WitnessCompletionFacts> {
    const record = this.requireBinding(token, artifactId, artifactDigest);
    if (record.kind !== "executable") {
      throw this.reject(
        "unsupported-capability",
        `artifact ${record.artifactId} binds ${record.exportName}; use invokeCase`,
      );
    }
    if (typeof adapter !== "function") {
      throw this.reject("invalid-request", "executable adapter must be a function");
    }
    const args = this.checkArgv(argv);
    if (this.invocations.size >= MAX_WITNESS_INVOCATIONS) {
      throw this.reject("resource-limit", "witness invocation cap reached");
    }
    this.invocationCounter += 1;
    const invocationId = `cinv${this.invocationCounter}`;
    const invocation: InvocationRecord = {
      invocationId,
      artifactId: record.artifactId,
      completion: null,
      detail: null,
      binding: null,
    };
    this.invocations.set(invocationId, invocation);
    let reportLines = 0;
    let exitCode: 0 | 1;
    try {
      exitCode = await runEntry(
        () => {},
        adapter as WitnessMain,
        args,
        () => {
          reportLines += 1;
        },
      );
    } catch {
      // The supervisor never settles its own throw into an exit code, so the
      // invocation stays honestly pending: a later observe still rejects as
      // unbound. Unreachable against the current supervisor, which settles
      // initialize/main/report failures into 0/1 internally.
      throw this.counted(
        new NativeSchemaError("failed", "native-io", "supervisor throw left facts unbound"),
      );
    }
    if (exitCode !== 0 && exitCode !== 1) {
      throw this.counted(
        new NativeSchemaError("failed", "native-io", "supervisor returned an unknown status"),
      );
    }
    const completion: CWitnessCompletion = exitCode === 0 ? "completed" : "failed";
    const detail: WitnessExecutableDetail = Object.freeze({
      kind: "executable",
      exit_code: exitCode,
      report_lines: reportLines,
    });
    const binding = digestBinding({
      schema_version: NATIVE_C_WITNESS_SCHEMA_VERSION,
      hook: "runtime/entry.ts runEntry",
      artifact: record.artifactId,
      adapter_export: record.exportName,
      adapter_binding: record.binding,
      artifact_digest: record.digest,
      signature: record.signature,
      token: record.token,
      invocation: invocationId,
      completion,
      exit_code: exitCode,
      report_lines: reportLines,
    });
    invocation.completion = completion;
    invocation.detail = detail;
    invocation.binding = binding;
    this.completionCount += 1;
    const facts = Object.freeze({
      artifact: record.artifactId,
      invocation: invocationId,
      completion,
      binding,
      ...detail,
    });
    checkFactsInert(facts, "witness completion facts");
    return facts as WitnessCompletionFacts;
  }

  // Invoke an assertion-case adapter through the real runAssertion supervisor
  // (no progress sink, so no timer): the witness opens the invocation, runs
  // the supplied case, and completes from the observed report. The case root
  // is inert data; actual/expected receive the real supervisor-built context.
  async invokeCase(
    token: unknown,
    artifactId: unknown,
    artifactDigest: unknown,
    testCase: unknown,
  ): Promise<WitnessCompletionFacts> {
    const record = this.requireBinding(token, artifactId, artifactDigest);
    if (record.kind !== "assertion_case") {
      throw this.reject(
        "unsupported-capability",
        `artifact ${record.artifactId} binds ${record.exportName}; use invokeExecutable`,
      );
    }
    const checked = this.checkCase(testCase);
    if (this.invocations.size >= MAX_WITNESS_INVOCATIONS) {
      throw this.reject("resource-limit", "witness invocation cap reached");
    }
    this.invocationCounter += 1;
    const invocationId = `cinv${this.invocationCounter}`;
    const invocation: InvocationRecord = {
      invocationId,
      artifactId: record.artifactId,
      completion: null,
      detail: null,
      binding: null,
    };
    this.invocations.set(invocationId, invocation);
    let report: Awaited<ReturnType<typeof runAssertion>>;
    try {
      report = await runAssertion(checked);
    } catch {
      throw this.counted(
        new NativeSchemaError("failed", "native-io", "supervisor throw left facts unbound"),
      );
    }
    const passed = (report as { passed: unknown }).passed;
    if (typeof passed !== "boolean") {
      throw this.counted(
        new NativeSchemaError("failed", "native-io", "supervisor report has no verdict"),
      );
    }
    const rawReason = passed ? null : (report as { reason: unknown }).reason;
    if (rawReason !== null && typeof rawReason !== "string") {
      throw this.counted(
        new NativeSchemaError("failed", "native-io", "supervisor report has no reason"),
      );
    }
    if (rawReason !== null && !(CASE_REASONS as readonly string[]).includes(rawReason as string)) {
      throw this.counted(
        new NativeSchemaError("failed", "native-io", "supervisor reported an unknown reason"),
      );
    }
    const reason = rawReason as string | null;
    const completion: CWitnessCompletion =
      passed === true
        ? "completed"
        : reason === "expected evaluation failed"
          ? "rejected"
          : "failed";
    const detail: WitnessCaseDetail = Object.freeze({
      kind: "assertion_case",
      passed,
      reason,
    });
    const binding = digestBinding({
      schema_version: NATIVE_C_WITNESS_SCHEMA_VERSION,
      hook: "runtime/assert/runner.ts runAssertion",
      artifact: record.artifactId,
      adapter_export: record.exportName,
      adapter_binding: record.binding,
      artifact_digest: record.digest,
      signature: record.signature,
      token: record.token,
      invocation: invocationId,
      completion,
      passed,
      reason,
    });
    invocation.completion = completion;
    invocation.detail = detail;
    invocation.binding = binding;
    this.completionCount += 1;
    const facts = Object.freeze({
      artifact: record.artifactId,
      invocation: invocationId,
      completion,
      binding,
      ...detail,
    });
    checkFactsInert(facts, "witness completion facts");
    return facts as WitnessCompletionFacts;
  }

  // Observe the inert facts bound to one invocation. The invocation must be
  // complete: reading a pending invocation rejects as an eager (unbound)
  // read, and reading an unknown invocation rejects as forged.
  observe(
    token: unknown,
    artifactId: unknown,
    artifactDigest: unknown,
    invocationId: unknown,
  ): WitnessObservationFacts {
    const record = this.requireBinding(token, artifactId, artifactDigest);
    if (typeof invocationId !== "string" || !INVOCATION_PATTERN.test(invocationId)) {
      throw this.reject("stale-handle", "observation names no witnessed invocation");
    }
    const invocation = this.invocations.get(invocationId);
    if (invocation === undefined || invocation.artifactId !== record.artifactId) {
      throw this.reject("stale-handle", "observation has no matching witnessed invocation");
    }
    if (
      invocation.completion === null ||
      invocation.binding === null ||
      invocation.detail === null
    ) {
      throw this.reject("permission", "invocation is not complete; facts are unbound");
    }
    this.observationCount += 1;
    const facts = Object.freeze({
      artifact: record.artifactId,
      adapter_export: record.exportName,
      adapter_binding: record.binding,
      artifact_digest: record.digest,
      invocation: invocationId,
      completion: invocation.completion,
      binding: invocation.binding,
      ...invocation.detail,
    });
    checkFactsInert(facts, "witness observation facts");
    return facts as WitnessObservationFacts;
  }

  // Derive the adapter binding from the parsed seam-clean module: the $canMain
  // import edge (exported name plus specifier) for executable entries, the
  // $canCase export for assertion cases. checkModule already enforced the
  // single-edge/exact-export shape; a scan mismatch fails closed.
  private adapterBinding(shape: GeneratedArtifact, exportName: CWitnessExport): string {
    const parsed = parseModule(shape.source);
    if (exportName === "$canCase") {
      if (!parsed.exports.includes("$canCase")) {
        throw this.counted(
          new NativeSchemaError("failed", "native-io", "seam-clean case has no $canCase export"),
        );
      }
      return "$canCase";
    }
    const edges = parsed.imports.filter((edge) =>
      edge.names.some((name) => name.local === "$canMain"),
    );
    if (edges.length !== 1) {
      throw this.counted(
        new NativeSchemaError(
          "failed",
          "native-io",
          "seam-clean entry has no single $canMain edge",
        ),
      );
    }
    const edge = edges[0] as (typeof edges)[number];
    const names = edge.names.filter((name) => name.local === "$canMain");
    if (names.length !== 1) {
      throw this.counted(
        new NativeSchemaError("failed", "native-io", "seam-clean entry binds $canMain twice"),
      );
    }
    return `${(names[0] as (typeof names)[number]).exported} from ${edge.specifier}`;
  }

  private checkArgv(argv: unknown): readonly string[] {
    if (!Array.isArray(argv)) {
      throw this.reject("invalid-request", "adapter argv must be an array");
    }
    if (argv.length > MAX_WITNESS_ARGV) {
      throw this.reject("resource-limit", "adapter argv exceeds the entry cap");
    }
    for (const entry of argv) {
      if (typeof entry !== "string" || entry.length > MAX_WITNESS_ARGV_BYTES) {
        throw this.reject("invalid-request", "adapter argv must be bounded strings");
      }
    }
    return Object.freeze([...argv]) as readonly string[];
  }

  private checkCase(testCase: unknown): AssertionCase {
    let record: Record<string, unknown>;
    let root: Record<string, unknown>;
    try {
      record = checkRecord(testCase, "witness case");
      root = checkRecord(record["root"], "witness case root");
    } catch (error) {
      throw this.counted(error);
    }
    for (const key of ["package", "declaration", "name"] as const) {
      const value = root[key];
      if (typeof value !== "string" || value.length === 0 || value.length > 256) {
        throw this.reject("invalid-request", `witness case root needs a bounded ${key}`);
      }
    }
    const links = root["links"];
    if (links !== undefined) {
      if (!Array.isArray(links) || links.length > 8) {
        throw this.reject("invalid-request", "witness case root links must be bounded");
      }
      for (const link of links) {
        if (typeof link !== "string" || link.length === 0 || link.length > 256) {
          throw this.reject("invalid-request", "witness case root links must be bounded strings");
        }
      }
      // The real supervisor rejects duplicate links too
      // (runtime/assert/context.ts assertionContext); fail closed here with
      // invalid-request instead of stranding a pending invocation.
      if (new Set(links).size !== links.length) {
        throw this.reject("invalid-request", "witness case root links must be unique");
      }
    }
    if (typeof record["actual"] !== "function") {
      throw this.reject("invalid-request", "witness case needs an actual function");
    }
    if (typeof record["expected"] !== "function") {
      throw this.reject("invalid-request", "witness case needs an expected function");
    }
    return Object.freeze({
      root: Object.freeze({
        package: root["package"] as string,
        declaration: root["declaration"] as string,
        name: root["name"] as string,
        ...(links === undefined ? {} : { links: Object.freeze([...(links as string[])]) }),
      }),
      actual: record["actual"] as AssertionCase["actual"],
      expected: record["expected"] as AssertionCase["expected"],
    });
  }

  private mintToken(seq: number): string {
    const digest = createHash("sha256").update(`${this.nonce}:${seq}`, "utf8").digest("hex");
    return `cwt:${seq}:${digest.slice(0, 16)}`;
  }

  // Verify the (token, artifact, digest) binding. Unknown tokens, malformed
  // tokens, unknown artifacts, uninstrumented digests, and mismatched triples
  // all reject: none of them proves a witnessed generated-path call.
  private requireBinding(
    token: unknown,
    artifactId: unknown,
    artifactDigest: unknown,
  ): ArtifactRecord {
    if (typeof token !== "string" || !TOKEN_PATTERN.test(token)) {
      throw this.reject("not-found", "no instrumented artifact for this token");
    }
    if (typeof artifactId !== "string" || !ARTIFACT_PATTERN.test(artifactId)) {
      throw this.reject("not-found", "no instrumented artifact for this id");
    }
    if (typeof artifactDigest !== "string" || !DIGEST_PATTERN.test(artifactDigest)) {
      throw this.reject("not-found", "no instrumented artifact for this digest");
    }
    const record = this.byToken.get(token);
    if (
      record === undefined ||
      record.artifactId !== artifactId ||
      record.digest !== artifactDigest
    ) {
      throw this.reject("not-found", "token names no witness-bound artifact");
    }
    return record;
  }

  private counted(error: unknown): NativeSchemaError {
    this.rejectedCount += 1;
    if (error instanceof NativeSchemaError) {
      return error;
    }
    return new NativeSchemaError("rejected", "invalid-request", "witness input failed validation");
  }

  private reject(
    kind:
      | "invalid-request"
      | "unsupported-capability"
      | "changed-input"
      | "not-found"
      | "permission"
      | "stale-handle"
      | "resource-limit",
    message: string,
  ): NativeSchemaError {
    this.rejectedCount += 1;
    return new NativeSchemaError("rejected", kind, message);
  }
}
