// K06 bounded self-check: late native occurrence and lease facts.
//
// Run with: bun tools/runtime/test-services/native-values/late-check.ts
// Local controls only. No services, transports, timers, or live runtimes.
// Every loop below is bounded by a small constant.
//
// Three legs: the preserved in-memory model controls (direct emit/terminal
// calls), the raw leg (every admission/terminal driven by a directly observed
// real runEntry supervisor settlement), and the C-subject leg (every
// admission/terminal driven by a CAdapterWitness-observed completion over the
// pinned real generated bytes). No leg claims integrated credit; QN3 holds it.

import { strict as assert } from "node:assert";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { checkFactsInert, NativeSchemaError } from "./schema.ts";
import {
  LATE_IDENTITIES,
  LateOccurrenceService,
  MAX_LATE_EVENTS,
  MAX_LATE_LEASES,
  type LateEventKind,
  type LateTerminal,
} from "./late.ts";
import {
  CAdapterWitness,
  type CWitnessArtifactKind,
  type CWitnessCompletion,
} from "./c-witness.ts";
import { runEntry } from "../../../../runtime/entry.ts";
import { success, type Completion } from "../../../../runtime/completion.ts";

const passed: string[] = [];
function check(name: string, body: () => void): void {
  body();
  passed.push(name);
}

function expectReject(body: () => unknown, kind: string): void {
  try {
    body();
  } catch (error) {
    if (!(error instanceof NativeSchemaError)) {
      assert.fail("expected a NativeSchemaError");
    }
    assert.equal(error.outcome, "rejected");
    assert.equal(error.kind, kind);
    return;
  }
  assert.fail(`expected rejection with kind ${kind}`);
}

function cleanService(): LateOccurrenceService {
  const late = new LateOccurrenceService();
  late.select("late.alpha");
  late.enroll("worker");
  late.enroll("observer");
  return late;
}

// --- Positive control: clean two-participant run ------------------------------

check("positive-clean-two-participant-run", () => {
  const late = cleanService();

  const early = late.emit("worker", "use", 1);
  assert.equal(early.late, false);
  assert.deepEqual(early.dropped, []);
  checkFactsInert(early, "early event facts");

  const gateWorker = late.gate("worker");
  assert.equal(gateWorker.gate_seq, 2);
  assert.equal(gateWorker.joined, false);
  const gateObserver = late.gate("observer");
  assert.equal(gateObserver.gate_seq, 1);

  const lateFault = late.emit("worker", "fault", 2);
  assert.equal(lateFault.late, true);
  assert.equal(lateFault.identity, "late.alpha");
  const lateUse = late.emit("observer", "use", 1);
  assert.equal(lateUse.late, true);

  const workerLease = late.grantLease("worker");
  assert.equal(workerLease.lease, "llease1");
  const observerLease = late.grantLease("observer");
  assert.equal(observerLease.lease, "llease2");

  const workerTerminal = late.terminal("worker", "completed");
  assert.ok(workerTerminal.binding.startsWith("sha256:"));
  checkFactsInert(workerTerminal, "worker terminal facts");
  const observerTerminal = late.terminal("observer", "completed");
  assert.ok(observerTerminal.binding.startsWith("sha256:"));
  assert.notEqual(workerTerminal.binding, observerTerminal.binding);

  const seen = late.observe("worker", "worker", 2);
  assert.equal(seen.kind, "fault");
  assert.equal(seen.late, true);
  assert.equal(seen.terminal, "completed");
  assert.equal(seen.binding, workerTerminal.binding);
  checkFactsInert(seen, "observation facts");

  const boundLease = late.observeLease("worker", workerLease.lease);
  assert.equal(boundLease.released, false);
  const release = late.releaseLease("worker", workerLease.lease);
  assert.equal(release.terminal, "completed");
  assert.equal(release.binding, workerTerminal.binding);
  const reread = late.observeLease("worker", workerLease.lease);
  assert.equal(reread.released, true);
  const observerRelease = late.releaseLease("observer", observerLease.lease);
  assert.equal(observerRelease.binding, observerTerminal.binding);

  const workerBooks = late.reconcile("worker");
  assert.equal(workerBooks.admitted, 2);
  assert.equal(workerBooks.late, 1);
  assert.deepEqual(workerBooks.dropped, []);
  assert.equal(workerBooks.next_seq, 3);

  const done = late.outcome();
  assert.equal(done.outcome, "complete");
  assert.equal(done.reason, "both terminals witnessed");
  assert.equal(done.worker_dead, false);
  checkFactsInert(done, "outcome facts");

  const counters = late.counters();
  assert.deepEqual(counters, {
    participants: 2,
    admitted: 3,
    late: 2,
    dropped: 0,
    terminals: 2,
    leases: 2,
    releases: 2,
    observations: 3,
    rejected: 0,
  });
  checkFactsInert(counters, "late counters");
});

check("positive-every-identity-and-terminal", () => {
  for (const identity of LATE_IDENTITIES) {
    for (const tag of ["completed", "rejected", "failed"] as const) {
      const late = new LateOccurrenceService();
      late.select(identity);
      late.enroll("worker");
      late.enroll("observer");
      late.emit("worker", "use", 1);
      late.emit("observer", "use", 1);
      late.terminal("worker", tag);
      late.terminal("observer", tag);
      const done = late.outcome();
      assert.equal(done.outcome, "complete");
    }
  }
});

// --- Occurrence swap: cross-participant claims reject --------------------------

check("swap-observe-other-participant-event", () => {
  const late = cleanService();
  late.emit("worker", "fault", 1);
  late.emit("observer", "use", 1);
  // Occurrence swap detected: the observer cannot claim the worker's event.
  expectReject(() => late.observe("observer", "worker", 1), "wrong-owner");
  expectReject(() => late.observe("worker", "observer", 1), "wrong-owner");
  // Matching claims still bind.
  assert.equal(late.observe("worker", "worker", 1).kind, "fault");
  assert.equal(late.observe("observer", "observer", 1).kind, "use");
});

check("swap-lease-claim-other-holder", () => {
  const late = cleanService();
  const lease = late.grantLease("worker");
  late.terminal("worker", "completed");
  late.terminal("observer", "completed");
  // Lease swap detected on both the read and the release path.
  expectReject(() => late.observeLease("observer", lease.lease), "wrong-owner");
  expectReject(() => late.releaseLease("observer", lease.lease), "wrong-owner");
  assert.equal(late.observeLease("worker", lease.lease).holder, "worker");
});

// --- Dropped late events: sequence reconciliation ------------------------------

check("dropped-late-event-detected", () => {
  const late = cleanService();
  late.gate("worker");
  late.emit("worker", "fault", 1);
  const skipped = late.emit("worker", "use", 3);
  assert.deepEqual(skipped.dropped, [2]);
  const books = late.reconcile("worker");
  assert.equal(books.admitted, 2);
  assert.equal(books.late, 2);
  assert.deepEqual(books.dropped, [2]);
  assert.equal(books.next_seq, 4);
  checkFactsInert(books, "reconcile facts");
  // The dropped sequence stays reported on later reconciliations.
  late.emit("worker", "use", 4);
  assert.deepEqual(late.reconcile("worker").dropped, [2]);
  assert.equal(late.counters().dropped, 1);
});

check("dropped-replay-still-rejects", () => {
  const late = cleanService();
  late.emit("worker", "use", 1);
  expectReject(() => late.emit("worker", "use", 1), "stale-handle");
  expectReject(() => late.observe("worker", "worker", 9), "stale-handle");
});

// --- Early release: pre-terminal lease facts are unbound -----------------------

check("early-release-rejects-unbound", () => {
  const late = cleanService();
  const lease = late.grantLease("worker");
  // Lease facts observed before the witnessed terminal event reject,
  // mirroring the K05 eager-read rule.
  expectReject(() => late.observeLease("worker", lease.lease), "permission");
  // Releasing before the terminal event is witnessed is an early release.
  expectReject(() => late.releaseLease("worker", lease.lease), "permission");
  // The same lease binds once the terminal event is witnessed.
  late.terminal("worker", "completed");
  late.terminal("observer", "rejected");
  assert.equal(late.observeLease("worker", lease.lease).released, false);
  const release = late.releaseLease("worker", lease.lease);
  assert.equal(release.terminal, "completed");
  assert.ok(release.binding.startsWith("sha256:"));
});

check("early-release-one-sided-terminal", () => {
  const late = cleanService();
  const workerLease = late.grantLease("worker");
  const observerLease = late.grantLease("observer");
  late.terminal("worker", "failed");
  // Only the witnessed side binds; the other side stays unbound.
  assert.equal(late.observeLease("worker", workerLease.lease).holder, "worker");
  expectReject(() => late.observeLease("observer", observerLease.lease), "permission");
  expectReject(() => late.releaseLease("observer", observerLease.lease), "permission");
  assert.equal(late.outcome().outcome, "incomplete");
});

// --- Worker death: terminal incomplete, never a pass, never silent ------------

check("worker-death-yields-incomplete", () => {
  const late = cleanService();
  late.emit("worker", "use", 1);
  late.emit("observer", "use", 1);
  const death = late.killWorker();
  assert.equal(death.outcome, "incomplete");
  assert.equal(death.reason, "worker-dead");
  assert.equal(death.worker_dead, true);
  checkFactsInert(death, "death outcome facts");
  // Worker admission closes: emits, terminals, and leases all reject.
  expectReject(() => late.emit("worker", "use", 2), "permission");
  expectReject(() => late.terminal("worker", "completed"), "permission");
  expectReject(() => late.grantLease("worker"), "permission");
  expectReject(() => late.enroll("worker"), "permission");
  // The observer can still finish, but the run never passes.
  late.terminal("observer", "completed");
  const done = late.outcome();
  assert.equal(done.outcome, "incomplete");
  assert.equal(done.reason, "worker-dead");
  assert.equal(done.observer_terminal, "completed");
  assert.equal(done.worker_terminal, null);
});

check("worker-death-before-any-terminal", () => {
  const late = cleanService();
  late.killWorker();
  const done = late.outcome();
  assert.equal(done.outcome, "incomplete");
  assert.equal(done.reason, "worker-dead");
  // Prior observations stay readable; the outcome names the death.
  expectReject(() => late.observe("worker", "worker", 1), "stale-handle");
});

// --- Identity, vocabulary, and bounds ------------------------------------------

check("identity-select-once", () => {
  const late = new LateOccurrenceService();
  assert.equal(late.select("late.beta").joined, false);
  assert.equal(late.select("late.beta").joined, true);
  expectReject(() => late.select("late.alpha"), "changed-input");
  expectReject(() => late.select("late.gamma"), "unsupported-capability");
  expectReject(() => late.select(42), "unsupported-capability");
});

check("identity-required-before-enroll", () => {
  const late = new LateOccurrenceService();
  expectReject(() => late.enroll("worker"), "invalid-request");
  expectReject(() => late.emit("worker", "use", 1), "invalid-request");
  expectReject(() => late.terminal("worker", "completed"), "invalid-request");
});

check("vocab-closed", () => {
  const late = cleanService();
  expectReject(() => late.enroll("controller"), "unsupported-capability");
  expectReject(() => late.gate("controller"), "unsupported-capability");
  expectReject(() => late.emit("worker", "spawn", 1), "unsupported-capability");
  expectReject(() => late.emit("worker", "use", 0), "invalid-request");
  expectReject(() => late.emit("worker", "use", 1.5), "invalid-request");
  expectReject(() => late.terminal("worker", "succeeded"), "unsupported-capability");
  expectReject(() => late.observeLease("worker", "llease0"), "not-found");
  expectReject(() => late.observeLease("worker", "llease99"), "not-found");
  expectReject(() => late.releaseLease("worker", "nope"), "not-found");
});

check("terminal-replay-rejects", () => {
  const late = cleanService();
  late.terminal("worker", "completed");
  expectReject(() => late.terminal("worker", "failed"), "stale-handle");
  expectReject(() => late.observe("controller", "worker", 1), "unsupported-capability");
});

check("terminal-closes-admission", () => {
  const late = cleanService();
  late.emit("worker", "use", 1);
  late.terminal("worker", "completed");
  // The terminal binding covers every admitted occurrence: nothing more
  // can arrive after it.
  expectReject(() => late.emit("worker", "use", 2), "permission");
  expectReject(() => late.emit("worker", "fault", 9), "permission");
  // The other participant is unaffected until its own terminal.
  late.emit("observer", "use", 1);
  assert.equal(late.reconcile("worker").admitted, 1);
});

check("terminal-kind-event-is-not-the-witness", () => {
  const late = cleanService();
  const lease = late.grantLease("worker");
  // An occurrence merely labeled "terminal" is not the witnessed terminal
  // event: lease facts stay unbound until terminal() runs.
  const labeled = late.emit("worker", "terminal", 1);
  assert.equal(labeled.kind, "terminal");
  expectReject(() => late.observeLease("worker", lease.lease), "permission");
  expectReject(() => late.releaseLease("worker", lease.lease), "permission");
  late.terminal("worker", "completed");
  assert.equal(late.observeLease("worker", lease.lease).holder, "worker");
});

check("gate-joins-and-release-joins", () => {
  const late = cleanService();
  const first = late.gate("worker");
  assert.equal(first.joined, false);
  const joined = late.gate("worker");
  assert.equal(joined.joined, true);
  assert.equal(joined.gate_seq, first.gate_seq);
  const lease = late.grantLease("worker");
  late.terminal("worker", "completed");
  late.terminal("observer", "completed");
  const release = late.releaseLease("worker", lease.lease);
  const repeat = late.releaseLease("worker", lease.lease);
  assert.equal(repeat.binding, release.binding);
  assert.equal(repeat.lease, lease.lease);
  // The repeat joins: same facts, no additional count.
  assert.equal(late.counters().releases, 1);
});

check("bounds-event-cap", () => {
  const late = cleanService();
  for (let seq = 1; seq <= MAX_LATE_EVENTS; seq += 1) {
    late.emit("worker", "use", seq);
  }
  expectReject(() => late.emit("observer", "use", 1), "resource-limit");
  assert.equal(late.counters().admitted, MAX_LATE_EVENTS);
});

check("bounds-gap-cap", () => {
  const late = cleanService();
  late.emit("worker", "use", 1);
  // A gap wider than the service can ever admit rejects instead of
  // allocating an unbounded dropped list.
  expectReject(() => late.emit("worker", "use", 2 + MAX_LATE_EVENTS + 1), "resource-limit");
  expectReject(() => late.emit("worker", "use", Number.MAX_SAFE_INTEGER), "resource-limit");
  // The boundary gap admits with every skipped number recorded.
  const edge = late.emit("worker", "use", 2 + MAX_LATE_EVENTS);
  assert.equal(edge.dropped.length, MAX_LATE_EVENTS);
  assert.deepEqual(late.reconcile("worker").dropped.slice(0, 3), [2, 3, 4]);
});

check("bounds-lease-cap", () => {
  const late = cleanService();
  for (let index = 0; index < MAX_LATE_LEASES; index += 1) {
    late.grantLease(index % 2 === 0 ? "worker" : "observer");
  }
  expectReject(() => late.grantLease("worker"), "resource-limit");
  assert.equal(late.counters().leases, MAX_LATE_LEASES);
});

check("bounds-rejections-counted", () => {
  const late = cleanService();
  expectReject(() => late.observe("observer", "worker", 1), "wrong-owner");
  expectReject(() => late.select("late.beta"), "changed-input");
  assert.equal(late.counters().rejected, 2);
  checkFactsInert(late.counters(), "late counters");
});

// --- Actual-subject fixtures: real generated bytes, pinned --------------------------
// Same committed emitter output the K05 driver pins, so any drift fails here,
// not silently. The executable artifact is byte-exact; the case artifact
// carries exactly one inserted import line (the runtime/image.ts edge the
// current emitter adds unconditionally).

const here = dirname(fileURLToPath(import.meta.url));
const manifestSource = readFileSync(join(here, "c-ingress.manifest.json"), "utf8");
const manifest = JSON.parse(manifestSource) as {
  readonly signatures: Readonly<Record<string, string>>;
};

function signatureOf(exportName: string): string {
  const signature = manifest.signatures[exportName];
  assert.ok(typeof signature === "string" && signature.length > 0);
  return signature as string;
}

const EVIDENCE_ROOT = join(
  here,
  "..",
  "..",
  "..",
  "..",
  "docs",
  "syntax-taste",
  "evidence",
  "2026-09-26",
  "full-review-2cb1bc3",
  "core-probes",
  "recurse-small",
);
const EXEC_PATH = "entry.ts";
const EXEC_SOURCE = readFileSync(join(EVIDENCE_ROOT, "prod", "entry.ts"), "utf8");
const CASE_FILENAME = "6abe8e13774b07642245601f17e48741d3a9c7cf581b258e1238c7911615f0fb.ts";
const CASE_PATH = `assertions/${CASE_FILENAME}`;
const CASE_RAW = readFileSync(join(EVIDENCE_ROOT, "assert", "assertions", CASE_FILENAME), "utf8");

function sha256Hex(data: string): string {
  return createHash("sha256").update(data, "utf8").digest("hex");
}

assert.equal(
  sha256Hex(EXEC_SOURCE),
  "381aae74c0822da5c281cdad8b304cff437481f50831668ec64fbef70f76cea0",
);
assert.equal(
  sha256Hex(CASE_RAW),
  "6a1128ba8f226230855e241a925e424ee04566dc946d2239b29f9e1106aac96f",
);

const IMAGE_EDGE = 'import { createImage as $canCreateImage } from "../runtime/image.ts";';
const IMAGE_ANCHOR =
  'import { sha256 as $canSHA256 } from "../runtime/platform/crypto/primitives.ts";';
assert.equal(CASE_RAW.split(IMAGE_ANCHOR).length, 2);
const CASE_SOURCE = CASE_RAW.replace(IMAGE_ANCHOR, `${IMAGE_EDGE}\n${IMAGE_ANCHOR}`);
assert.equal(CASE_SOURCE.length, CASE_RAW.length + IMAGE_EDGE.length + 1);

function execArtifact(): { path: string; kind: CWitnessArtifactKind; source: string } {
  return { path: EXEC_PATH, kind: "executable", source: EXEC_SOURCE };
}

function caseArtifact(): { path: string; kind: CWitnessArtifactKind; source: string } {
  return { path: CASE_PATH, kind: "assertion_case", source: CASE_SOURCE };
}

// Independent artifact-digest recomputation: flat preimage, three lines of
// node:crypto, no witness internals.
function artifactDigestOf(path: string, kind: CWitnessArtifactKind, source: string): string {
  return `sha256:${sha256Hex(`${path}\0${kind}\0${source}`)}`;
}

function caseRoot(name: string): {
  package: string;
  declaration: string;
  name: string;
} {
  return { package: "can.k06", declaration: "late", name };
}

// --- Actual-subject harness -----------------------------------------------------

async function checkAsync(name: string, body: () => void | Promise<void>): Promise<void> {
  await body();
  passed.push(name);
}

type RawMainSettlement = Readonly<{ exitCode: 0 | 1; reportLines: number; calls: number }>;

// Drive one adapter through the real runEntry supervisor with a counting stub
// reporter: the observed exit code is the raw settlement the late admission
// below is bound to. At most one settlement per call; no timers, no polling.
async function runRawMain(
  main: (args: readonly string[]) => Completion<void> | Promise<Completion<void>>,
): Promise<RawMainSettlement> {
  let calls = 0;
  let reportLines = 0;
  const exitCode = await runEntry(
    () => {},
    (args) => {
      calls += 1;
      return main(args);
    },
    [],
    () => {
      reportLines += 1;
    },
  );
  return { exitCode, reportLines, calls };
}

// Observed settlement -> late occurrence kind / terminal tag. Failed work
// surfaces as a fault occurrence; every witness completion tag is already a
// valid late terminal tag, so the C leg passes completions through directly.
function kindForExit(exitCode: 0 | 1): LateEventKind {
  return exitCode === 0 ? "use" : "fault";
}

function terminalForExit(exitCode: 0 | 1): LateTerminal {
  return exitCode === 0 ? "completed" : "failed";
}

function kindForCompletion(completion: CWitnessCompletion): LateEventKind {
  return completion === "failed" ? "fault" : "use";
}

// --- Raw leg: admissions bound to directly observed settlements -------------------
// Each check drives tiny adapters through the real runEntry supervisor and
// admits exactly the observed settlements: every emit/terminal below names a
// settlement this driver actually saw (call counts asserted), never a bare
// hand-written call.

await checkAsync("raw-swap-settlement-bound-to-emitter", async () => {
  const late = cleanService();
  const workerSettled = await runRawMain(() => success(undefined));
  assert.equal(workerSettled.calls, 1);
  assert.equal(workerSettled.exitCode, 0);
  assert.equal(workerSettled.reportLines, 0);
  const workerEvent = late.emit("worker", kindForExit(workerSettled.exitCode), 1);
  assert.equal(workerEvent.kind, "use");

  const observerSettled = await runRawMain(async () => {
    throw new Error("boom");
  });
  assert.equal(observerSettled.calls, 1);
  assert.equal(observerSettled.exitCode, 1);
  assert.equal(observerSettled.reportLines, 1);
  const observerEvent = late.emit("observer", kindForExit(observerSettled.exitCode), 1);
  assert.equal(observerEvent.kind, "fault");

  // Each observed settlement stays bound to its emitter: swaps reject.
  expectReject(() => late.observe("observer", "worker", 1), "wrong-owner");
  expectReject(() => late.observe("worker", "observer", 1), "wrong-owner");
  assert.equal(late.observe("worker", "worker", 1).kind, "use");
  assert.equal(late.observe("observer", "observer", 1).kind, "fault");
  checkFactsInert(workerEvent, "raw worker event facts");
  checkFactsInert(observerEvent, "raw observer event facts");
});

await checkAsync("raw-dropped-settlement-detected", async () => {
  const late = cleanService();
  late.gate("worker");
  const first = await runRawMain(() => success(undefined));
  assert.equal(first.calls, 1);
  late.emit("worker", kindForExit(first.exitCode), 1);
  // A second real settlement happens but is never admitted: the gap proves a
  // dropped late event.
  const skipped = await runRawMain(() => success(undefined));
  assert.equal(skipped.calls, 1);
  assert.equal(skipped.exitCode, 0);
  const third = await runRawMain(() => success(undefined));
  const admitted = late.emit("worker", kindForExit(third.exitCode), 3);
  assert.deepEqual(admitted.dropped, [2]);
  assert.equal(admitted.late, true);
  const books = late.reconcile("worker");
  assert.equal(books.admitted, 2);
  assert.deepEqual(books.dropped, [2]);
  assert.equal(books.next_seq, 4);
});

await checkAsync("raw-early-release-unbound", async () => {
  const late = cleanService();
  const lease = late.grantLease("worker");
  expectReject(() => late.observeLease("worker", lease.lease), "permission");
  expectReject(() => late.releaseLease("worker", lease.lease), "permission");
  // The binding terminal event is a real observed settlement, not a bare tag.
  const settled = await runRawMain(() => success(undefined));
  assert.equal(settled.calls, 1);
  const terminal = late.terminal("worker", terminalForExit(settled.exitCode));
  assert.equal(terminal.terminal, "completed");
  const release = late.releaseLease("worker", lease.lease);
  assert.equal(release.binding, terminal.binding);
  checkFactsInert(release, "raw-bound release facts");
});

await checkAsync("raw-worker-death-incomplete", async () => {
  const late = cleanService();
  const workerSettled = await runRawMain(() => success(undefined));
  late.emit("worker", kindForExit(workerSettled.exitCode), 1);
  const observerSettled = await runRawMain(() => success(undefined));
  late.emit("observer", kindForExit(observerSettled.exitCode), 1);
  const death = late.killWorker();
  assert.equal(death.outcome, "incomplete");
  assert.equal(death.reason, "worker-dead");
  // A fresh real settlement for the observer still cannot flip the run.
  const terminalSettled = await runRawMain(() => success(undefined));
  late.terminal("observer", terminalForExit(terminalSettled.exitCode));
  const done = late.outcome();
  assert.equal(done.outcome, "incomplete");
  assert.equal(done.reason, "worker-dead");
  assert.equal(done.observer_terminal, "completed");
  // And the worker's own fresh settlement has nowhere to go.
  const workerRetry = await runRawMain(() => success(undefined));
  assert.equal(workerRetry.exitCode, 0);
  expectReject(() => late.emit("worker", kindForExit(workerRetry.exitCode), 2), "permission");
});

// --- C-subject leg: admissions bound to witnessed generated-path completions -----
// Each check instruments the pinned real generated bytes with the current
// CAdapterWitness API (instrument/invokeExecutable/invokeCase/observe; no
// begin/complete seam exists) and admits exactly the observed witness
// completions. Artifact digests are recomputed independently below.

await checkAsync("c-subject-swap-across-witnessed-artifacts", async () => {
  const late = cleanService();
  const witness = new CAdapterWitness();
  const exec = witness.instrument(execArtifact(), "$canMain", signatureOf("$canMain"), manifest);
  assert.equal(exec.artifact_digest, artifactDigestOf(EXEC_PATH, "executable", EXEC_SOURCE));
  const kase = witness.instrument(caseArtifact(), "$canCase", signatureOf("$canCase"), manifest);
  assert.equal(kase.artifact_digest, artifactDigestOf(CASE_PATH, "assertion_case", CASE_SOURCE));
  assert.notEqual(exec.token, kase.token);

  let workerCalls = 0;
  const workerDone = await witness.invokeExecutable(
    exec.token,
    exec.artifact,
    exec.artifact_digest,
    () => {
      workerCalls += 1;
      return success(undefined);
    },
  );
  assert.equal(workerCalls, 1);
  assert.equal(workerDone.completion, "completed");
  let observerCalls = 0;
  const observerDone = await witness.invokeCase(kase.token, kase.artifact, kase.artifact_digest, {
    root: caseRoot("swap"),
    actual: async () => {
      observerCalls += 1;
      return success(1);
    },
    expected: async () => success(1),
  });
  assert.equal(observerCalls, 1);
  assert.equal(observerDone.completion, "completed");

  const workerSeen = witness.observe(
    exec.token,
    exec.artifact,
    exec.artifact_digest,
    workerDone.invocation,
  );
  const observerSeen = witness.observe(
    kase.token,
    kase.artifact,
    kase.artifact_digest,
    observerDone.invocation,
  );
  late.emit("worker", kindForCompletion(workerSeen.completion), 1);
  late.emit("observer", kindForCompletion(observerSeen.completion), 1);

  // Witness layer: a token/artifact/digest triple never minted together
  // rejects, so one participant cannot claim the other's witnessed call.
  expectReject(
    () => witness.observe(kase.token, exec.artifact, exec.artifact_digest, workerDone.invocation),
    "not-found",
  );
  // Late layer: cross-participant claims on witnessed occurrences reject.
  expectReject(() => late.observe("observer", "worker", 1), "wrong-owner");
  expectReject(() => late.observe("worker", "observer", 1), "wrong-owner");
  assert.equal(late.observe("worker", "worker", 1).kind, "use");
  assert.equal(late.observe("observer", "observer", 1).kind, "use");
  checkFactsInert(workerSeen, "c worker observation facts");
  checkFactsInert(observerSeen, "c observer observation facts");
});

await checkAsync("c-subject-dropped-invocation-detected", async () => {
  const late = cleanService();
  late.gate("worker");
  const witness = new CAdapterWitness();
  const exec = witness.instrument(execArtifact(), "$canMain", signatureOf("$canMain"), manifest);
  const first = await witness.invokeExecutable(
    exec.token,
    exec.artifact,
    exec.artifact_digest,
    () => success(undefined),
  );
  const firstSeen = witness.observe(
    exec.token,
    exec.artifact,
    exec.artifact_digest,
    first.invocation,
  );
  late.emit("worker", kindForCompletion(firstSeen.completion), 1);
  // A second witnessed invocation completes but is never admitted.
  const skipped = await witness.invokeExecutable(
    exec.token,
    exec.artifact,
    exec.artifact_digest,
    () => success(undefined),
  );
  assert.equal(skipped.completion, "completed");
  assert.equal(skipped.invocation, "cinv2");
  const third = await witness.invokeExecutable(
    exec.token,
    exec.artifact,
    exec.artifact_digest,
    () => success(undefined),
  );
  const thirdSeen = witness.observe(
    exec.token,
    exec.artifact,
    exec.artifact_digest,
    third.invocation,
  );
  assert.equal(third.invocation, "cinv3");
  const admitted = late.emit("worker", kindForCompletion(thirdSeen.completion), 3);
  assert.deepEqual(admitted.dropped, [2]);
  assert.equal(admitted.late, true);
  assert.deepEqual(late.reconcile("worker").dropped, [2]);
  // Three witnessed settlements, two admissions: the gap is the proof.
  assert.equal(witness.counters().invocations, 3);
  assert.equal(late.counters().admitted, 2);
});

await checkAsync("c-subject-early-release-unbound", async () => {
  const late = cleanService();
  const witness = new CAdapterWitness();
  const kase = witness.instrument(caseArtifact(), "$canCase", signatureOf("$canCase"), manifest);
  const workerLease = late.grantLease("worker");
  const observerLease = late.grantLease("observer");
  expectReject(() => late.observeLease("worker", workerLease.lease), "permission");
  expectReject(() => late.releaseLease("worker", workerLease.lease), "permission");
  // The binding terminal event is an actually witnessed case settlement.
  const done = await witness.invokeCase(kase.token, kase.artifact, kase.artifact_digest, {
    root: caseRoot("terminal"),
    actual: async () => success(1),
    expected: async () => success(1),
  });
  const seen = witness.observe(kase.token, kase.artifact, kase.artifact_digest, done.invocation);
  assert.equal(seen.completion, "completed");
  const terminal = late.terminal("worker", seen.completion);
  assert.equal(terminal.terminal, "completed");
  const release = late.releaseLease("worker", workerLease.lease);
  assert.equal(release.binding, terminal.binding);
  checkFactsInert(release, "c-bound release facts");
  // A rejected case settlement binds a rejected terminal the same way.
  const rejected = await witness.invokeCase(kase.token, kase.artifact, kase.artifact_digest, {
    root: caseRoot("terminal-rejected"),
    actual: async () => success(1),
    expected: async () => {
      throw new Error("expected blew up");
    },
  });
  const rejectedSeen = witness.observe(
    kase.token,
    kase.artifact,
    kase.artifact_digest,
    rejected.invocation,
  );
  assert.equal(rejectedSeen.completion, "rejected");
  assert.equal(rejectedSeen.kind, "assertion_case");
  if (rejectedSeen.kind !== "assertion_case") {
    assert.fail("expected an assertion_case observation");
  }
  assert.equal(rejectedSeen.reason, "expected evaluation failed");
  late.terminal("observer", rejectedSeen.completion);
  const observerRelease = late.releaseLease("observer", observerLease.lease);
  assert.equal(observerRelease.terminal, "rejected");
});

await checkAsync("c-subject-worker-death-incomplete", async () => {
  const late = cleanService();
  const witness = new CAdapterWitness();
  const exec = witness.instrument(execArtifact(), "$canMain", signatureOf("$canMain"), manifest);
  const kase = witness.instrument(caseArtifact(), "$canCase", signatureOf("$canCase"), manifest);
  const workerDone = await witness.invokeExecutable(
    exec.token,
    exec.artifact,
    exec.artifact_digest,
    () => success(undefined),
  );
  const workerSeen = witness.observe(
    exec.token,
    exec.artifact,
    exec.artifact_digest,
    workerDone.invocation,
  );
  late.emit("worker", kindForCompletion(workerSeen.completion), 1);
  const observerDone = await witness.invokeCase(kase.token, kase.artifact, kase.artifact_digest, {
    root: caseRoot("death"),
    actual: async () => success(1),
    expected: async () => success(1),
  });
  const observerSeen = witness.observe(
    kase.token,
    kase.artifact,
    kase.artifact_digest,
    observerDone.invocation,
  );
  late.emit("observer", kindForCompletion(observerSeen.completion), 1);
  const death = late.killWorker();
  assert.equal(death.outcome, "incomplete");
  assert.equal(death.reason, "worker-dead");
  // A further witnessed settlement for the observer still cannot complete it.
  const terminalDone = await witness.invokeCase(kase.token, kase.artifact, kase.artifact_digest, {
    root: caseRoot("terminal"),
    actual: async () => success(1),
    expected: async () => success(1),
  });
  const terminalSeen = witness.observe(
    kase.token,
    kase.artifact,
    kase.artifact_digest,
    terminalDone.invocation,
  );
  late.terminal("observer", terminalSeen.completion);
  const done = late.outcome();
  assert.equal(done.outcome, "incomplete");
  assert.equal(done.reason, "worker-dead");
  assert.equal(done.observer_terminal, "completed");
  // The worker's own witnessed terminal has nowhere to go.
  expectReject(() => late.terminal("worker", workerSeen.completion), "permission");
});

await checkAsync("c-subject-unwitnessed-adapter-yields-no-occurrence", async () => {
  const late = cleanService();
  const witness = new CAdapterWitness();
  const exec = witness.instrument(execArtifact(), "$canMain", signatureOf("$canMain"), manifest);
  // A directly called (unwitnessed) adapter produces no facts to admit.
  let calls = 0;
  const adapter = () => {
    calls += 1;
    return success(undefined);
  };
  adapter();
  assert.equal(calls, 1);
  assert.equal(witness.counters().invocations, 0);
  expectReject(
    () => witness.observe(exec.token, exec.artifact, exec.artifact_digest, "cinv1"),
    "stale-handle",
  );
  // No witnessed settlement, so no late admission exists to observe.
  expectReject(() => late.observe("worker", "worker", 1), "stale-handle");
  assert.equal(late.counters().admitted, 0);
});

console.log(
  JSON.stringify({
    schema: "can.native-test.late-check",
    passed: passed.length,
    checks: passed,
  }),
);
