"""Prepare audited, independently phrased technical choices; --send calls Jev."""
from pathlib import Path
import datetime
import hashlib
import itertools
import json
import os
import sys
import urllib.request

OUT = Path(__file__).resolve().parent

# Each column is a fresh wording of the entire request, not only its question.
STATE = {
    "objective": [
        "Can targets AI coding agents. Correct behavior, reliable edits, explicit contracts and independent composition lead; total tokens per successful task including context, diagnostics and retries is secondary. Human familiarity and source brevity are not goals. There are zero external users and no compatibility obligation. Prefer equivalent native JavaScript/Bun operations with only adapters needed for contracts and immutability. Select informative bounded technical trials, never syntax or final language adoption.",
        "This language is written by coding agents. Rank correctness, safe refactoring, inspectable contracts and separately authored library composition above measured whole-task token cost. Count prompts, repair and validation as well as code; human comfort and short source are irrelevant. No external adopters require preserving prior forms. Lower to native JS/Bun wherever semantics agree, adding minimal immutable-contract support. These judgments guide experiments rather than grammar decisions or production changes.",
        "Evaluate experiments for an agent-authored language, where successful behavior, dependable changes, visible guarantees and independent libraries matter first. Tokens consumed through a complete successful task are a secondary metric, encompassing supplied context and failed attempts. Neither human taste nor line count is an acceptance rule. With no outside users, backward compatibility has no value. Generated TypeScript should use equivalent JavaScript/Bun primitives and necessary immutability/contract adapters. Advice cannot enact a language or spelling choice.",
    ],
    "provenance": [
        "Evidence packets inspect revision 02a549d2. Historical executed probes at 4c2db1e have unchanged compiler/runtime sources at that revision. Current focused type, project and resolver tests pass; assertion runtime tests passed 14/14. These are source audits and narrow tests, not candidate implementations or agent comparisons. Existing decisions remain authoritative. Pattern-intent and finite-generic-error experiments were consulted separately and are excluded here. No general effect system, arbitrary backend access or mutable aliases is justified.",
        "At 02a549d2 the preparation notes combine source inspection and focused passing compiler tests with 14 successful assertion runtime tests. Their older executable cases came from 4c2db1e; no compiler/runtime change separates those revisions. Replacement prototypes and controlled agent measurements do not yet exist for these five choices. The selected specification still governs. Earlier consultations already cover patterns and generic error helpers, so neither is being re-decided. The supplied findings do not support broad effects, unrestricted backend calls or mutable aliasing.",
        "The baseline is the audited 02a549d2 source plus earlier 4c2db1e executions, whose compiler and runtime files are unchanged. Targeted type/project/resolver suites and all 14 assertion runtime checks passed. This support is narrower than evaluating an alternative implementation or measuring agent performance. Retain current normative rules until expressly revised. Separate saved reviews address pattern intent and finite error polymorphism; these questions avoid duplicating them. General effects, free backend imports and shared mutable aliases remain unsupported expansions.",
    ],
    "values": [
        "DI-02: Exported records share one visibility bit for type and construction, allow positional creation, public projection and same-type with updates, and are frozen. A private record cannot appear in a public signature. Generic decoding projects declared fields directly into nominal records without calling a source factory. Thus a transparent email(str value) can be forged through construction, update or structural decode; this is source/runtime inference, not a dedicated exported-email execution. The strongest baseline decodes a public wire record, calls a validator, and revalidates at ingress and sensitive operations; correct application behavior is possible, but nominal membership cannot certify validation. Owner boundaries must cover equality, hidden-field matching, with, encoding/decoding/schema and fixture completions together. Test email canonicalization, positive quantity and tenant identifiers; valid tenant identity never grants access to another tenant's invoice. Owner-controlled designs still trust their author's creation code; central validators need recursion, normalization, side-effect and finite-failure rules.",
        "DI-02 concerns invariants on authored immutable records. Current public type visibility also exposes construction, field observation and with replacement; frozen storage prevents mutation, not invalid initial contents. Private types cannot escape through exported signatures. Codec projection manufactures a nominal record from structural fields, bypassing user factories. Audited paths therefore permit invalid email(str value) via callers, replacement or decoding, although an end-to-end public-email probe was not run. A good current program can decode wire data, validate explicitly and check again at important boundaries; it cannot promise all instances of that nominal type are valid. Any experiment must jointly define comparison, representation visibility in patterns, updates, wire/schema operations and supplied fixtures. Exercise normalized emails, positive quantities and tenant IDs while checking authorization at each protected invoice operation. Package minting trusts owner implementations; universal validation introduces questions about recursion, effects, canonicalization and exact errors.",
        "For DI-02, record immutability and nominal tags already exist, but exported declarations make positional construction and visible-field with edits available to importers. There is no independent constructor visibility, and public functions may not expose private record types. Document decoders build the nominal representation from schema fields rather than invoke its factory. These inspected mechanisms imply a forgeable email(str value); a dedicated cross-package execution remains missing. Explicit wire decoding followed by factories and repeated sensitive-boundary validation is the strongest existing idiom and may deliver a correct app, without making type inhabitation proof of validation. A new boundary is incomplete unless it covers equalities, hidden fields in matches, copy changes, codecs/schema and fixture creation. Use canonical email, positive quantity and tenant-ID cases, including rejection of cross-tenant invoice access despite a valid ID. Owner policies rely on trusted minting code; a single checked validator requires defined normalization, recursion, effects and finite failures.",
    ],
    "packages": [
        "DI-05a: Internal graph IDs already include project/dependency identity and short package name; output paths hash that identity. Graph.Packages nevertheless indexes all loaded packages by short name and rejects duplicates before uses aliases run. File-local aliases cannot fix two independent dependencies both declaring model. Imports resolve only declared direct dependencies and enforce canonical internal visibility and reserved catalogue names. Compare consuming both unchanged libraries in one root file, then renaming root aliases, adding a transitive model and relocating the checkout. Dependency imports must resolve through that dependency's own table; distinct loaded versions/instances cannot merge merely because names match. Keep source maps, lock reproducibility and emitted native module identity coherent. Globally qualified authored declarations are a coherent future regime but require rewriting bare-name libraries, so cannot pass the unchanged-library case.",
        "DI-05a starts with qualified IDs and hashed output filenames already present, while the loading map Graph.Packages still requires globally unique terminal names. Duplicate model packages fail before file aliases are resolved; today's uses aliases only rename a successfully selected package. Direct-dependency visibility, canonical internal restrictions and the catalogue namespace must survive. The acceptance graph imports two unmodified same-named libraries into one source file and repeats after local alias edits, another transitive model and checkout relocation. Each library's imports use its own dependency bindings, and separate loaded instances or versions remain distinct. Source-map identities, locking and native module paths must agree. Requiring authors to declare full unique names is viable for newly authored libraries, but changes existing bare declarations and does not meet this unmodified-input benchmark.",
        "The package loader in DI-05a has project-qualified identity and identity-hashed output paths, yet its Graph.Packages short-name index rejects a collision anywhere in the graph. A uses alias is applied too late to disambiguate two independent model declarations. Preserve direct-only imports, canonical internal checks and protected catalogue naming. Trials must combine those unchanged dependencies in a single consumer, modify only root aliases, introduce a transitive namesake and move the checkout. Resolve library imports in the library's own dependency context, keeping separately loaded versions/instances separate. Deterministic locks, source mapping and native import emission depend on a consistent canonical identity. Author-qualified package declarations form a valid alternative contract only with rewritten bare-name inputs, not a pass for the original unchanged libraries.",
    ],
    "errors": [
        "DI-05b: Nominal errors are identified by declaring package/declaration and concrete generic arguments, whereas source numeric IDs are diagnostic codes. Source numbers duplicate active can.errors.json entries, locks snapshot registries, and active plus retired codes must be globally unique across catalogue/root/dependencies. Loader, checker and runtime failure-plan admission all enforce numeric uniqueness. The audited code identifies those consumers but establishes no external numeric-report or cross-release rename requirements. Scoped codes, build-local allocation and textual keys all need coherent registry/lock/plan/report treatment. Two libraries reusing active codes or another library's retired code should compose without coordination under a new contract. Test both failures, two generic instances, and reports across a dependency-addition build; a shared declaration code must not merge specialized nominal errors. A hash alone is not a collision-free numeric scheme. Package owner identity is a dependency of this choice, but no package candidate is assumed selected.",
        "Error composition, DI-05b, separates fully specialized package/declaration identity from diagnostic integers. Current source declarations repeat active registry numbers in can.errors.json; dependency locks preserve them, and even retired entries reserve their integers throughout the entire graph. Graph loading, checking and runtime plan validation each reject duplicates. These known consumers have been inspected, but requirements for outside number-based reports or stable identities after release renames are not known. Any scoped, generated or textual reporting trial must update the registry, lock, plan and report contract consistently. Exercise independent equal active IDs and active-versus-foreign-retired IDs, trigger both errors and generic specializations, then interpret reports before and after adding a dependency. Declaration-level codes cannot collapse distinct instantiated error types. Bare hashing cannot promise collision-free integers. This topic relies on canonical package ownership without presuming an answer to the import question.",
        "In DI-05b the integer attached to an error is a diagnostic identifier; nominal matching uses its package/declaration plus type arguments. Authors enter active numbers in source and can.errors.json, with registries captured by locks. Both active and retired values collide globally today, enforced in loader, checker and runtime plans. The audit found these internal uses; it did not establish external consumers' numeric needs or cross-version rename policy. Scope-based, build-generated and direct textual reports must each specify all registry/locking/emission/reporting consequences. Acceptance uses independently repeated active numbers and reuse of a foreign retired number, distinct triggered failures and generic instances, and old/new reports after graph growth. Sharing a reporting code never makes two specializations one nominal error. Numeric hashes require explicit collision handling to guarantee uniqueness. Canonical owner identity is required but the package-import trial remains independent.",
    ],
    "fixtures": [
        "DI-06: Attached assertions have full package/declaration/name roots. Lexical when rows select by the running root's short name; FIFO queues isolate full root/table/invocation paths and never search arguments to allocate occurrences. Historical execution renamed only caller customer to renamed: static checking passed, helper fixture activation disappeared, text::from_int(7) returned 7 rather than fixture text, and the helper's own unit assertion still passed. This is a fragile selector relationship, not a concurrent queue collision. Inert exact-target templates expand under a use-site selector and retain that fragility. Whole-helper stubs plus separate helper unit assertions avoid internal linking but lose integrated helper-body coverage; ordinary injected callables are another current API baseline. Every candidate retains attached roots, exact target/arguments, lexical queues, FIFO, recursion/callable/participant paths and distinct real/supplied/raw-provider evidence labels. Compare root rename, duplicate root labels, two helper invocations, recursion, concurrent participants, missing links and unused fixtures; a deliberately requested missing scenario must not silently run real code.",
        "For DI-06, the root identity is package/declaration/assertion name but fixture rows match just the active root label. Queue isolation already uses complete root and lexical-table identities plus invocation/reservation paths, with FIFO rather than argument search. An older executable caller-label edit from customer to renamed still checked yet caused text::from_int(7) in the helper to execute for real, replacing fixture text with 7; the helper unit case was unaffected. The defect is implicit selection, not queue sharing. Typed inert templates preserve local table ownership and inherit the use-site label, so they do not repair cross-package activation. Current whole-helper stubs and separately tested internals sacrifice combined-path coverage; explicit callable dependency injection is also available as a baseline. Preserve attached assertions, target and argument checking, per-table FIFO/path isolation for recursion and concurrent/callable participants, and honest real/supplied/raw evidence. Exercise renamed and duplicate roots, repeated helpers, recursion/concurrency and missing/unused links, disallowing silent real fallback for explicitly requested missing fixtures.",
        "DI-06 has sound full-root queue identities but brittle row selection: when compares its selector against the current assertion's unqualified label. Allocation remains FIFO per root, lexical table and invocation/reservation path, never an argument lookup. In historical executed projects, changing caller customer to renamed alone passed checking while the helper switched from fixture output to real text::from_int(7), giving 7; its own unit assertion continued to pass. This demonstrates activation coupling rather than a concurrency collision. Reusable exact-target templates are inert and expand under the local selector, leaving that coupling intact. Stubbing the helper as a whole plus its own unit tests is a strong existing option but does not exercise its body inside the caller path; ordinary callable injection also deserves comparison. All alternatives must retain attached roots, checked targets/arguments, FIFO lexical queues, recursive/callable/concurrent invocation identity and separate supplied/raw/real evidence labels. Test label renames/collisions, repeated calls, recursion and participants, unused fixtures and disappeared explicit links; a requested unavailable fixture cannot quietly become a real call.",
    ],
    "variants": [
        "DI-07: Current assignment first rejects different specializations of the same generic variant, including phantom parameters, then otherwise uses nominal leaf-set inclusion. Historical direct tagged<int> -> tagged<str> fails; tagged<int> -> bridge -> tagged<str> and narrowing through shared unit succeed. Current focused type tests confirm the rule; no runtime identity or memory defect is demonstrated. Variants are flattened sets without constructors/wrappers; values and codec tags are nominal leaves. Generic records have distinct specialized nominal identities and are not shown broken. Compare direct/bridge/unit paths, nested variants, leaf addition, option<int>/option<str>, shared none, distinct some<int>/some<str>, generic record leaves and codec roundtrips. Extensional variants cannot provide brands; existing nominal record wrapping is a baseline for brands. Wrappers would change representation, conversions, matching and wire identity, so measure allocations and codec consequences. No comparative agent cost exists.",
        "The DI-07 checker combines a same-generic-declaration specialization veto with leaf inclusion for other assignments. Executed probes rejected direct tagged<int> -> tagged<str> but admitted a bridge variant and a shared unit leaf route; present type tests still support that matrix. It is path-sensitive static admission, not evidence of a memory bug or lost runtime identity. Runtime values and codec tags belong to nominal leaves, since variants currently have no wrapper constructor. Specialized generic records keep their own nominal distinctions. Required comparisons cover direct, bridge and unit cases, option<int>/option<str> with common none and distinct some<int>/some<str>, nested sets, new leaves, generic records and roundtrips. Pure sets intentionally do not brand; nominal record wrappers already offer a branding baseline. A new nominal variant regime would require conversion/matching and wire-representation changes plus allocation measurements. Agent edit costs have not been measured.",
        "DI-07's current relation rejects differing instances of one generic variant before admitting leaf-set subsets between other types. Earlier running cases showed direct tagged<int> -> tagged<str> refusal and successful bridge and unit-leaf detours; focused contemporary tests corroborate the policy. No runtime-safety failure follows from that static inconsistency. Variants flatten into nominal leaves without wrapper construction, and codecs encode those leaves. Ordinary generic record identity remains specialization-specific. Trials must exercise all three paths along with nested variants, added leaves, option<int>/option<str>, shared none, differentiated some<int>/some<str>, generic record leaves and encoding roundtrips. Leaf-set semantics offer no variant branding; current nominal records can supply a wrapper baseline where branding is needed. Nominal variants would alter conversion, matching, representation and codec recovery, requiring allocation evidence. There is no measured comparative agent behavior yet.",
    ],
    "trial_policy": [
        "Judge only technical information gained relative to implementation scope. Each candidate is a possible experiment, with the best current idiom as a control; none is already proven beneficial. Include creation, held-out rename/refactor and diagnostic repair cases with equivalent agent context/tools and preregistered model/effort/trials. Require contract tests and reproducible failure or measured benefit after library/tooling alternatives. If evidence cannot distinguish next trials, select defer_measure rather than fabricate certainty. All five questions are independent against this shared state.",
        "Choose trials for their ability to resolve the stated contract gap at bounded cost, not for adoption or taste. Compare a proposed mechanism to the strongest existing practice; demonstrated superiority is still absent. Register model settings, sample count and equal instructions/tools before creation, unseen refactor and repair tasks. Passing semantic tests and a repeatable current-idiom failure or material benefit beyond library/tooling changes are prerequisites to promotion. Use defer_measure when this record cannot support an informative next-prototype choice. Each of the five judgments uses the same evidence independently.",
        "The decision is which limited experiment yields useful technical evidence per added scope. Keep present best-practice code as a benchmark and do not presume any candidate wins. Predefine models, effort, repeats and equivalent tool/context access, then include initial authoring, held-out edits and diagnostic recovery. Advancement requires the relevant semantics to pass plus reproducible baseline failure or meaningful measured gains after considering tooling/libraries. Choose defer_measure if selecting a next experiment remains underdetermined. Answers to these five independent questions cannot depend on one another.",
    ],
}

QUESTIONS = {}
def question(key, wording, criteria):
    QUESTIONS[key] = {"instructions": wording, "criteria": criteria}

question("validated_value_trial", [
    "For DI-02, which next bounded comparison most usefully tests an unforgeable package-owned validated-value contract across every creation path, given the strongest baseline and remaining evidence gaps? Select a trial, not syntax or adoption.",
    "Which DI-02 experiment should next investigate whether package-controlled valid values improve on disciplined validation, considering construction, codecs and fixtures as one boundary? Recommend only a technical comparison.",
    "Choose the most informative limited DI-02 trial for preventing unauthorized manufacture of validated values through all admitted routes while comparing current practice; no language decision follows from this answer.",
], {
    "owner_record": [
        "Test a public nominal record with package-only construction and with updates. Permit selected immutable projections and identity matching without hidden-field destructuring. Owner functions validate minting; equality is owner-defined unless deliberately exposed. Reject derived decode/schema and use wire records plus owner factories; encode via owner projection. Fixtures use factories or validated owner constants. Keep frozen JS records with compiler visibility checks; cost is trust in owner code and additional adapters.",
        "Prototype separate visibility for a record type versus its constructors/replacements. Consumers observe only published frozen fields and nominal identity; hidden pattern fields remain inaccessible. Minting and default equality belong to owner APIs, with an explicit fixed equality export allowed. Deny generic decoding/schema, route wire data through factories and encode owner projections; fixtures acquire validated constants or factory values. Existing frozen nominal representation suffices, at the expense of owner trust and boundary plumbing.",
        "Evaluate a record-shaped owner boundary: only its declaring package creates or copy-updates, while chosen read-only fields and leaf identity can be public. Concealed fields cannot be matched; comparison is an owner operation unless a stable public equality is expressly granted. Structural codecs/schema cannot manufacture it: factory-decode a wire record and project for encoding. Supply fixtures through owner-validated constants/factories. Compile access restrictions around frozen JS records, measuring adapter burden and trusted creation code.",
    ],
    "opaque_value": [
        "Trial an entirely hidden authored nominal representation, with owner wrap/unwrap, observation, equality and update APIs; consumers may test leaf identity in variants but cannot destructure or with-update. Owner codecs use separate wire types; derived codec/schema is forbidden. Assertions observe projections/equality and obtain genuine owner values. A frozen brand wrapper is used unless erasure is proven safe. Smaller legal surface trades against accessors, fixture work and possible allocations.",
        "Experiment with owner-only access to an opaque nominal payload. External code uses exported read/compare/transform functions and optional identity-only variant tests, never representation patterns or with. Forbid schema/codec derivation and let owner functions define wire conversion and errors. Assertion values come from the owner and are checked through published observations. Retain a frozen branded wrapper until safe erasure is established; weigh strict abstraction against API/adaptor and allocation costs.",
        "Compare full authored opacity: the package alone wraps and unwraps, and public operations control every observation, equality and replacement. Identity may remain a variant leaf test without exposing fields; destructuring and consumer with are illegal. Explicit owner codecs target separate wire data, with no derived schema. Fixtures need actual owner-produced handles and projection/equality checks. Default to immutable branded wrappers, erasing only with proof; test whether the reduced consumer surface offsets extra operations and allocations.",
    ],
    "checked_construction": [
        "Prototype one owner validator over raw representation with finite errors, invoked for every constructor, with update, decode and supplied fixture. It validates/canonicalizes without recursively minting the target. Fields and nominal patterns stay public, equality compares validated fields. Decode combines structural and domain failures; schema promises only shape. Define recursion/effects and lower to validator calls plus frozen records. This centralizes admission but makes construction and codecs fallible.",
        "Test a declared validation function that consumes representation and either normalizes it or emits named finite failures before any record exists. All construction, copying, document projection and fixture supply must invoke it. Public projections/matches and ordinary nominal field equality remain. Decoders expose structural plus predicate errors and schemas describe structure alone. Specify effects/recursive behavior; generate native calls and immutable-record adapters. Uniform checking trades for new failure sequencing at every creation site.",
        "Evaluate universally checked record creation through a designated owner predicate/normalizer over an unconstructed payload. Initial calls, with, generic decode and fixture completions share its finite failure contract; it cannot recursively construct the same target to validate. Keep visible fields, leaf patterns and post-validation field equality. Structural schemas do not assert predicate validity; decoding reports both error categories. Native validator invocation precedes freezing, with explicit recursion/effect rules and measured fallibility overhead.",
    ],
    "defer_measure": [
        "First execute the missing exported-email importer/decoder/fixture counterexamples and benchmark explicit wire-record factories plus operation revalidation, making no boundary prototype yet; this baseline promises correct operations, not valid nominal membership.",
        "Delay choosing a boundary until cross-package email forging and current wire/factory/recheck code have executable results, including fixtures and decoding. Measure the disciplined baseline without claiming every record instance satisfies its predicate.",
        "Collect the absent end-to-end invalid-email paths and agent data for wire decoding, factories and sensitive-operation validation before prototyping a new abstraction. Retain the honest distinction between application correctness and guaranteed valid inhabitants.",
    ],
})

question("package_identity_trial", [
    "For DI-05a, which resolution-contract experiment is most useful for composing independent packages without editing them while preserving identity and confinement? Treat declaration-qualified rewriting as a different prerequisite, not a pass for unchanged libraries.",
    "Select the next DI-05a technical comparison for duplicate short names with deterministic identities and direct-dependency restrictions; account explicitly for any candidate that first rewrites vendor declarations.",
    "Which bounded package-resolution trial best investigates unmodified library composition and retained visibility rules in DI-05a? Do not credit author-renamed inputs as the unchanged-library acceptance case.",
], {
    "qualified_imports": [
        "Prototype source imports naming a direct dependency key and package with optional local aliases. Local packages use the current project, catalogue a reserved namespace, and dependency internals their own tables. Preserve distinct instances, locks and identity-based native imports. This puts selection in source but adds qualified references.",
        "Test explicit dependency-plus-package source selection with file aliases, current-project local lookup and unshadowable catalogue qualification. Resolve each dependency relative to its manifest and keep separate instances in locks/emission. Native imports follow canonical IDs; source-level clarity costs longer references.",
        "Compare directly written import targets composed of dependency key and package, optionally renamed within a file. Use project-local lookup for own packages and reserved catalogue identity; libraries consult their own dependency bindings. Maintain lock and loaded-instance distinctions in native emission, measuring the added source qualification.",
    ],
    "manifest_handles": [
        "Prototype unique project-manifest handles mapped to direct dependency/package targets, optionally file-aliased in source. Each dependency owns its mappings, catalogue handles cannot be shadowed, and missing/ambiguous entries diagnose. Locks bind resolved identities rather than handle names; native imports are static. This centralizes remapping but adds a consulted file.",
        "Test manifest-defined local import names whose values identify one direct dependency package, retaining per-file aliases. Nested projects resolve their own maps and reserve catalogue names; graph loading rejects incomplete or ambiguous handles. Canonical instances, not handles, drive locks/native imports. Compact source trades against manifest context and indirection.",
        "Evaluate source handles declared in each project's import map and bound to dependency/package pairs; a file may alias a handle. Library maps are independent, reserved catalogue handles stay protected, and invalid mappings fail early. Emit native modules and lock canonical targets irrespective of handle renames. Measure central remap benefits against another-file lookup costs.",
    ],
    "qualified_declarations": [
        "Trial globally author/project-qualified package declarations and local aliases after rewriting bare-name libraries. Distinct loaded instances remain separate; identical declared identities require an explicit resolution choice. No unchanged-library success is claimed. Compare reduced map indirection against author naming coordination and migration work.",
        "Evaluate a regime requiring fully qualified package declarations from authors, while source aliases stay short. Rewrite the input libraries first and report failure to satisfy the original untouched-input requirement. Preserve version/instance identities and reject exact full-name collisions absent explicit resolution. The trade is naming coordination for fewer mappings.",
        "Prototype author-qualified declaration names with convenient local aliases, acknowledging that existing bare declarations must change. Keep loaded versions distinct and make identical qualified declarations an explicit resolution conflict. This is a separate-input experiment rather than unchanged dependency composition; assess author coordination versus lookup indirection.",
    ],
    "defer_measure": [
        "Gather the full two-dependency graph, alias/relocation/lock counterexamples and comparative agent tasks first, retaining the global-short-name baseline as a documented failing control rather than choosing a new lookup prototype.",
        "Postpone a resolution prototype until an executable same-name graph and refactor/lock/checkout tests plus agent comparison inputs are available. Keep today's globally unique naming discipline only as the explicit failing composition baseline.",
        "Prepare and run the missing complete duplicate-package, local-alias and deterministic-lock/relocation baseline before picking an alternative. Record current global naming's composition failure and collect agent tasks without changing resolution yet.",
    ],
})

question("error_identity_trial", [
    "For DI-05b, which next reporting-identity trial most informatively removes independent allocation collisions without inventing unverified external stability requirements? Include numeric consumer and rename-policy uncertainty in the decision.",
    "Which bounded DI-05b comparison should address overlapping diagnostic numbers while retaining exact nominal failures and honest report interpretation, given unknown outside numeric and cross-release requirements?",
    "Select a technical DI-05b experiment that tests independently composed error reports without assuming absent consumer evidence; weigh unresolved number-based integrations and rename stability explicitly.",
], {
    "scoped_numbers": [
        "Trial owner-scoped authored numbers and active/retired registries. Reports carry canonical owner plus local number; retirement blocks only owner-local reuse. Locks and all loader/checker/plan/report consumers use that pair, while nominal matching still includes declaration and generic arguments. Native maps/metadata suffice; source bookkeeping remains and naked integers become insufficient.",
        "Test keeping source diagnostic integers but qualifying each by canonical owner throughout registries, locks, validation plans and reports. Retired values reserve only their owner's namespace. Preserve declaration/type-argument matching independently. Use ordinary maps and error metadata; this reduces allocation change but retains duplicate authoring and requires scope in every report.",
        "Compare local numeric allocation with owner-qualified report keys, including scoped active history and retirement. Revise all registry/lock/loader/checker/runtime consumers consistently; specialization identity continues to use the declaration and concrete parameters. Native pair serialization/maps implement it. Authors still maintain numbers and readers cannot interpret an integer alone.",
    ],
    "build_numbers": [
        "Trial canonical source declaration keys with deterministic unique compact numbers allocated from the full locked graph and an archived reverse map/build identity in every report. Numbers may change after graph growth; specializations share a declaration number but retain arguments. Tombstone retired declaration keys. Migrate source/registry numbering, audit every consumer and compare map dependence against removed manual allocation.",
        "Experiment with removing authored global numbers and assigning collision-free integers during the locked build. Archive the key-to-number map and require reports to identify that build; graph edits may renumber entries. Keep declaration tombstones and concrete type arguments separately from shared declaration codes. Update source, registries and all consumers, trading manual coordination for exact-map retrieval.",
        "Evaluate generated compact diagnostic codes whose deterministic allocation covers the complete lock graph, with canonical declaration identity preserved. Ship and retain a reverse table and build key; no cross-build numeric stability is promised. Generic instances retain their parameters beside a shared declaration code, and retired keys can be tombstoned. Change authored registry/source contracts and consumers together, measuring reporting-map obligations.",
    ],
    "text_keys": [
        "Trial reporting canonical qualified declaration strings and concrete arguments directly. Optional compact numbers are build-local mapped metadata only if consumers need them; retirement and rename/reuse policy live in owner metadata. Migrate source/registry and all report consumers. Native strings suffice, avoiding mandatory reverse-map lookup at the cost of longer reports and explicit key evolution.",
        "Test self-identifying textual error keys with specialization parameters; numeric values become optional build-scoped conveniences with maps. Owner metadata governs retired identities and rename/reuse semantics. Revise authored numbering/registries and every consuming layer. Ordinary JS string metadata eliminates required map retrieval, but increases report size and makes identity evolution explicit.",
        "Compare direct qualified declaration-key reports, retaining concrete generic arguments and only optional mapped build-local integers for demonstrated consumers. Define retired-key and rename/reuse policy in owner records, then migrate source, registry and downstream readers coherently. Native textual metadata favors independent interpretation while costing report tokens and deliberate key maintenance.",
    ],
    "defer_measure": [
        "Finish identifying numeric/report consumers and cross-release rename requirements, then run duplicate/retired-ID and two-build report cases before choosing among the three schemes. Keep globally coordinated IDs as a failing composition baseline, without treating absent external users as proof no report contract matters.",
        "First complete the consumer and identity-evolution audit and execute overlapping active/retired plus changed-build report examples. Do not yet prototype a replacement; retain current coordination only as the collision-prone control. Lack of external adopters does not determine the needed report semantics.",
        "Defer scheme selection until numeric dependencies, release renames and report interpretation across two graph versions are specified and collision cases run. Today's global allocation remains the documented failing benchmark; zero outside users does not itself justify removing diagnostic contracts.",
    ],
})

question("fixture_ownership_trial", [
    "For DI-06, which bounded ownership experiment best tests deliberate cross-package fixture activation without sacrificing checked invocation/queue guarantees? Compare coverage honestly with templates, whole-helper stubs and ordinary injected callables.",
    "Choose the next DI-06 technical trial for caller-label-independent scenario behavior, retaining exact lexical FIFO execution semantics and exposing the integration-coverage tradeoff against current test/injection practices.",
    "Which limited fixture-activation comparison most usefully addresses DI-06's rename failure while preserving precise arguments and isolated occurrence paths? Account for the actual body coverage offered by existing stubs, templates and injected dependencies.",
], {
    "lexical_only": [
        "Trial selecting lexical fixtures only from their declared test scope, removing foreign short-label activation. Callers use whole-helper stubs; helper roots test internals and integration runs real bodies or ordinary injected APIs. Templates only reuse inert content. Existing contexts enforce scope without new links; cross-package simulated body coverage is deliberately absent, not claimed equivalent.",
        "Test a scope restriction on current rows so another package's root label cannot activate them. Reuse templates locally, stub a helper at the caller and test its body separately, or integrate real/injected dependencies. Retain current queue machinery with owner checks and no scenario references. This removes the fragile coupling but forgoes the caller's simulated internal helper path.",
        "Evaluate owner-local row activation and forbid ambient matching from foreign roots. Keep lexical templates, caller stubs and independent helper assertions; integration either executes real code or uses ordinary dependency injection. Enforce scope using existing assertion contexts rather than exported links. Report the lost combined helper-body simulation as a coverage limit.",
    ],
    "exported_scenarios": [
        "Trial helper-exported named configurations of its lexical fixtures. A caller explicitly links a particular helper invocation site to declaration/scenario identity; nested calls declare links too. Route recursion/participants through isolated invocation paths. Missing, inaccessible, ambiguous, unused or incompatible links diagnose. Compile plan entries into current contexts/queues, hiding helper internals at the cost of a published scenario API.",
        "Prototype a callee-owned scenario export that configures its internal lexical tables and is referenced explicitly by the caller assertion at a checked call site. Scenario/declaration identities replace display-label equality; nested links are written and recursive/concurrent invocations stay isolated. Reject missing/private/conflicting/unused/signature-invalid references. Reuse plan/context routing while measuring exported-scenario maintenance.",
        "Compare explicit invocation-site attachment to named helper scenarios controlling the helper's own rows. The identity combines declaration and scenario, with declared nested links and separate paths for recursion and participants. Diagnose unavailable, inaccessible, ambiguous, unused and type-incompatible attachments. Lower metadata into existing assertion queues; encapsulated internals trade against a new public scenario contract.",
    ],
    "exported_seams": [
        "Trial helper-approved typed symbolic seams at lexical calls. Caller roots bind fixture content along checked call paths; helper owns seam targets/signatures and caller owns behavior. Invocation identity isolates recursive/participant FIFO queues. Missing requested seams, unused required bindings and changed signatures fail. Compile bounded declared paths to existing contexts; precise control exposes more internal structure and refactor work.",
        "Test exported typed call-site seams that a root supplies through explicit verified paths. Only the helper declares eligible signatures/targets; roots choose completions. Nesting, recursion and participants combine paths with runtime invocation identity for FIFO allocation. Reject vanished requested seams, unused mandatory supplies or incompatible signatures. Use current routing plans, avoiding a global override registry but increasing structural coupling.",
        "Evaluate caller fixture attachment to specific typed seams deliberately published by a helper. Resolve a checked call path and keep seam signature ownership in the callee while behavior belongs to the root. Per-invocation paths isolate repeated/recursive/concurrent FIFO occurrences. Removed requested seams, changed types and unused required bindings diagnose. Existing contexts carry the compiled plan; greater control costs internal-detail exposure and edits.",
    ],
    "defer_measure": [
        "First benchmark lexical templates, whole-helper stubs plus separate helper assertions, and normal callable injection on the renamed-root integrated task. Preserve their explicit coverage limits and current failure evidence, but delay any fixture ownership prototype pending measured comparison.",
        "Collect controlled rename and integration results for current local templates, caller stubs with helper unit checks, and injected callables before selecting new linkage. Do not equate their coverage or deny the demonstrated label failure; postpone the ownership experiment until the baseline costs are known.",
        "Hold new ownership machinery while measuring the strongest template/stub/separate-test and ordinary injection alternatives against the root rename scenario. Record exactly which helper body each runs and the existing fragile selector behavior before choosing a bounded prototype.",
    ],
})

question("variant_policy_trial", [
    "For DI-07, which assignment-policy trial most usefully resolves the direct/bridge/leaf inconsistency while preserving nominal records, option behavior and honest codec guarantees? Choose a semantic experiment, not a brand requirement or syntax preference.",
    "Select the next DI-07 technical comparison for predictable specialization paths given flattened variants, distinct nominal record leaves and the option/codec matrix; no unprovided need for nominal branding should be assumed.",
    "Which limited DI-07 semantics trial best investigates refactor-sensitive direct versus indirect compatibility, accounting for generic records, common option leaves and wire identity without inventing a branding mandate?",
], {
    "extensional_leaves": [
        "Trial one inclusion relation over fully specialized nominal leaf sets, removing the same-declaration specialization veto. Equal phantom leaf sets admit direct/bridge/unit paths; names add no brand. some<int> and some<str> remain distinct record leaves and none is shared. Matching and codecs retain flattened leaf behavior with native tag tests. Compare agent predictions and negative nominal-record cases against today's rule.",
        "Prototype uniformly set-based variant compatibility using concrete nominal leaves, without the exceptional direct generic-instance restriction. A phantom parameter with unchanged leaves has no branding force, so all equivalent paths work; specialized some records remain distinct while none fits both. Keep current flattened tags/codecs and test record identity plus agent refactoring against the baseline.",
        "Evaluate extensional subset admission for variants after fully specializing every nominal leaf. Drop direct-only phantom-instance rejection, accepting equal-set direct and bridge/leaf routes but retaining distinct some<int>/some<str> and generic records; none belongs to either option. Native leaf tests and existing codecs need no wrapper. Measure prediction/repair and identity regressions relative to present admission.",
    ],
    "document_current": [
        "Trial better diagnostics and exact documentation of the current two-stage rule: reject differing instances of one generic variant, otherwise admit leaf subsets. Bridge/unit conversions remain legal, no provenance or durable brand is claimed, and matching/codecs stay flat. Measure whether agents can handle immediate-static-type-sensitive edits without changing semantics.",
        "Compare a tooling/documentation improvement that retains same-generic-instance rejection before other leaf inclusion. Explicitly describe the resulting legal bridges/shared leaves and absence of transitive subtyping or branding. Runtime leaf matching and wire forms remain. Test whether clear static-type-dependent diagnostics suffice for agent edits.",
        "Keep existing path-sensitive admission as the experiment's semantics and strengthen explanations: different specializations of one declaration fail directly, yet other sources use leaf inclusion. Promise neither provenance nor an unbypassable brand, and preserve flattened codecs/tests. Evaluate whether agents reliably predict/refactor this immediate-type rule with better diagnostics.",
    ],
    "nominal_wrappers": [
        "Trial distinct nominal wrapper identity for every variant/specialization, explicit leaf injection and controlled unwrapping in matches. Cross-variant movement requires exhaustive mapping/reinjection, so implicit direct/bridge/leaf escapes fail; a deliberately exported leaf may be explicitly reinjected. Use frozen branded JS wrappers unless safe erasure is proven. Codecs encode or contextually restore exact wrapper identity. Measure allocations, adapters and agent edits against existing nominal record wrappers.",
        "Prototype each variant instance as a nominal container holding an admitted leaf. Require explicit injections, narrowing unwraps and exhaustive conversions between containers; shared leaves permit only visible export-and-reinject, never implicit identity loss. Immutable tagged wrappers remain until erasure is proven. Wire decoding must recover the exact container from encoding or context. Compare conversion/allocation/repair costs with today's record-wrapper baseline.",
        "Evaluate genuine nominal variant containers per declaration and specialization. Leaf construction is explicitly injected; pattern narrowing unwraps under visibility rules, and cross-container paths use exhaustive maps plus reinjection. Block implicit specialization bridges, allowing only deliberate reinjection of an exported leaf. Freeze branded JS wrappers absent proven-safe erasure and specify codec restoration of wrapper identity. Benchmark representation and agent-adapter costs versus ordinary nominal records.",
    ],
    "defer_measure": [
        "Run the full current option/generic-record/codec/direct-bridge-leaf matrix and controlled agent refactors first, retaining today's semantics without asserting a brand. Defer a policy prototype until these broader effects and costs have executable evidence.",
        "Before choosing altered admission, expand baseline executions to options, specialized records, codecs and all bridge paths plus agent edits. State the present path dependence accurately and postpone a policy experiment pending the missing comparative data.",
        "Collect comprehensive existing-rule executions and refactor measurements across direct/indirect paths, ordinary options, generic leaves and roundtrips. Make no brand claim and select no new policy prototype until that baseline establishes the broader contract cost.",
    ],
})

def leaf_strings(value, path=()):
    if isinstance(value, dict):
        for key, item in value.items():
            yield from leaf_strings(item, path + (key,))
    elif isinstance(value, str):
        yield path, value

payloads = []
for i in range(3):
    payloads.append({"model": "jev-latest", "state": {k: v[i] for k, v in STATE.items()},
        "questions": {k: {"type": "choice", "instructions": v["instructions"][i],
            "criteria": {label: descriptions[i] for label, descriptions in v["criteria"].items()}}
            for k, v in QUESTIONS.items()}})

if __name__ == "__main__":
    leaf_maps = [dict(leaf_strings(p)) for p in payloads]
    prose_paths = [p for p in leaf_maps[0] if p != ("model",) and p[-1] != "type"]
    assert all(set(m) == set(leaf_maps[0]) for m in leaf_maps)
    assert all(len({m[p] for m in leaf_maps}) == 3 for p in prose_paths)
    pairs = []
    for a, b in itertools.combinations(range(3), 2):
        pairs.append({"requests": [a + 1, b + 1], "explanatory_fields": len(prose_paths),
            "unchanged_explanatory_paths": [".".join(p) for p in prose_paths if leaf_maps[a][p] == leaf_maps[b][p]]})
    for i, p in enumerate(payloads, 1):
        (OUT / f"request-{i}.json").write_text(json.dumps(p, indent=2) + "\n")
    audit = {
        "preparedAt": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "model": "jev-latest", "independent_questions": list(QUESTIONS),
        "manual_semantic_review": "Reviewed all three columns before sending. Facts, observation strength, goals, constraints, acceptance matrices and viable alternative contracts are equivalent. Each question asks the next technical experiment, not final semantics or user taste. All options include tradeoffs. Every family includes defer_measure. The owner_record option conservatively denies direct derived schema as well as decoding; schema of a public wire shape remains available. Technical identifiers, question keys and option labels are deliberately stable.",
        "invariants": {"validated_value_trial": "Owner record, full opacity, universal validation or baseline-first; codecs, fixtures, equality and authorization all covered.",
            "package_identity_trial": "Qualified imports, manifest handles, author-qualified declarations or baseline-first; unchanged-input limitation and separate instances preserved.",
            "error_identity_trial": "Scoped numbers, build-local numbers, direct keys or audit-first; unknown consumers/rename needs, retirement, exact generic identity and two builds preserved.",
            "fixture_ownership_trial": "Lexical-only, helper scenarios, exported seams or current-idiom-first; coverage difference, deliberate selection, exact arguments and isolated FIFO paths preserved.",
            "variant_policy_trial": "Extensional leaves, documented present admission, nominal wrappers or matrix-first; direct/bridge/leaf, option, record and codec cases preserved."},
        "full_request_wording_checks": pairs,
        "allowed_exact_strings": ["jev-latest", "choice", "JSON keys, answer labels and embedded technical identifiers"],
        "request_sha256": {str(i): hashlib.sha256((OUT / f"request-{i}.json").read_bytes()).hexdigest() for i in range(1, 4)},
        "limitations": "Text inequality is checked mechanically; equivalence is manual. This neither proves semantic identity nor removes framing bias. All alternatives share a fixed order. Prior Jev outputs are excluded from request state. Agreement remains advice, never validation.",
    }
    (OUT / "wording-audit.json").write_text(json.dumps(audit, indent=2) + "\n")
    if "--send" in sys.argv:
        key = os.environ["TYPESAFE_API_KEY"]
        for i in range(1, 4):
            req = urllib.request.Request("https://api.typesafe.ai/v1/systemone", data=(OUT / f"request-{i}.json").read_bytes(),
                headers={"Content-Type": "application/json", "Authorization": "Bearer " + key})
            started = datetime.datetime.now(datetime.timezone.utc).isoformat()
            with urllib.request.urlopen(req, timeout=60) as response:
                body, status = response.read(), response.status
            (OUT / f"response-{i}.json").write_bytes(body + b"\n")
            data = json.loads(body)
            (OUT / f"response-{i}.metadata.json").write_text(json.dumps({"startedAt": started, "status": status,
                "endpoint": "https://api.typesafe.ai/v1/systemone", "request_sha256": audit["request_sha256"][str(i)],
                "returned_model": data.get("model")}, indent=2) + "\n")
            print(json.dumps({"request": i, "model": data.get("model"), "answers": data.get("answers"), "usage": data.get("usage")}))
