"""Prepare/audit or send three independent design consultations; no probe execution."""
import datetime
import json
import os
from pathlib import Path
import sys
import urllib.request

OUT = Path(__file__).resolve().parent
CONTEXTS = [
    "We are scoping, not running, four small native mechanics checks before writing an implementation plan for replacing host tests with ordinary Can functions and Can-owned scenarios/expectations. Can targets AI authors. The eventual design has reference R judging candidate C under external Go owner N; accepted R/N executables and a Can live-entry binding are absent. Preparatory host observations cannot qualify R/N, credit migration, or retire tests. Existing local inputs are pinned Bun 1.4.2, Python 3.14.7 with os.posix_spawn descriptor actions, Go 1.27.1, and Playwright 1.55.1; no compiler distribution is materialized. The MacBook has a 256 GB disk; broad builds, downloads and measurements are deferred. Each proposed job has one question, independent fixed observations, a deliberate failing control, a finite deadline and external cleanup. A temporary Python parent can own a fixed child graph, pipe fd 3 JSON independently of binary fd 0, record ownership before effects, stop/reap on all handled exits and remove its own scratch. This would investigate POSIX-to-Bun transport, not Go ExtraFiles or the product launcher. It cannot prove recovery after its own death or arbitrary detached-child containment; those stay open. A Go parent could instead use os.Pipe and exec.Cmd.ExtraFiles like the product, requiring a small stdlib build and bounded cache accounting. Building full N first would add the runner implementation before mechanics research. PM-N1 uses numeric handles to keep a getter-backed then object inert. PM-N2 can directly import C runtime/codec/json.ts::encodeJSON, supply a tiny array/int schema, pass an array with a throwing index getter and independently expect reason type, empty path and zero getter calls. Reading the index in a disposable control must fail that expectation. This proves only this source-module ingress: no compiled Can invocation, generated state or R oracle. The integrated N2 still needs a C artifact, same-realm typed binding, invocation witness and qualified R/N. A full compiler build now might reach that boundary but exceeds the small source-mechanics scope; deferring this check entirely would retain the source-derived uncertainty. Browser scope has a held POST form navigation, actual click settlement observation and external route decision; early native click settlement is inconclusive. No DB is needed. All outcomes remain unrun at this design step.",
    "The current deliverable defines four bounded experiments; execution and production implementation are later steps. Our replacement suite must use normal Can code for helpers, scenarios and assertions, optimized for AI agents. Its selected architecture separates an accepted reference R, candidate C and generic Go supervisor N, but R/N binaries and the ordinary-Can live entry do not yet exist. Early foreign-language mechanics evidence gives no reference promotion, migration coverage or old-harness deletion authority. Available tools include Bun 1.4.2 pinned locally, Python 3.14.7 exposing os.posix_spawn file actions, Go 1.27.1 and Playwright 1.55.1; a built Can compiler is unavailable. Storage/load matter on a 256 GB MacBook, and broad compilation, dependency downloads and benchmarks remain postponed. Every scoped experiment requires a single falsifiable question, independent expected facts, a seeded defect, bounded time and cleanup outside the subject. One option is a short-lived Python controller for a known process tree: pre-record ownership, map a JSON pipe to fd 3 while reserving fd 0 for bytes, reap stopped children and delete only its owned directory on normal/error/signal exits. That demonstrates POSIX descriptor delivery to Bun, not the Go launcher implementation. Controller death and unconstrained detached descendants are outside its proof. A second option builds a tiny Go stdlib controller using os.Pipe/exec.Cmd.ExtraFiles, closer to the product but adding compilation and cache limits. Completing N instead would move substantial implementation ahead of the feasibility study. Numeric handles in PM-N1 protect an object whose then getter counts and throws. The smallest PM-N2 imports the existing candidate export runtime/codec/json.ts::encodeJSON, with a minimal int-array schema and getter-bearing array. A separate parent expects type rejection at the empty path without any index read; deliberately accessing the index in a disposable shim supplies the failure control. Such evidence concerns direct source-module access only, leaving emitted Can calls, generated factory state and reference judging unverified. Integrated N2 continues to require a compiled C subject, typed same-realm access, a call witness and accepted R/N. Building C now would test more but expand this preparation; postponing all ingress observation is another alternative. The browser proposal intercepts form POST navigation and measures the real click promise while an external decision releases the route; a click that already settled leaves the pending-input question unanswered. It uses no database. Nothing has been executed in this scoping round.",
    "We need experimental job definitions before implementation planning, with four future checks and no runs today. Ordinary Can functions must eventually own all scenario logic and expectations; agent authors are the intended audience. The agreed system assigns judgment to qualified R, subjects to C and resource management to a separate Go N. No accepted R/N program or Can live-probe entry is available, so preliminary host-measured results must remain design evidence and cannot accept tools, replace coverage or remove existing harnesses. Local inventory includes the pinned Bun 1.4.2, Python 3.14.7 supporting os.posix_spawn descriptor mappings, Go 1.27.1 and Playwright 1.55.1, but no materialized Can compiler. The 256 GB laptop requires small disk/load budgets; large builds, installations and performance work are on hold. Each proposed check names one uncertainty, raw or fixed independent measurements, a fault injection, an end-to-end time cap and an external resource owner. A minimal Python host process could register a controlled child graph before launching, deliver fd 3 JSON separately from fd 0 binary data, retain kill/wait authority and reclaim marked scratch after success, failure or handled interruption. Its conclusion would cover POSIX/Bun descriptor mechanics, excluding Go ExtraFiles/product-launcher correctness, owner-death recovery and arbitrary detached descendants. Alternatively a small compiled Go parent would exercise os.Pipe with exec.Cmd.ExtraFiles at the cost of a stdlib build and explicit build-cache budget. Implementing the complete N would be a larger prerequisite. The native transport proposal PM-N1 refers to a then-getter object only through integer IDs. For PM-N2 the existing runtime/codec/json.ts::encodeJSON export accepts a minimal schema for an int array; a hostile own-index accessor should yield type with an empty path and no getter executions. An independently checked count changes under an intentional index-read shim. This source-level call cannot establish C-generated ordinary Can ingress, emitted state wiring or an R verdict. Those integrated N2 requirements retain a C output identity, typed same-realm seam, invocation evidence and accepted R/N. Producing C now broadens the experiment beyond direct-module mechanics, while waiting until integration leaves this narrower empirical question open. Browser preparation uses a paused form-navigation POST, direct observation of Playwright click settlement and a route response chosen in another process; premature click completion is recorded as inconclusive. Database work is excluded. All four proposals are still unrun."
]
QUESTIONS = {
    "temporary_owner": {
        "instructions": ["Which initial resource-owner instrument best fits the bounded preparatory scope?", "Choose the appropriate first host controller for these limited mechanics observations.", "What supervision setup should these preliminary jobs start with under the stated constraints?"],
        "criteria": {
            "python_scoped": ["Use the reviewed Python parent and POSIX descriptor mapping, explicitly excluding Go/product and owner-death guarantees; retain full N qualification later.", "Select temporary Python supervision of the fixed graph, credit only POSIX-to-Bun mechanics and leave Go launcher and supervisor-loss acceptance for later.", "Start with the small Python instrument and record its bounded authority; postpone claims about Go integration, parent death and complete N."],
            "go_small": ["Build a small Go parent now so descriptor preparation uses os.Pipe/ExtraFiles, with a separately bounded stdlib compilation and temporary cache.", "Choose a minimal Go executable as the early controller, accepting an explicitly limited build/cache allocation to match product descriptor setup.", "Use a tiny compiled Go instrument first, budgeting compilation resources in exchange for directly exercising the product-style pipe mapping."],
            "full_owner": ["Require the full generic Go N implementation and its acceptance before any of these preliminary native observations.", "Delay all four mechanics checks until complete N supervision is implemented and qualified.", "Make the finished Go resource service a prerequisite for starting this exploratory work."]
        }
    },
    "source_ingress": {
        "instructions": ["Which next probe scope is appropriate for the candidate ingress uncertainty?", "Select the first empirical boundary to investigate for PM-N2.", "How should this preparation address hostile-value access to candidate code?"],
        "criteria": {
            "source_partial": ["Scope the direct encodeJSON source-module check now and leave compiled ordinary-Can ingress explicitly unproven.", "Investigate the existing codec export first as partial mechanics evidence, preserving the generated-Can gate as unfinished.", "Use the small source-import experiment to inform ingress design without claiming the later Can artifact integration."],
            "compiled_now": ["Expand preparation to build C and a tiny ordinary Can subject with a typed hostile-value seam before collecting ingress evidence.", "Materialize a candidate compiler/Can output and its binding during this preparatory stage to examine the complete subject ingress.", "Require the compiled Can boundary in the immediate experiment, including candidate build and typed access implementation."],
            "defer": ["Skip source-module execution and leave all candidate ingress experimentation until the implementation lanes provide C and its binding.", "Postpone empirical ingress work entirely until production implementation supplies the compiled subject and interface.", "Retain only the source analysis for now and schedule every ingress run after C integration becomes available."]
        }
    }
}

if "--send" not in sys.argv:
    fields = [CONTEXTS] + [q["instructions"] for q in QUESTIONS.values()] + [v for q in QUESTIONS.values() for v in q["criteria"].values()]
    assert all(len(set(v)) == 3 for v in fields)
    for i in range(3):
        request = {"model": "jev-latest", "state": CONTEXTS[i], "questions": {name: {"type": "choice", "instructions": q["instructions"][i], "criteria": {k: v[i] for k, v in q["criteria"].items()}} for name, q in QUESTIONS.items()}}
        (OUT / f"request-{i+1}.json").write_text(json.dumps(request, indent=2) + "\n")
    (OUT / "wording-audit.json").write_text(json.dumps({"status": "reviewed before sending", "semantic_review": "All three retain tools, trust limits, user scope, source seam, controls, missing artifacts, browser uncertainty, resource constraints and identical alternatives. Every explanatory field has been rewritten and full-field inequality checked. No response is included in another request.", "question_alternatives": {k: list(q["criteria"]) for k,q in QUESTIONS.items()}, "limitations": "Advice only; neither consensus nor confidence is experimental proof or guaranteed bias removal."}, indent=2) + "\n")
    print("Saved three requests and pre-send audit.")
else:
    number = int(sys.argv[-1])
    assert number in (1, 2, 3)
    target = OUT / f"response-{number}.json"
    if target.exists():
        raise SystemExit("Response exists; refusing overwrite")
    started = datetime.datetime.now(datetime.timezone.utc).isoformat()
    request = urllib.request.Request("https://api.typesafe.ai/v1/systemone", data=(OUT / f"request-{number}.json").read_bytes(), headers={"Content-Type": "application/json", "Authorization": "Bearer " + os.environ["TYPESAFE_API_KEY"]})
    with urllib.request.urlopen(request, timeout=50) as response:
        data = response.read()
        status = response.status
    target.write_bytes(data + b"\n")
    (OUT / f"response-{number}.metadata.json").write_text(json.dumps({"started_utc": started, "http_status": status}, indent=2) + "\n")
    result = json.loads(data)
    print(json.dumps({"request": number, "model": result.get("model"), "answers": result.get("answers"), "usage": result.get("usage")}))
