"""Shared capability design consultation; never runs test subjects."""
import datetime
import json
import os
from pathlib import Path
import sys
import urllib.error
import urllib.request

OUT = Path(__file__).resolve().parent
CONTEXTS = [
    "Specify native capability contracts for a Can test suite authored by AI agents. Ordinary unrestricted Can functions own scenario order, expected values, scheduling, readiness/retries and reports; authored foreign harnesses must disappear. The chosen execution uses a qualified reference compiler/runtime for the Can controller and fresh Bun case processes, with candidate compilers/runtime/browser artifacts only as subjects and a generic Go supervisor outside them. No implementation, live trials or measurements are authorized; laptop load/storage are bounded. Current assertion supervision kills its direct worker, buffers output before truncating, and does not establish complete filesystem/descendant cleanup. Current process::run uses detached Bun.spawn children and registers cleanup after spawn, but worker SIGKILL skips worker-local cleanup. New resources therefore need reservations and ownership outside the worker before exposure, operation IDs with argument digests, bounded event/byte streams, explicit partial effects and recovery. Absolute path validation alone is not confinement; OS-enforced disk/descendant guarantees must be qualified or refused as unsupported. Native process start/signal returns execution/delivery facts, never server readiness; nonzero exits are observations. A deadline during a state-changing operation can leave an accepted effect with an unknown result, so Can must not blindly retry it. Browser tests require physical and synthetic actions, independent property versus attribute reads, interception with deferred Can decisions, and an armed-before-navigation event stream closed by a bounded drain/seal barrier. Remote Firefox sessions may be owned while the service is shared. JS-source eval or a native whole-scenario helper would retain host-authored policy. Typed native value constructors, one-operation observers and counters can expose proxies/getters/thenables/raw identity; ordinary compiled Can probe programs can handle additional callback logic in the candidate realm. Expected results stay Can-owned and native handles do not cross process heaps. Native fault masking must affect disposable candidate processes, not the trusted judge. SQL facts must come through an independently identified connection/decoder with raw values. Compiler CheckSnapshot performs inert frontend analysis and gives code/severity/UTF16 spans, but folds project failures into diagnostics and omits per-diagnostic phase provenance. A proposed general canlc check --json product CLI needs explicit complete accepted/rejected versus infrastructure-failure statuses, diagnostic stage provenance, versioned schema and source identities. It must not run assertions, emit/publish or execute subjects. Candidate command crashes, malformed reports, cancellation and IO failures cannot count as expected source rejection. This CLI work must classify failures at their source rather than infer them from diagnostic strings.",
    "The task is design-only shared platform contracts for AI-authored Can testing, with no builds, benchmarks or live tests. Can cases/helpers are ordinary full-language functions and own actions, oracles, scheduling, polling and reporting; foreign authored test harnesses are to be removed. A qualified reference toolchain runs a Can controller and separate fresh Bun workers, while a generic Go parent supervises them and candidate compiler/runtime/browser output is exercised as a subject. Preserve bounded laptop resources and cleanup. The present assertion supervisor reaps only its immediate worker and truncates diagnostics after buffering; it is not a proven disk/process-tree sandbox. Existing process::run spawns detached children through Bun and installs worker-owned cleanup after launch, which cannot execute after SIGKILL. Proposed acquisition must reserve ownership externally before exposing resources, using request identity/digests, bounded evidence and explicit recovery/partial-result states. Checking a pathname is insufficient containment; advertise strict host enforcement only when proved, otherwise reject that capability. Process creation and signal receipts are mechanical facts, not health checks, and exit codes including failure are data. Time limits do not necessarily undo state changes, making unqualified automatic retries unsafe. Browser coverage needs real input and synthetic events, native live-property/attribute distinctions, paused requests answered by Can and event recording active before navigation with bounded final drainage. A remote browser service can remain shared even though its context is case-owned. Arbitrary JavaScript source execution or fixed native test legs violate the intended policy boundary. Generic native-value builders and factual observations/counters should expose hostile getters/proxies, thenables and identity; extra callbacks can be ordinary compiled Can probes inside a disposable candidate realm. No expected verdict belongs to the observer, and raw handles stay in their heap. Fault installation is confined to candidate probe processes. Independent SQL observation identifies its separate connection/decoder and preserves raw values. The current inert CheckSnapshot returns structured diagnostics and UTF16 ranges but represents project errors as diagnostics and lacks diagnostic phase metadata. A public canlc check --json interface must distinguish completed source acceptance/rejection from invocation/IO/internal faults, expose pipeline provenance, bind versioned output to input/compiler identity and avoid assertions, code emission or publication. A crash, truncated output or cancelled check cannot satisfy a rejection expectation. Failure categories need producer-level metadata, not parsing English messages.",
    "Design contracts, without executing code or measurements, for shared capabilities in a native Can suite. The author is an AI agent; keep full ordinary Can and assign scenario choices, expected observations, selection, readiness/retry logic and verdicts to Can rather than host harnesses. Initial architecture is reference-built Can orchestration and fresh Bun workers under an external generic Go supervisor; candidate compiler, runtime and browser artifacts are subjects. Hard laptop load/storage and owned cleanup remain requirements. Source evidence shows direct-worker termination and post-buffer diagnostic truncation in the assertion supervisor; complete tree/filesystem containment is absent. The one-shot process::run performs detached Bun.spawn then worker-local cleanup registration, leaving cleanup unavailable if that worker is killed. The new interface needs parent-owned reservations before resource exposure, deduplicated operation identities tied to arguments, bounded facts, partial effects and recovery records. Path normalization cannot substitute for OS enforcement; a host lacking a promised hard limit must report unsupported. Spawn and signal acknowledge native actions rather than service readiness; normal returned process facts include nonzero exit. Interrupted side effects can remain applied or indeterminate, so a timed-out call cannot be assumed safe to repeat. Browser primitives must cover physical input, synthetic dispatch, independent property/attribute reads, deferred interception decisions and event collection armed before navigation with a closing barrier. Shared remote Firefox ownership stops at the owned connection/context. Neither JavaScript strings nor native scenario-sized procedures satisfy Can ownership. Primitive foreign-value construction and single-operation observation can provide getter/proxy/thenable counters and raw identity, supplemented by normal Can programs for richer callbacks in the candidate process. Comparisons are Can code; handles stay process-local and faults affect only disposable subjects. SQL observation needs separate connection/decoder provenance and raw data. Compiler CheckSnapshot is inert and supplies structured code/severity/UTF16 location data, while converting project faults into diagnostics and lacking individual pipeline-stage fields. A general product canlc check --json must add an explicit schema, phase/error taxonomy and input identity, returning complete analysis acceptance/rejection separately from unavailable or broken execution. It must never execute assertions or subjects, emit code or publish. Unexpected death, malformed results, cancellation and filesystem failures are not source rejection, and categorization must originate in the frontend rather than stderr wording."
]
Q = {
    "resource_authority": {
        "instructions": ["Which ownership contract should these shared native operations adopt?", "Select the resource lifetime boundary for the capability specification.", "Choose the acquisition and cleanup authority model to document."],
        "criteria": {
            "outside_worker": ["Reserve and retain resource authority in a native owner outside workers before exposure; use operation IDs, explicit uncertain/partial outcomes, bounded cleanup receipts and host enforcement admission.", "Place ownership and recovery in the supervised external resource service, register reservations before use and preserve partial effects with idempotent request identities and enforced bounds.", "Use an external native resource ledger and acquisition reservations, keeping cleanup viable after worker death and reporting bounded facts including uncertainty and unsupported enforcement."],
            "worker_scopes": ["Keep resource authority in worker-local scopes and ordinary Can teardown, with the outer supervisor only terminating/reaping the worker and reporting abandoned resource risk.", "Use the worker's existing resource owner for lifetime and cleanup, letting parent supervision report that cleanup may be incomplete after abrupt worker loss.", "Base the contract on local scope finalization inside each worker, acknowledging that outer process termination cannot itself reclaim every worker-owned resource."],
            "recovery_scan": ["Launch resources from workers and rely on later native scanning of process/path ownership records to recover abandoned work, minimizing synchronous broker participation but accepting an acquisition recovery window.", "Prefer direct worker acquisition followed by external ownership discovery and recovery scans, documenting the gap before resources are fully identified.", "Keep native launch local and reconstruct cleanup ownership after failures from persisted markers and scans, trading simpler active calls for uncertain pre-registration recovery."]
        }
    },
    "observation_boundary": {
        "instructions": ["Which boundary should define browser and independent native observations?", "Choose the shared external observation interface under full Can authorship.", "How should these contracts expose browser and raw native behavior to Can cases?"],
        "criteria": {
            "typed_facts": ["Expose bounded typed actions, event streams, foreign-value construction and individual facts; Can chooses order and expectations, with ordinary Can probes for richer callbacks and no foreign-source escape hatch.", "Use general typed operations and sealed observations with Can-driven decisions, native value/counter mechanics and compiled Can callback programs where necessary.", "Specify small native mechanisms returning facts and supporting raw-value handles, while full Can code supplies choreography, callbacks requiring logic and comparisons."],
            "source_eval": ["Allow Can to submit JavaScript source to browser/native contexts and compare returned data in Can, retaining foreign-authored callbacks as part of the testing contract.", "Provide a JavaScript evaluation channel for observations and leave top-level expectations in Can, accepting embedded host-authored scenario fragments.", "Adopt source-string execution inside the browser/probe as the extensibility mechanism, with Can consuming results and foreign code defining those local actions."],
            "scenario_adapters": ["Provide native operations for entire browser/native scenario families returning result summaries, with Can handling registration and final comparisons.", "Move each multi-step observation leg into a native family-specific adapter that yields a summary for Can to assess.", "Package complete driver/probe sequences into native calls and expose their aggregate observations to the Can suite."]
        }
    },
    "compiler_diagnostics": {
        "instructions": ["Which compiler-diagnostic boundary should this contract choose?", "Select how Can cases should obtain candidate compiler analysis facts.", "Choose the diagnostic interface to specify for compiler rejection cases."],
        "criteria": {
            "product_cli": ["Define general canlc check --json with explicit frontend fault/phase provenance and complete-report statuses; use generic managed-process execution and Can report parsing/expectations.", "Add a structured product checking command that separates completed diagnostics from infrastructure failure, run it as the candidate process and keep interpretation in Can.", "Specify a candidate CLI JSON analysis protocol with source identities, stage taxonomy and unambiguous status meanings, accessed through ordinary process and Can parsing helpers."],
            "language_primitive": ["Expose semantic compiler checking as a new native Can operation with explicit candidate identity and isolation, designing its binding/protocol instead of a public CLI first.", "Introduce a compiler-check language binding that invokes an identified isolated candidate and returns typed diagnostics directly, with a new native API contract.", "Make compiler analysis a native Can primitive carrying candidate provenance and isolated execution, accepting compiler-specific runtime integration."],
            "stderr_adapter": ["Keep existing compiler commands and define a Can stderr/status parser as the primary rejection interface, maintaining wording/phase parsing without a new structured product command.", "Use current failing invocations and Can-owned text parsing for diagnostic identity and stage, accepting dependencies on stderr shape.", "Specify exit-plus-stderr analysis in Can over the existing CLI, with explicit textual parsing contracts instead of adding structured check output."]
        }
    }
}
for values in [CONTEXTS]+[v['instructions'] for v in Q.values()]+[x for v in Q.values() for x in v['criteria'].values()]:
    assert len(values)==3 and len(set(values))==3
for i in range(3):
    request={'model':'jev-latest','state':CONTEXTS[i],'questions':{k:{'type':'choice','instructions':v['instructions'][i],'criteria':{a:d[i] for a,d in v['criteria'].items()}} for k,v in Q.items()}}
    (OUT/f'request-{i+1}.json').write_text(json.dumps(request,indent=2)+'\n')
(OUT/'wording-audit.json').write_text(json.dumps({'status':'reviewed before send','method':'Manual semantic comparison and full-field inequality across all three complete contexts, questions and option descriptions. Exact technical identifiers and alternatives preserved; prior answers are not reused.','equivalent_facts':['agent/full-Can and Can-owned scenarios/oracles','chosen reference/candidate/process architecture','design-only resource limits and cleanup','current native containment/registration/output gaps','external ownership, partial effects, deadlines and retry ambiguity','browser input/interception/sealed-events and shared-service ownership','typed raw native value/callback/fault boundaries','independent SQL provenance','CheckSnapshot strengths and producer-level classification gaps'],'limits':'Rewording and agreement do not prove bias removal, enforceability or correctness.'},indent=2)+'\n')
if '--send' in sys.argv:
    for i in range(1,4):
        started=datetime.datetime.now(datetime.timezone.utc).isoformat()
        request=urllib.request.Request('https://api.typesafe.ai/v1/systemone',data=(OUT/f'request-{i}.json').read_bytes(),headers={'Content-Type':'application/json','Authorization':'Bearer '+os.environ['TYPESAFE_API_KEY']})
        try:
            with urllib.request.urlopen(request,timeout=55) as response: body,status=response.read(),response.status
        except urllib.error.URLError as error:
            (OUT/f'transport-error-{i}.json').write_text(json.dumps({'started_utc':started,'kind':type(error).__name__,'reason':str(error.reason)},indent=2)+'\n')
            raise SystemExit('Consultation transport failed; metadata saved.')
        (OUT/f'response-{i}.json').write_bytes(body+b'\n')
        (OUT/f'response-{i}.metadata.json').write_text(json.dumps({'started_utc':started,'http_status':status},indent=2)+'\n')
        parsed=json.loads(body)
        print(json.dumps({'request':i,'model':parsed.get('model'),'answers':parsed.get('answers'),'usage':parsed.get('usage')}))
